import { StyleSheet } from 'react-native';

export const aboutStyles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  topBar: {
    backgroundColor: '#142C4C',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    paddingBottom: 12,
    paddingHorizontal: 20,
    paddingTop: 50,
  },
  topBarTitle: {
    color: '#ffffff',
    fontFamily: 'Jomolhari',
    fontSize: 22,
    includeFontPadding: false,
    lineHeight: 32,
  },
  topBarLogo: {
    height: 34,
    marginLeft: 4,
    width: 40,
  },
  hero: {
    minHeight: 256,
    justifyContent: 'center',
  },
  heroOverlay: {
    backgroundColor: 'rgba(20, 44, 76, 0.58)',
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 18,
    paddingVertical: 28,
  },
  heroEyebrow: {
    color: '#ffffff',
    fontFamily: 'InterBold',
    fontSize: 15,
    includeFontPadding: false,
    lineHeight: 20,
    marginBottom: 8,
  },
  heroTitle: {
    color: '#ffffff',
    fontFamily: 'Jomolhari',
    fontSize: 28,
    includeFontPadding: false,
    lineHeight: 38,
  },
  heroScript: {
    color: '#ffffff',
    fontFamily: 'Italianno',
    fontSize: 42,
    includeFontPadding: false,
    lineHeight: 46,
  },
  heroScriptSmall: {
    fontSize: 36,
    lineHeight: 40,
  },
  heroTagline: {
    color: '#ffffff',
    fontFamily: 'Inter',
    fontSize: 12,
    includeFontPadding: false,
    letterSpacing: 2,
    lineHeight: 18,
    marginTop: 16,
  },
  sheet: {
    backgroundColor: '#ffffff',
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
    marginTop: -20,
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  quoteCard: {
    backgroundColor: '#D8E3F2',
    borderRadius: 16,
    marginBottom: 24,
    padding: 16,
  },
  quoteText: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 16,
    fontStyle: 'italic',
    includeFontPadding: false,
    lineHeight: 22,
  },
  eyebrow: {
    color: '#62748C',
    fontFamily: 'InterBold',
    fontSize: 13,
    includeFontPadding: false,
    lineHeight: 18,
    marginBottom: 4,
  },
  sectionTitle: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 24,
    includeFontPadding: false,
    lineHeight: 34,
    marginBottom: 12,
  },
  sectionTitleLarge: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 28,
    includeFontPadding: false,
    lineHeight: 39,
    marginBottom: 16,
  },
  bodyText: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 15,
    includeFontPadding: false,
    lineHeight: 22,
    marginBottom: 16,
  },
  centerText: {
    textAlign: 'center',
  },
  storyImage: {
    borderRadius: 10,
    height: 200,
    marginBottom: 16,
    width: '100%',
  },
  storyImageTall: {
    height: 260,
  },
  scriptQuote: {
    color: '#122D48',
    fontFamily: 'Italianno',
    fontSize: 25,
    includeFontPadding: false,
    lineHeight: 34,
    marginVertical: 20,
    textAlign: 'center',
  },
  scriptQuoteCenter: {
    color: '#142C4C',
    fontFamily: 'Italianno',
    fontSize: 27,
    includeFontPadding: false,
    lineHeight: 36,
    marginBottom: 20,
    textAlign: 'center',
  },
  serviceCard: {
    borderColor: '#A9B7CA',
    borderRadius: 16,
    borderWidth: 1,
    marginBottom: 16,
    overflow: 'hidden',
  },
  serviceImage: {
    height: '100%',
    width: '100%',
  },
  serviceLabelBadge: {
    backgroundColor: '#142C4C',
    borderRadius: 10,
    left: 12,
    maxWidth: '90%',
    paddingHorizontal: 14,
    paddingVertical: 7,
    position: 'absolute',
    top: 10,
  },
  serviceLabel: {
    color: '#FFFFFF',
    fontFamily: 'InterSemiBold',
    fontSize: 18,
    includeFontPadding: false,
    lineHeight: 26,
  },
  moreThanPhotos: {
    color: '#142C4C',
    fontFamily: 'Inter',
    fontSize: 14,
    includeFontPadding: false,
    lineHeight: 20,
    marginTop: 8,
    textAlign: 'center',
  },
  wideImage: {
    borderRadius: 10,
    height: 260,
    marginVertical: 16,
    width: '100%',
  },
  lowerSection: {
    backgroundColor: '#F8EFEF',
    paddingHorizontal: 20,
    paddingTop: 40,
  },
  whyRow: {
    alignItems: 'center',
    backgroundColor: '#DCE4F0',
    borderRadius: 10,
    flexDirection: 'row',
    marginBottom: 12,
    padding: 12,
  },
  iconCircle: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 28,
    height: 56,
    justifyContent: 'center',
    marginRight: 14,
    width: 56,
  },
  contactIconCircle: {
    backgroundColor: '#D8E3F2',
  },
  whyTextWrap: {
    flex: 1,
    minWidth: 0,
  },
  whyTitle: {
    color: '#4C5E76',
    fontFamily: 'InterBold',
    fontSize: 15,
    includeFontPadding: false,
    lineHeight: 20,
  },
  whyDescription: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 13,
    includeFontPadding: false,
    lineHeight: 18,
    marginTop: 2,
  },
  contactCardsWrap: {
    marginTop: 12,
  },
  contactCard: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 16,
    elevation: 2,
    flexDirection: 'row',
    marginBottom: 12,
    padding: 14,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
  },
  contactTextWrap: {
    flex: 1,
    minWidth: 0,
  },
  contactTitle: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 16,
    includeFontPadding: false,
    lineHeight: 24,
    marginBottom: 4,
  },
  contactLine: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 13,
    includeFontPadding: false,
    lineHeight: 18,
  },
  footerText: {
    color: '#395276',
    fontFamily: 'Inter',
    fontSize: 13,
    includeFontPadding: false,
    lineHeight: 20,
    marginTop: 20,
    textAlign: 'center',
  },
});
