import { StyleSheet } from 'react-native';

import { adminColors } from '@/styles/admin-theme';

export const adminCalendarSlotsStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: adminColors.canvas },
  timeSlotFigmaContent: { flexGrow: 1, paddingHorizontal: 18, width: '100%', maxWidth: 760, alignSelf: 'center' },
  figmaDateHeaderRow: { alignItems: 'center', flexDirection: 'row', gap: 12, paddingVertical: 16 },
  figmaBackButton: { alignItems: 'center', justifyContent: 'center', width: 44, height: 44, backgroundColor: adminColors.surface, borderColor: adminColors.border, borderWidth: 1, borderRadius: 14 },
  figmaDatePill: { flex: 1, minWidth: 0, minHeight: 52, alignItems: 'center', flexDirection: 'row', gap: 10, backgroundColor: adminColors.surface, borderColor: adminColors.border, borderWidth: 1, borderRadius: 16, paddingHorizontal: 14, paddingVertical: 12 },
  figmaDatePillText: { flex: 1, color: adminColors.ink, fontFamily: 'InterSemiBold', fontSize: 16, lineHeight: 23 },
  figmaSlotLegend: { alignItems: 'center', flexDirection: 'row', flexWrap: 'wrap', gap: 18, paddingVertical: 8 },
  figmaLegendItem: { alignItems: 'center', flexDirection: 'row', gap: 7 },
  figmaLegendDot: { borderRadius: 5, height: 8, width: 8 },
  figmaAvailableDot: { backgroundColor: adminColors.green },
  figmaBookedDot: { backgroundColor: adminColors.blue },
  figmaUnavailableDot: { backgroundColor: adminColors.red },
  figmaLegendText: { color: adminColors.muted, fontFamily: 'InterMedium', fontSize: 13, lineHeight: 19 },
  figmaTimeSlotHeader: { alignItems: 'center', flexDirection: 'row', flexWrap: 'wrap', gap: 12, justifyContent: 'space-between', marginTop: 20 },
  figmaTimeSlotTitle: { color: adminColors.ink, fontFamily: 'InterBold', fontSize: 24, lineHeight: 32, flexShrink: 1 },
  figmaEditButton: { alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 8, minHeight: 44, paddingHorizontal: 18, paddingVertical: 10, backgroundColor: adminColors.blue, borderRadius: 13 },
  figmaEditButtonText: { color: adminColors.surface, fontFamily: 'InterSemiBold', fontSize: 14, lineHeight: 21 },
  adminPageSubtitle: { color: adminColors.muted, fontFamily: 'Inter', fontSize: 14, lineHeight: 22, backgroundColor: adminColors.surface, borderColor: adminColors.border, borderWidth: 1, borderRadius: 14, padding: 14, marginTop: 16 },
  figmaTimeSlotList: { gap: 12, marginTop: 18 },
  figmaSlotCard: { backgroundColor: adminColors.surface, borderColor: adminColors.border, borderWidth: 1, borderRadius: 18, padding: 16 },
  figmaSlotCardTop: { alignItems: 'center', flexDirection: 'row', gap: 12, justifyContent: 'space-between' },
  slotCardCompact: { alignItems: 'flex-start', flexDirection: 'column' },
  slotIdentity: { alignItems: 'center', flexGrow: 1, flexShrink: 1, flexBasis: 'auto', minWidth: 0, flexDirection: 'row', gap: 12 },
  slotIdentityCompact: { flexGrow: 0, flexShrink: 0, flexBasis: 'auto', width: '100%' },
  figmaSlotCopy: { flex: 1, minWidth: 0 },
  figmaSlotTime: { color: adminColors.ink, fontFamily: 'InterSemiBold', fontSize: 16, lineHeight: 23 },
  figmaSlotDuration: { color: adminColors.muted, fontFamily: 'Inter', fontSize: 13, lineHeight: 20, marginTop: 3 },
  figmaStatusPill: { alignItems: 'center', alignSelf: 'flex-start', flexDirection: 'row', flexShrink: 0, gap: 6, borderRadius: 10, minHeight: 30, paddingHorizontal: 10, paddingVertical: 6 },
  figmaStatusPillDot: { borderRadius: 4, height: 6, width: 6, flexShrink: 0 },
  figmaStatusPillText: { flexShrink: 0, fontFamily: 'InterSemiBold', fontSize: 12, lineHeight: 18 },
  availableSlotPill: { backgroundColor: adminColors.greenSoft },
  bookedSlotPill: { backgroundColor: adminColors.blueSoft },
  unavailableSlotPill: { backgroundColor: adminColors.redSoft },
  availableSlotPillText: { color: adminColors.green },
  bookedSlotPillText: { color: adminColors.blue },
  unavailableSlotPillText: { color: adminColors.red },
  figmaBookedInfoBox: { backgroundColor: adminColors.blueSoft, borderRadius: 12, marginTop: 14, paddingHorizontal: 14, paddingVertical: 12, gap: 3 },
  figmaBookedClient: { color: adminColors.ink, fontFamily: 'InterSemiBold', fontSize: 14, lineHeight: 21 },
  figmaBookedPackage: { color: adminColors.muted, fontFamily: 'Inter', fontSize: 13, lineHeight: 20 },
  manageDateScreen: { flex: 1, backgroundColor: adminColors.canvas },
  manageDateContent: { flexGrow: 1, paddingHorizontal: 18, maxWidth: 760, width: '100%', alignSelf: 'center' },
  manageDateHeader: { alignItems: 'center', flexDirection: 'row', gap: 14, paddingVertical: 16 },
  manageDateBackButton: { alignItems: 'center', justifyContent: 'center', width: 44, height: 44, borderRadius: 14, backgroundColor: adminColors.surface, borderColor: adminColors.border, borderWidth: 1 },
  manageDateTitle: { flex: 1, color: adminColors.ink, fontFamily: 'InterBold', fontSize: 24, lineHeight: 32 },
  manageDateCard: { backgroundColor: adminColors.surface, borderColor: adminColors.border, borderWidth: 1, borderRadius: 20, padding: 16 },
  manageDateLabel: { color: adminColors.ink, fontFamily: 'InterSemiBold', fontSize: 14, lineHeight: 21 },
  manageDateInput: { alignItems: 'center', flexDirection: 'row', gap: 12, minHeight: 54, paddingHorizontal: 14, paddingVertical: 12, backgroundColor: adminColors.canvas, borderRadius: 13, borderColor: adminColors.border, borderWidth: 1, marginTop: 8, marginBottom: 24 },
  manageDateInputText: { flex: 1, minWidth: 0, color: adminColors.ink, fontFamily: 'InterMedium', fontSize: 15, lineHeight: 22 },
  manageDateSectionLabel: { color: adminColors.ink, fontFamily: 'InterSemiBold', fontSize: 16, lineHeight: 23 },
  manageStatusOptions: { gap: 10, marginTop: 10 },
  dayAvailabilityOption: { alignItems: 'center', flexDirection: 'row', gap: 12, minHeight: 52, paddingHorizontal: 14, paddingVertical: 12, backgroundColor: adminColors.surface, borderColor: adminColors.border, borderWidth: 1, borderRadius: 13 },
  activeAvailableOption: { backgroundColor: adminColors.greenSoft, borderColor: adminColors.green },
  activeUnavailableOption: { backgroundColor: adminColors.redSoft, borderColor: adminColors.red },
  radioOuter: { alignItems: 'center', justifyContent: 'center', borderColor: adminColors.muted, borderRadius: 10, borderWidth: 1.5, height: 20, width: 20 },
  availableRadioOuter: { borderColor: adminColors.green },
  unavailableRadioOuter: { borderColor: adminColors.red },
  radioInner: { borderRadius: 5, height: 10, width: 10 },
  availableRadioInner: { backgroundColor: adminColors.green },
  unavailableRadioInner: { backgroundColor: adminColors.red },
  dayAvailabilityOptionText: { flex: 1, color: adminColors.muted, fontFamily: 'InterMedium', fontSize: 14, lineHeight: 21 },
  activeDayAvailabilityOptionText: { color: adminColors.ink, fontFamily: 'InterSemiBold' },
  manageTimeSlotsHeader: { alignItems: 'center', flexDirection: 'row', flexWrap: 'wrap', gap: 12, justifyContent: 'space-between', marginTop: 28 },
  manageAddTimeButton: { alignItems: 'center', justifyContent: 'center', minHeight: 44, paddingHorizontal: 13, paddingVertical: 10, backgroundColor: adminColors.blueSoft, borderColor: adminColors.blueSoft, borderWidth: 1, borderRadius: 12 },
  disabledAddTimeButton: { opacity: 0.45 },
  manageAddTimeText: { color: adminColors.blue, fontFamily: 'InterSemiBold', fontSize: 13, lineHeight: 20 },
  manageSlotList: { gap: 10, marginTop: 14 },
  manageSlotCard: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', gap: 12, backgroundColor: adminColors.canvas, borderColor: adminColors.border, borderWidth: 1, borderRadius: 14, padding: 12 },
  manageSlotTime: { color: adminColors.ink, fontFamily: 'InterMedium', fontSize: 14, lineHeight: 21 },
  manageSlotCopy: { flex: 1, minWidth: 0, gap: 8 },
  manageSlotActions: { alignItems: 'center', alignSelf: 'flex-end', flexDirection: 'row', gap: 8 },
  manageSlotActionButton: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center', borderRadius: 12, backgroundColor: adminColors.surface, borderColor: adminColors.border, borderWidth: 1 },
  manageSlotDeleteButton: { backgroundColor: adminColors.redSoft, borderColor: adminColors.redSoft },
  manageSaveButton: { alignItems: 'center', justifyContent: 'center', minHeight: 50, paddingHorizontal: 18, paddingVertical: 13, backgroundColor: adminColors.blue, borderRadius: 14, marginTop: 24 },
  manageSaveText: { color: adminColors.surface, fontFamily: 'InterSemiBold', fontSize: 15, lineHeight: 22 },
  timeEntryOverlay: { position: 'absolute', top: 0, right: 0, bottom: 0, left: 0, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(23, 47, 80, 0.42)', paddingHorizontal: 18, zIndex: 20 },
  timeEntryCard: { backgroundColor: adminColors.surface, borderColor: adminColors.border, borderWidth: 1, borderRadius: 22, width: '100%', maxWidth: 480, maxHeight: '100%', overflow: 'hidden' },
  timeEntryScrollContent: { padding: 20 },
  timeEntryHeader: { alignItems: 'center', flexDirection: 'row', gap: 12, paddingBottom: 14, borderBottomWidth: 1, borderBottomColor: adminColors.border },
  timeEntryTitle: { flex: 1, minWidth: 0, color: adminColors.ink, fontFamily: 'InterBold', fontSize: 20, lineHeight: 28 },
  timeEntryCloseButton: { alignItems: 'center', justifyContent: 'center', height: 44, width: 44, backgroundColor: adminColors.canvas, borderRadius: 13 },
  timeEntryDate: { color: adminColors.muted, fontFamily: 'InterMedium', fontSize: 13, lineHeight: 20, marginTop: 14 },
  timeEntryFields: { gap: 18, marginTop: 22 },
  timeEntryField: { width: '100%' },
  formLabel: { color: adminColors.ink, fontFamily: 'InterSemiBold' },
  timeEntryLabel: { fontSize: 14, lineHeight: 21, marginBottom: 8 },
  calendarSlotInput: { minHeight: 52, paddingHorizontal: 14, paddingVertical: 13, backgroundColor: adminColors.canvas, borderColor: adminColors.border, borderWidth: 1, borderRadius: 13, color: adminColors.ink, fontFamily: 'Inter', fontSize: 16 },
  timeEntryActions: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginTop: 26 },
  timeEntryCancelButton: { alignItems: 'center', justifyContent: 'center', flex: 1, minWidth: 96, minHeight: 50, paddingHorizontal: 14, paddingVertical: 13, backgroundColor: adminColors.canvas, borderColor: adminColors.border, borderWidth: 1, borderRadius: 13 },
  timeEntryCancelText: { color: adminColors.ink, fontFamily: 'InterSemiBold', fontSize: 14, lineHeight: 21 },
  timeEntrySubmitButton: { alignItems: 'center', justifyContent: 'center', flex: 1, minWidth: 96, minHeight: 50, paddingHorizontal: 14, paddingVertical: 13, backgroundColor: adminColors.blue, borderRadius: 13 },
  timeEntrySubmitText: { color: adminColors.surface, fontFamily: 'InterSemiBold', fontSize: 14, lineHeight: 21 },
  deleteTimeSlotOverlay: { position: 'absolute', top: 0, right: 0, bottom: 0, left: 0, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(23, 47, 80, 0.42)', paddingHorizontal: 18, zIndex: 30 },
  deleteTimeSlotCard: { backgroundColor: adminColors.surface, borderColor: adminColors.border, borderWidth: 1, borderRadius: 22, width: '100%', maxWidth: 440, maxHeight: '100%', overflow: 'hidden' },
  noticeScrollContent: { alignItems: 'center', padding: 20 },
  deleteTimeSlotCloseButton: { alignItems: 'center', alignSelf: 'flex-end', justifyContent: 'center', height: 44, width: 44, borderRadius: 13, backgroundColor: adminColors.canvas, marginBottom: 12 },
  deleteTimeSlotTitle: { color: adminColors.ink, fontFamily: 'InterBold', fontSize: 20, lineHeight: 28, marginTop: 20, textAlign: 'center' },
  deleteTimeSlotMessage: { color: adminColors.muted, fontFamily: 'Inter', fontSize: 14, lineHeight: 22, marginTop: 10, textAlign: 'center', width: '100%' },
  deleteTimeSlotActions: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, width: '100%', marginTop: 24 },
  deleteTimeSlotCancelButton: { alignItems: 'center', justifyContent: 'center', flex: 1, minWidth: 96, minHeight: 50, paddingHorizontal: 14, paddingVertical: 13, backgroundColor: adminColors.canvas, borderColor: adminColors.border, borderWidth: 1, borderRadius: 13 },
  deleteTimeSlotCancelText: { color: adminColors.ink, fontFamily: 'InterSemiBold', fontSize: 14, lineHeight: 21 },
  deleteTimeSlotDeleteButton: { alignItems: 'center', justifyContent: 'center', flex: 1, minWidth: 96, minHeight: 50, paddingHorizontal: 14, paddingVertical: 13, backgroundColor: adminColors.red, borderRadius: 13 },
  deleteTimeSlotDeleteText: { color: adminColors.surface, fontFamily: 'InterSemiBold', fontSize: 14, lineHeight: 21 },
  timeSlotNoticeOkButton: { alignItems: 'center', justifyContent: 'center', flex: 1, minHeight: 50, paddingHorizontal: 14, paddingVertical: 13, backgroundColor: adminColors.blue, borderRadius: 13 },
  timeSlotNoticeOkText: { color: adminColors.surface, fontFamily: 'InterSemiBold', fontSize: 14, lineHeight: 21 },
});
