import { StyleSheet } from 'react-native';

export const authRouteStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#021526',
  },
  keyboardAvoidingView: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
  },
  logo: {
    position: 'absolute',
  },
  wordmark: {
    position: 'absolute',
    color: '#FFFFFF',
    fontFamily: 'Jomhuria',
    includeFontPadding: false,
  },
  wordmarkAccent: {
    color: '#70A2E3',
  },
  tagline: {
    position: 'absolute',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  taglineText: {
    color: '#FFFFFF',
    fontFamily: 'JosefinSlabBold',
    includeFontPadding: false,
  },
  dot: {
    backgroundColor: '#FFFFFF',
  },
  panel: {
    position: 'absolute',
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderColor: '#FFFFFF',
    borderWidth: 1,
  },
  label: {
    position: 'absolute',
    color: '#FFFFFF',
    fontFamily: 'Inter',
    includeFontPadding: false,
  },
  input: {
    position: 'absolute',
    backgroundColor: 'rgba(255, 255, 255, 0.24)',
    borderColor: 'rgba(255, 255, 255, 0.82)',
    borderWidth: 1,
    boxShadow: '0px 4px 4px rgba(0, 0, 0, 0.25)',
    color: '#FFFFFF',
    fontFamily: 'Inter',
    elevation: 4,
  },
  actionButton: {
    position: 'absolute',
    alignItems: 'center',
    backgroundColor: 'transparent',
    borderColor: '#FFFFFF',
    borderWidth: 1,
    justifyContent: 'center',
  },
  actionButtonText: {
    color: '#FFFFFF',
    fontFamily: 'Inter',
    fontWeight: '500',
    includeFontPadding: false,
  },
  footerButton: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
  },
  footerButtonText: {
    color: '#FFFFFF',
    fontFamily: 'Inter',
    includeFontPadding: false,
  },
  forgotPasswordButton: {
    position: 'absolute',
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  forgotPasswordText: {
    color: '#FFFFFF',
    fontFamily: 'Inter',
    includeFontPadding: false,
    textDecorationLine: 'underline',
  },
  authMessageText: {
    position: 'absolute',
    backgroundColor: 'rgba(255, 255, 255, 0.92)',
    borderRadius: 8,
    color: '#142C4C',
    fontFamily: 'Inter',
    includeFontPadding: false,
    opacity: 0.95,
    paddingHorizontal: 8,
    paddingVertical: 6,
    textAlign: 'center',
  },
  privacyAgreementButton: {
    position: 'absolute',
    alignItems: 'center',
    flexDirection: 'row',
  },
  privacyAgreementText: {
    color: '#FFFFFF',
    fontFamily: 'Inter',
    includeFontPadding: false,
  },
  privacyCheckbox: {
    alignItems: 'center',
    borderColor: '#FFFFFF',
    borderWidth: 1.4,
    justifyContent: 'center',
  },
  privacyCheckboxChecked: {
    backgroundColor: '#FFFFFF',
  },
  modalBackdrop: {
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.68)',
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  forgotModalCard: {
    width: '100%',
    maxWidth: 340,
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    paddingHorizontal: 22,
    paddingVertical: 24,
  },
  forgotModalTitle: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 24,
    includeFontPadding: false,
    lineHeight: 32,
    textAlign: 'center',
  },
  forgotModalCopy: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 14,
    includeFontPadding: false,
    lineHeight: 20,
    marginTop: 12,
    textAlign: 'center',
  },
  forgotModalInput: {
    backgroundColor: '#F3EEEE',
    borderColor: '#D8E0EC',
    borderRadius: 12,
    borderWidth: 1,
    color: '#142C4C',
    fontFamily: 'Inter',
    fontSize: 16,
    height: 48,
    marginTop: 20,
    paddingHorizontal: 14,
  },
  forgotModalActions: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 20,
  },
  forgotModalCancelButton: {
    alignItems: 'center',
    backgroundColor: '#DCE4F3',
    borderRadius: 12,
    flex: 1,
    height: 48,
    justifyContent: 'center',
  },
  forgotModalSendButton: {
    alignItems: 'center',
    backgroundColor: '#142C4C',
    borderRadius: 12,
    flex: 1,
    height: 48,
    justifyContent: 'center',
  },
  forgotModalCancelText: {
    color: '#142C4C',
    fontFamily: 'Inter',
    fontSize: 16,
    includeFontPadding: false,
    lineHeight: 22,
  },
  forgotModalSendText: {
    color: '#FFFFFF',
    fontFamily: 'InterBold',
    fontSize: 16,
    includeFontPadding: false,
    lineHeight: 22,
  },
});
