import { StyleSheet } from 'react-native';
import { authColors as colors } from '@/styles/auth-theme';

export const authRouteStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.canvas },
  keyboardAvoidingView: { flex: 1 },
  scrollContent: { flexGrow: 1 },
  header: { overflow: 'hidden' },
  scrim: { ...StyleSheet.absoluteFill, backgroundColor: 'rgba(7, 20, 35, 0.4)' },
  headerContent: { width: '100%', maxWidth: 480, alignSelf: 'center', paddingHorizontal: 24,
    paddingBottom: 52, gap: 18 },
  backButton: { minHeight: 44, alignSelf: 'flex-start', flexDirection: 'row', alignItems: 'center', gap: 8, paddingRight: 12 },
  backText: { color: '#DAE6F6', fontFamily: 'InterMedium', fontSize: 13, lineHeight: 20 },
  brandRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  brandLogo: { width: 64, height: 52 },
  brandCopy: { flex: 1, minWidth: 0 },
  introBrand: { flexDirection: 'column', alignItems: 'center', gap: 14 },
  introLogo: { width: 148, height: 116 },
  introBrandCopy: { flex: 0, width: '100%', alignItems: 'center' },
  introWordmark: { fontSize: 80, lineHeight: 76, textAlign: 'center' },
  wordmark: { color: colors.ink, fontFamily: 'Jomhuria', fontSize: 52, lineHeight: 52, includeFontPadding: false },
  wordmarkAccent: { color: colors.link },
  tagline: { color: '#DAE6F6', fontFamily: 'InterMedium', fontSize: 10, lineHeight: 16, letterSpacing: 1.2 },
  body: { width: '100%', maxWidth: 480, alignSelf: 'center', paddingHorizontal: 20, gap: 8 },
  panel: { marginTop: -28, backgroundColor: colors.surface, borderRadius: 24,
    borderWidth: 1, borderColor: colors.border, padding: 22, gap: 18, boxShadow: '0px 12px 32px rgba(3, 14, 26, 0.24)' },
  formTitle: { color: colors.ink, fontFamily: 'InterSemiBold', fontSize: 21, lineHeight: 30,
    textAlign: 'center', marginBottom: 4 },
  field: { gap: 7 },
  label: { color: colors.ink, fontFamily: 'InterSemiBold', fontSize: 13, lineHeight: 20 },
  inputRow: { minHeight: 54, backgroundColor: colors.field, borderWidth: 1,
    borderColor: colors.controlBorder, borderRadius: 14, flexDirection: 'row', alignItems: 'center' },
  inputFocused: { borderColor: colors.link, backgroundColor: '#172E45' },
  input: { flex: 1, minWidth: 0, minHeight: 52, paddingHorizontal: 14, paddingVertical: 14,
    color: colors.ink, fontFamily: 'Inter', fontSize: 15, lineHeight: 22, outlineColor: colors.link },
  passwordToggle: { minWidth: 44, minHeight: 48, alignItems: 'center', justifyContent: 'center', marginRight: 4 },
  actionButton: { minHeight: 54, paddingHorizontal: 16, paddingVertical: 15,
    backgroundColor: colors.blue, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  actionButtonText: { color: colors.actionInk, fontFamily: 'InterSemiBold', fontSize: 16, lineHeight: 24, textAlign: 'center' },
  disabled: { opacity: 0.65 },
  googleButton: { minHeight: 54,
    alignItems: 'center', justifyContent: 'center' },
  googleButtonImage: { width: 177, height: 40 },
  footerButton: { minHeight: 48, paddingHorizontal: 12, paddingVertical: 14, justifyContent: 'center' },
  footerText: { color: colors.muted, fontFamily: 'Inter', fontSize: 14, lineHeight: 22, textAlign: 'center' },
  linkText: { color: colors.link, fontFamily: 'InterSemiBold' },
  forgotPasswordButton: { minHeight: 44, alignSelf: 'flex-end', justifyContent: 'center', marginTop: -6 },
  forgotPasswordText: { color: colors.link, fontFamily: 'InterMedium', fontSize: 13, lineHeight: 20 },
  authMessageText: { color: colors.ink, fontFamily: 'Inter', fontSize: 14, lineHeight: 22,
    backgroundColor: colors.message, borderRadius: 12, padding: 12 },
  privacyAgreementButton: { minHeight: 44, flexDirection: 'row', alignItems: 'center', gap: 10 },
  privacyAgreementText: { flex: 1, color: colors.muted, fontFamily: 'Inter', fontSize: 12, lineHeight: 19 },
  privacyCheckbox: { width: 24, height: 24, borderRadius: 7, borderWidth: 1.5,
    borderColor: colors.controlBorder, alignItems: 'center', justifyContent: 'center' },
  privacyCheckboxChecked: { backgroundColor: colors.blue, borderColor: colors.blue },
  modalBackdrop: { flex: 1, backgroundColor: 'rgba(9, 24, 43, 0.65)', alignItems: 'center',
    justifyContent: 'center', paddingHorizontal: 20, paddingVertical: 24 },
  forgotModalCard: { width: '100%', maxWidth: 400, maxHeight: '90%', backgroundColor: colors.surface,
    borderWidth: 1, borderColor: colors.border, borderRadius: 24 },
  forgotModalContent: { padding: 24 },
  forgotModalTitle: { color: colors.ink, fontFamily: 'Jomolhari', fontSize: 24, lineHeight: 34 },
  forgotModalCopy: { color: colors.muted, fontFamily: 'Inter', fontSize: 14, lineHeight: 22, marginTop: 10 },
  forgotModalInput: { backgroundColor: colors.field, borderColor: colors.controlBorder, borderWidth: 1,
    borderRadius: 14, color: colors.ink, fontFamily: 'Inter', fontSize: 15,
    minHeight: 54, paddingVertical: 14, paddingHorizontal: 14, marginTop: 20, outlineColor: colors.link },
  forgotModalActions: { flexDirection: 'row', gap: 10, marginTop: 20 },
  forgotModalCancelButton: { flex: 1, minHeight: 50, paddingVertical: 14, paddingHorizontal: 8,
    backgroundColor: colors.field, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  forgotModalSendButton: { flex: 1, minHeight: 50, paddingVertical: 14, paddingHorizontal: 8,
    backgroundColor: colors.blue, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  forgotModalCancelText: { color: colors.ink, fontFamily: 'InterMedium', fontSize: 15, lineHeight: 22 },
  forgotModalSendText: { color: colors.actionInk, fontFamily: 'InterSemiBold', fontSize: 15, lineHeight: 22 },
});
