import { StyleSheet } from 'react-native';

import { clientUi } from '@/styles/client-ui.styles';

export const bookingEmptyStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F3EEEE',
    overflow: 'hidden',
  },
  canvas: {
    position: 'relative',
    backgroundColor: '#F3EEEE',
  },
  backgroundImage: {
    position: 'absolute',
    top: 0,
    opacity: 0.6,
  },
  backButton: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
  },
  brandTitle: {
    position: 'absolute',
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    includeFontPadding: false,
    textAlign: 'center',
  },
  logo: {
    position: 'absolute',
  },
  collage: {
    position: 'absolute',
  },
  title: {
    position: 'absolute',
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    includeFontPadding: false,
    textAlign: 'center',
  },
  subtitle: {
    position: 'absolute',
    color: '#142C4C',
    fontFamily: 'Inter',
    includeFontPadding: false,
    textAlign: 'center',
  },
  browseButton: {
    position: 'absolute',
    alignItems: 'center',
    backgroundColor: clientUi.colors.ink,
    borderColor: clientUi.colors.warmAccent,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.16,
    shadowRadius: 10,
    elevation: 3,
  },
  browseText: {
    color: '#ffffff',
    fontFamily: 'InterSemiBold',
    includeFontPadding: false,
  },
  dividerLine: {
    position: 'absolute',
    backgroundColor: '#8AA3C3',
  },
  dividerCameraWrap: {
    position: 'absolute',
    alignItems: 'center',
    backgroundColor: '#F3EEEE',
    justifyContent: 'center',
  },
  statusCard: {
    position: 'absolute',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: 'rgba(76, 94, 118, 0.16)',
    borderWidth: 1,
    paddingHorizontal: 18,
    paddingVertical: 18,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.14,
    shadowRadius: 8,
    elevation: 4,
  },
  statusIconWrap: {
    alignItems: 'center',
    backgroundColor: '#F3EEEE',
    justifyContent: 'center',
    marginBottom: 15,
  },
  statusTitle: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    includeFontPadding: false,
    textAlign: 'center',
  },
  statusMessage: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    includeFontPadding: false,
    marginTop: 7,
    textAlign: 'center',
  },
  bookingSummaryBox: {
    alignSelf: 'stretch',
    backgroundColor: '#F6FAFF',
    borderColor: 'rgba(76, 94, 118, 0.12)',
    borderRadius: 12,
    borderWidth: 1,
    marginTop: 16,
    padding: 12,
  },
  bookingActionRow: {
    alignSelf: 'stretch',
    gap: 10,
    marginTop: 14,
  },
  cancelBookingButton: {
    alignItems: 'center',
    borderColor: '#E45F62',
    borderRadius: 999,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 42,
  },
  cancelBookingText: {
    color: '#E45F62',
    fontFamily: 'InterBold',
    fontSize: 13,
    includeFontPadding: false,
    lineHeight: 18,
  },
  bookAgainButton: {
    alignItems: 'center',
    backgroundColor: '#142C4C',
    borderRadius: 999,
    justifyContent: 'center',
    minHeight: 42,
  },
  bookAgainText: {
    color: '#ffffff',
    fontFamily: 'InterBold',
    fontSize: 13,
    includeFontPadding: false,
    lineHeight: 18,
  },
  confirmedHelpText: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 11,
    includeFontPadding: false,
    lineHeight: 16,
    textAlign: 'center',
  },
  clientRejectionReasonBox: {
    alignSelf: 'stretch',
    backgroundColor: '#FFF6F6',
    borderColor: 'rgba(228, 95, 98, 0.18)',
    borderRadius: 12,
    borderWidth: 1,
    marginTop: 14,
    padding: 12,
  },
  clientRejectionReasonLabel: {
    color: '#E45F62',
    fontFamily: 'InterBold',
    fontSize: 12,
    includeFontPadding: false,
    lineHeight: 16,
  },
  clientRejectionReasonText: {
    color: '#142C4C',
    fontFamily: 'Inter',
    fontSize: 12,
    includeFontPadding: false,
    lineHeight: 17,
    marginTop: 4,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    paddingVertical: 5,
  },
  summaryLabel: {
    color: '#4C5E76',
    fontFamily: 'InterBold',
    fontSize: 12,
    includeFontPadding: false,
    lineHeight: 17,
  },
  summaryValue: {
    color: '#142C4C',
    flex: 1,
    fontFamily: 'Inter',
    fontSize: 12,
    includeFontPadding: false,
    lineHeight: 17,
    textAlign: 'right',
  },
  historyPanel: {
    position: 'absolute',
    backgroundColor: '#ffffff',
    borderColor: 'rgba(76, 94, 118, 0.16)',
    borderWidth: 1,
    paddingHorizontal: 16,
    paddingVertical: 14,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 3,
  },
  historyHeader: {
    borderBottomColor: 'rgba(138, 163, 195, 0.32)',
    borderBottomWidth: 1,
    paddingBottom: 10,
  },
  historyTitle: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    includeFontPadding: false,
  },
  historySubtitle: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    includeFontPadding: false,
    marginTop: 3,
  },
  historyList: {
    gap: 10,
    paddingTop: 12,
    paddingBottom: 4,
  },
  historyCard: {
    backgroundColor: '#F6FAFF',
    borderColor: 'rgba(76, 94, 118, 0.12)',
    borderRadius: 12,
    borderWidth: 1,
    padding: 11,
  },
  historyTopRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
  },
  historyPackage: {
    color: '#142C4C',
    flex: 1,
    fontFamily: 'InterBold',
    fontSize: 12,
    includeFontPadding: false,
    lineHeight: 17,
  },
  historyStatusPill: {
    borderRadius: 999,
    paddingHorizontal: 9,
    paddingVertical: 4,
  },
  historyPendingPill: {
    backgroundColor: '#FFEBCF',
  },
  historyConfirmedPill: {
    backgroundColor: '#DDF4EC',
  },
  historyRejectedPill: {
    backgroundColor: '#FFE3E4',
  },
  historyStatusText: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 10,
    includeFontPadding: false,
    lineHeight: 12,
  },
  historyMeta: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 11,
    includeFontPadding: false,
    lineHeight: 16,
    marginTop: 7,
  },
  historyPrice: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 12,
    includeFontPadding: false,
    lineHeight: 17,
    marginTop: 4,
  },
  bookingHeader: {
    position: 'absolute',
    backgroundColor: clientUi.colors.navBlue,
    left: 0,
    overflow: 'hidden',
    top: 0,
  },
  bookingHeaderTexture: {
    height: '220%',
    opacity: 0.58,
    position: 'absolute',
    right: 0,
    top: '-62%',
    width: '190%',
  },
  bookingHeaderTitle: {
    position: 'absolute',
    color: '#ffffff',
    fontFamily: 'Jomolhari',
    includeFontPadding: false,
    textAlign: 'center',
  },
  bookingBackButton: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bookingBodyShell: {
    position: 'absolute',
    backgroundColor: '#ffffff',
    overflow: 'hidden',
  },
  bookingBodyBackground: {
    height: '116%',
    left: 0,
    opacity: 0.7,
    position: 'absolute',
    top: 0,
    width: '100%',
  },
  bookingListScroll: {
    position: 'absolute',
  },
  detailScrollView: {
    flexGrow: 0,
  },
  bookingFilterRow: {
    position: 'absolute',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  bookingFilterPill: {
    alignItems: 'center',
    backgroundColor: '#E6F1FD',
    borderColor: '#4C5E76',
    borderWidth: 0.5,
    justifyContent: 'center',
  },
  activeBookingFilterPill: {
    backgroundColor: '#142C4C',
    borderColor: '#142C4C',
  },
  bookingFilterText: {
    color: '#142C4C',
    fontFamily: 'Inter',
    fontSize: 15,
    includeFontPadding: false,
    lineHeight: 18,
  },
  activeBookingFilterText: {
    color: '#ffffff',
  },
  bookingListCard: {
    position: 'absolute',
    backgroundColor: '#ffffff',
    borderColor: 'rgba(20, 44, 76, 0.08)',
    borderWidth: 1,
    overflow: 'hidden',
    shadowColor: '#142C4C',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 2,
  },
  bookingListAccentRail: {
    backgroundColor: clientUi.colors.warmAccent,
    borderBottomRightRadius: 999,
    borderTopRightRadius: 999,
    position: 'absolute',
  },
  bookingListImage: {
    position: 'absolute',
  },
  bookingStatusPill: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bookingStatusText: {
    fontFamily: 'InterBold',
    fontSize: 11,
    includeFontPadding: false,
    lineHeight: 13,
  },
  bookingListTitle: {
    position: 'absolute',
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    includeFontPadding: false,
  },
  bookingListMetaRow: {
    position: 'absolute',
    alignItems: 'center',
    flexDirection: 'row',
    gap: 4,
  },
  bookingListMetaText: {
    color: '#515354',
    fontFamily: 'Inter',
    includeFontPadding: false,
  },
  bookingChevron: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bookingEmptyPanel: {
    position: 'absolute',
    backgroundColor: '#ffffff',
    borderColor: 'rgba(200, 138, 85, 0.28)',
    borderWidth: 1,
    overflow: 'hidden',
    padding: 22,
    paddingTop: 116,
    shadowColor: '#142C4C',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.1,
    shadowRadius: 14,
    elevation: 2,
  },
  bookingEmptyImage: {
    height: 92,
    left: 0,
    opacity: 0.9,
    position: 'absolute',
    right: 0,
    top: 0,
    width: '100%',
  },
  bookingEmptyAccentLine: {
    backgroundColor: clientUi.colors.warmAccent,
    borderRadius: 999,
    height: 4,
    marginBottom: 14,
    width: 54,
  },
  bookingEmptyTitle: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 24,
    includeFontPadding: false,
    lineHeight: 34,
  },
  bookingEmptyText: {
    color: '#515354',
    fontFamily: 'Inter',
    fontSize: 13,
    includeFontPadding: false,
    lineHeight: 18,
    marginTop: 8,
  },
  bookingSkeletonImage: {
    position: 'absolute',
    backgroundColor: '#D9D1CC',
  },
  bookingSkeletonLine: {
    position: 'absolute',
    backgroundColor: '#E9E1DC',
  },
  bookingSkeletonLineStrong: {
    position: 'absolute',
    backgroundColor: '#D8E3F2',
  },
  bookingSkeletonAccentRail: {
    backgroundColor: clientUi.colors.warmAccentSoft,
    borderBottomRightRadius: 999,
    borderTopRightRadius: 999,
    position: 'absolute',
  },
  detailHeroImage: {
    position: 'absolute',
  },
  detailHeroScrim: {
    backgroundColor: 'rgba(8, 18, 31, 0.24)',
    position: 'absolute',
  },
  detailHeroLabel: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.92)',
    borderColor: 'rgba(200, 138, 85, 0.5)',
    borderWidth: 1,
    justifyContent: 'center',
    position: 'absolute',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.14,
    shadowRadius: 6,
    elevation: 2,
  },
  detailHeroLabelText: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    includeFontPadding: false,
  },
  bookingDetailBodyShell: {
    position: 'absolute',
    backgroundColor: '#ffffff',
    overflow: 'hidden',
  },
  detailInfoCard: {
    position: 'absolute',
    backgroundColor: '#ffffff',
    borderColor: 'rgba(20, 44, 76, 0.08)',
    borderWidth: 1,
    overflow: 'hidden',
    paddingHorizontal: 24,
    paddingTop: 23,
    paddingBottom: 26,
    shadowColor: '#142C4C',
    shadowOffset: { width: 0, height: 7 },
    shadowOpacity: 0.12,
    shadowRadius: 15,
    elevation: 3,
  },
  detailCardAccent: {
    backgroundColor: clientUi.colors.warmAccent,
    height: 6,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  detailStatusPill: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    borderRadius: 10,
    height: 24,
    justifyContent: 'center',
    minWidth: 92,
    paddingHorizontal: 14,
  },
  detailStatusText: {
    fontFamily: 'InterBold',
    fontSize: 11,
    includeFontPadding: false,
    lineHeight: 13,
  },
  detailPackageTitle: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    includeFontPadding: false,
    marginTop: 12,
  },
  detailServiceName: {
    color: '#515354',
    fontFamily: 'Inter',
    fontSize: 13,
    includeFontPadding: false,
    lineHeight: 18,
    marginBottom: 18,
    marginTop: 3,
  },
  detailInfoRow: {
    alignItems: 'center',
    alignSelf: 'stretch',
    backgroundColor: 'rgba(206, 221, 239, 0.47)',
    borderRadius: 10,
    flexDirection: 'row',
    height: 44,
    marginTop: 11,
    paddingHorizontal: 20,
  },
  detailInfoLabel: {
    color: '#515354',
    fontFamily: 'Inter',
    fontSize: 15,
    includeFontPadding: false,
    lineHeight: 20,
    marginLeft: 10,
    width: 65,
  },
  detailInfoValue: {
    color: '#515354',
    flex: 1,
    fontFamily: 'Inter',
    fontSize: 15,
    includeFontPadding: false,
    lineHeight: 20,
  },
  detailStatusPanel: {
    position: 'absolute',
    alignItems: 'flex-start',
    flexDirection: 'row',
    minHeight: 105,
    paddingHorizontal: 23,
    paddingVertical: 20,
  },
  detailStatusCopy: {
    flex: 1,
    marginLeft: 14,
  },
  detailStatusTitle: {
    fontFamily: 'InterBold',
    fontSize: 16,
    includeFontPadding: false,
    lineHeight: 22,
  },
  detailStatusMessage: {
    color: '#2C2C2C',
    fontFamily: 'Inter',
    fontSize: 13,
    includeFontPadding: false,
    lineHeight: 17,
    marginTop: 4,
  },
  detailReasonText: {
    color: '#2C2C2C',
    fontFamily: 'InterBold',
    fontSize: 12,
    includeFontPadding: false,
    lineHeight: 16,
    marginTop: 6,
  },
  detailPrimaryButton: {
    position: 'absolute',
    alignItems: 'center',
    backgroundColor: clientUi.colors.ink,
    flexDirection: 'row',
    justifyContent: 'center',
  },
  detailPrimaryButtonText: {
    color: '#ffffff',
    fontFamily: 'InterSemiBold',
    includeFontPadding: false,
    marginLeft: 10,
  },
  cancelDrawerOverlay: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  cancelDrawerScrim: {
    ...StyleSheet.absoluteFill,
    backgroundColor: 'rgba(20, 44, 76, 0.5)',
  },
  cancelDrawer: {
    alignSelf: 'center',
    backgroundColor: '#ffffff',
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    maxHeight: '95%',
    paddingHorizontal: 24,
    paddingTop: 21,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.18,
    shadowRadius: 10,
    elevation: 8,
  },
  cancelDrawerHandle: {
    alignSelf: 'center',
    backgroundColor: '#BFBFBF',
    borderRadius: 999,
    height: 5,
    marginBottom: 34,
    width: 113,
  },
  cancelDrawerIconWrap: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: '#D8E6F7',
    borderRadius: 56,
    height: 112,
    justifyContent: 'center',
    marginBottom: 13,
    width: 112,
  },
  cancelDrawerTitle: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 25,
    includeFontPadding: false,
    lineHeight: 34,
    textAlign: 'center',
  },
  cancelDrawerText: {
    color: '#2C2C2C',
    fontFamily: 'Inter',
    fontSize: 15,
    includeFontPadding: false,
    lineHeight: 20,
    marginTop: 4,
    textAlign: 'center',
    paddingHorizontal: 10,
  },
  cancelDrawerActions: {
    gap: 18,
    marginTop: 21,
  },
  keepBookingButton: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: '#142C4C',
    borderRadius: 8,
    borderWidth: 1,
    minHeight: 63,
    paddingVertical: 12,
    justifyContent: 'center',
  },
  keepBookingText: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 25,
    includeFontPadding: false,
    lineHeight: 34,
  },
  confirmCancelButton: {
    alignItems: 'center',
    backgroundColor: '#142C4C',
    borderRadius: 8,
    minHeight: 63,
    paddingVertical: 12,
    justifyContent: 'center',
  },
  confirmCancelText: {
    color: '#ffffff',
    fontFamily: 'Jomolhari',
    fontSize: 25,
    includeFontPadding: false,
    lineHeight: 34,
  },
});
