import { StyleSheet } from 'react-native';

export const clientNotificationsStyles = StyleSheet.create({
  container: {
    backgroundColor: '#F3EEEE',
    flex: 1,
  },
  content: {
    paddingHorizontal: 20,
    paddingTop: 58,
  },
  topBar: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 24,
  },
  iconButton: {
    alignItems: 'center',
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  brandRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  brandText: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 24,
    includeFontPadding: false,
    lineHeight: 35,
  },
  title: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 32,
    includeFontPadding: false,
    lineHeight: 42,
  },
  subtitle: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 14,
    includeFontPadding: false,
    lineHeight: 20,
    marginBottom: 18,
    marginTop: 2,
  },
  list: {
    gap: 10,
  },
  card: {
    backgroundColor: '#ffffff',
    borderColor: 'rgba(76, 94, 118, 0.13)',
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: 'row',
    minHeight: 82,
    padding: 13,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 2,
  },
  iconWrap: {
    alignItems: 'center',
    backgroundColor: '#EAF2FA',
    borderRadius: 12,
    height: 44,
    justifyContent: 'center',
    marginRight: 12,
    width: 44,
  },
  copy: {
    flex: 1,
    minWidth: 0,
  },
  cardTitle: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 15,
    includeFontPadding: false,
    lineHeight: 20,
  },
  message: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 13,
    includeFontPadding: false,
    lineHeight: 18,
    marginTop: 3,
  },
  meta: {
    color: '#8AA3C3',
    fontFamily: 'InterBold',
    fontSize: 11,
    includeFontPadding: false,
    lineHeight: 15,
    marginTop: 7,
  },
  unreadDot: {
    backgroundColor: '#ED2314',
    borderRadius: 5,
    height: 10,
    marginLeft: 8,
    marginTop: 5,
    width: 10,
  },
  emptyPanel: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: 'rgba(76, 94, 118, 0.13)',
    borderRadius: 16,
    borderWidth: 1,
    padding: 22,
  },
  emptyTitle: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 16,
    includeFontPadding: false,
    lineHeight: 22,
    marginTop: 12,
  },
  emptyText: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 13,
    includeFontPadding: false,
    lineHeight: 18,
    marginTop: 5,
    textAlign: 'center',
  },
});
