import { StyleSheet } from 'react-native';

import { clientUi } from '@/styles/client-ui.styles';

const { ink, muted, background } = clientUi.colors;

export const clientProfileStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: ink },
  header: { backgroundColor: ink },
  headerRow: {
    width: '100%',
    maxWidth: 720,
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 20,
    paddingVertical: 16,
  },
  headerTitle: {
    flex: 1,
    minWidth: 0,
    color: '#FFFFFF',
    fontFamily: 'Jomolhari',
    fontSize: 28,
    lineHeight: 40,
    textAlign: 'center',
  },
  backButton: {
    width: 44,
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  scroll: { flex: 1, backgroundColor: background },
  content: {
    width: '100%',
    maxWidth: 720,
    alignSelf: 'center',
    padding: 20,
    gap: 18,
  },
  identityCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    borderWidth: 1,
    borderColor: '#E1E5EA',
    padding: 24,
    gap: 10,
    alignItems: 'center',
  },
  avatar: {
    width: 96,
    height: 96,
    borderRadius: 48,
    borderWidth: 4,
    borderColor: '#FFFFFF',
    backgroundColor: '#DDE8F3',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: ink,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 2,
  },
  avatarImage: { width: 88, height: 88, borderRadius: 44 },
  roleBadge: {
    backgroundColor: '#EDF3F8',
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 5,
    maxWidth: '100%',
  },
  roleText: {
    color: muted,
    fontFamily: 'InterMedium',
    fontSize: 11,
    lineHeight: 17,
    textAlign: 'center',
  },
  name: {
    color: ink,
    fontFamily: 'Jomolhari',
    fontSize: 24,
    lineHeight: 34,
    textAlign: 'center',
    maxWidth: '100%',
  },
  email: {
    color: muted,
    fontFamily: 'Inter',
    fontSize: 14,
    lineHeight: 22,
    textAlign: 'center',
    maxWidth: '100%',
  },
  editButton: {
    alignSelf: 'stretch',
    marginTop: 6,
    backgroundColor: ink,
    borderRadius: 14,
    minHeight: 48,
    paddingHorizontal: 16,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  buttonText: {
    color: '#FFFFFF',
    fontFamily: 'InterSemiBold',
    fontSize: 15,
    lineHeight: 23,
    textAlign: 'center',
    flexShrink: 1,
  },
  section: { gap: 10 },
  sectionTitle: {
    color: ink,
    fontFamily: 'InterSemiBold',
    fontSize: 16,
    lineHeight: 24,
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E1E5EA',
    borderRadius: 20,
    paddingHorizontal: 18,
  },
  accountRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    paddingVertical: 16,
  },
  divider: { borderBottomWidth: 1, borderBottomColor: '#EDF0F4' },
  iconTile: {
    backgroundColor: '#EDF3F8',
    width: 38,
    height: 38,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  copy: { flex: 1, minWidth: 0, gap: 4 },
  label: { color: muted, fontFamily: 'Inter', fontSize: 12, lineHeight: 18 },
  value: {
    color: ink,
    fontFamily: 'InterMedium',
    fontSize: 14,
    lineHeight: 22,
  },
  menuRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 16,
  },
  menuTitle: {
    color: ink,
    fontFamily: 'InterSemiBold',
    fontSize: 15,
    lineHeight: 23,
  },
  helper: { color: muted, fontFamily: 'Inter', fontSize: 13, lineHeight: 20 },
  featureCard: { backgroundColor: ink, borderRadius: 20, overflow: 'hidden' },
  featureImage: { ...StyleSheet.absoluteFill },
  featureOverlay: {
    ...StyleSheet.absoluteFill,
    backgroundColor: 'rgba(10,25,43,0.72)',
  },
  featureCopy: { padding: 22, gap: 10 },
  featureEyebrow: {
    color: '#F4DDC8',
    fontFamily: 'InterSemiBold',
    fontSize: 11,
    lineHeight: 18,
    letterSpacing: 1,
  },
  featureTitle: {
    color: '#FFFFFF',
    fontFamily: 'Jomolhari',
    fontSize: 22,
    lineHeight: 32,
  },
  featureLink: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 6,
  },
  featureLinkText: {
    color: '#FFFFFF',
    fontFamily: 'InterSemiBold',
    fontSize: 14,
    lineHeight: 22,
  },
  logoutButton: {
    borderColor: '#E8D4CF',
    borderWidth: 1,
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    minHeight: 52,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  logoutText: {
    color: '#963E37',
    fontFamily: 'InterSemiBold',
    fontSize: 15,
    lineHeight: 23,
  },
  photoCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#E1E5EA',
    padding: 20,
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 18,
  },
  photoCopy: { flexGrow: 1, flexBasis: 140, minWidth: 0, gap: 8 },
  photoButton: {
    alignSelf: 'flex-start',
    minHeight: 44,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: '#EDF3F8',
    justifyContent: 'center',
  },
  photoButtonText: {
    color: ink,
    fontFamily: 'InterSemiBold',
    fontSize: 13,
    lineHeight: 20,
  },
  cameraBadge: {
    position: 'absolute',
    bottom: -2,
    right: -2,
    backgroundColor: ink,
    borderRadius: 16,
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  formCard: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E1E5EA',
    borderRadius: 20,
    padding: 20,
    gap: 18,
  },
  sectionHeading: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  field: { gap: 7 },
  fieldLabel: {
    color: ink,
    fontFamily: 'InterMedium',
    fontSize: 14,
    lineHeight: 22,
  },
  requiredMark: { color: '#963E37' },
  inputShell: {
    backgroundColor: '#FAFBFD',
    borderColor: '#CCD6E2',
    borderWidth: 1,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
  },
  focusedInput: { borderColor: '#3D83AC', backgroundColor: '#FFFFFF' },
  disabledInput: { backgroundColor: '#EDF1F5', borderColor: '#E1E5EA' },
  input: {
    flex: 1,
    minWidth: 0,
    minHeight: 52,
    paddingHorizontal: 14,
    paddingVertical: 14,
    color: ink,
    fontFamily: 'Inter',
    fontSize: 16,
  },
  inputAccessory: {
    width: 44,
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  optionalBadge: {
    alignSelf: 'flex-start',
    backgroundColor: '#EDF3F8',
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  actions: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
  saveButton: {
    backgroundColor: ink,
    borderRadius: 14,
    flexGrow: 2,
    flexBasis: 150,
    minHeight: 52,
    paddingHorizontal: 16,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelButton: {
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    borderColor: '#CCD6E2',
    borderWidth: 1,
    flexGrow: 1,
    flexBasis: 100,
    minHeight: 52,
    paddingHorizontal: 16,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelText: {
    color: ink,
    fontFamily: 'InterSemiBold',
    fontSize: 15,
    lineHeight: 23,
    textAlign: 'center',
  },
  skeleton: {
    height: 18,
    borderRadius: 6,
    backgroundColor: '#E5EBF2',
    width: '75%',
  },
  pressed: { opacity: 0.76 },
  disabled: { opacity: 0.5 },
});
