import { StyleSheet } from 'react-native';

import { clientUi } from '@/styles/client-ui.styles';

const { ink, muted, warmAccent } = clientUi.colors;

export const clientBookingsStyles = StyleSheet.create({
  intro: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    paddingVertical: 4,
  },
  introIcon: {
    width: 52,
    height: 52,
    borderRadius: 18,
    backgroundColor: '#E1EBF4',
    alignItems: 'center',
    justifyContent: 'center',
  },
  copy: { flex: 1, minWidth: 0, gap: 5 },
  heading: {
    color: ink,
    fontFamily: 'Jomolhari',
    fontSize: 22,
    lineHeight: 32,
  },
  subtitle: { color: muted, fontFamily: 'Inter', fontSize: 13, lineHeight: 20 },
  filters: { gap: 8, paddingVertical: 4 },
  filter: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    minHeight: 44,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 24,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D9DFE6',
  },
  activeFilter: { backgroundColor: ink, borderColor: ink },
  filterText: {
    color: muted,
    fontFamily: 'InterMedium',
    fontSize: 13,
    lineHeight: 20,
  },
  activeFilterText: { color: '#FFFFFF' },
  filterCount: {
    color: ink,
    fontFamily: 'InterSemiBold',
    fontSize: 12,
    lineHeight: 18,
    paddingHorizontal: 6,
    paddingVertical: 1,
    borderRadius: 8,
    backgroundColor: '#EDF2F7',
    overflow: 'hidden',
  },
  activeFilterCount: { color: '#FFFFFF', backgroundColor: '#355172' },
  sectionHeader: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  sectionTitle: {
    color: ink,
    fontFamily: 'InterSemiBold',
    fontSize: 16,
    lineHeight: 24,
  },
  newBooking: {
    maxWidth: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    minHeight: 44,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: '#E0EAF5',
    borderRadius: 14,
  },
  linkText: {
    flexShrink: 1,
    color: ink,
    fontFamily: 'InterSemiBold',
    fontSize: 13,
    lineHeight: 20,
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#E0E4EA',
    borderLeftWidth: 4,
    padding: 16,
    gap: 14,
    shadowColor: ink,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 2,
  },
  cardTop: { flexDirection: 'row', alignItems: 'flex-start', gap: 14 },
  thumbnail: {
    width: '28%',
    maxWidth: 112,
    aspectRatio: 0.86,
    borderRadius: 12,
    backgroundColor: '#EBE5E0',
  },
  packageTitle: {
    color: ink,
    fontFamily: 'InterSemiBold',
    fontSize: 17,
    lineHeight: 25,
  },
  badge: {
    alignSelf: 'flex-start',
    maxWidth: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  statusDot: { width: 6, height: 6, borderRadius: 3 },
  badgeText: {
    flexShrink: 1,
    fontFamily: 'InterSemiBold',
    fontSize: 11,
    lineHeight: 17,
  },
  schedule: {
    backgroundColor: '#F5F7FA',
    borderRadius: 12,
    padding: 12,
    gap: 8,
  },
  metaRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 10 },
  metaText: {
    flex: 1,
    minWidth: 0,
    color: muted,
    fontFamily: 'InterMedium',
    fontSize: 13,
    lineHeight: 20,
  },
  cardFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  chevron: {
    backgroundColor: '#EDF2F7',
    borderRadius: 16,
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyCard: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E3DDD5',
    borderRadius: 24,
    overflow: 'hidden',
  },
  emptyArt: { backgroundColor: '#F2E7DC', padding: 20, alignItems: 'center' },
  collage: { width: '100%', maxWidth: 320, aspectRatio: 1.65 },
  emptyCopy: { padding: 24, gap: 14 },
  accent: {
    width: 40,
    height: 3,
    backgroundColor: warmAccent,
    borderRadius: 2,
  },
  emptyTitle: {
    color: ink,
    fontFamily: 'Jomolhari',
    fontSize: 25,
    lineHeight: 36,
  },
  body: { color: muted, fontFamily: 'Inter', fontSize: 14, lineHeight: 22 },
  primaryButton: {
    backgroundColor: ink,
    borderRadius: 16,
    minHeight: 52,
    paddingHorizontal: 18,
    paddingVertical: 14,
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  buttonText: {
    color: '#FFFFFF',
    fontFamily: 'InterSemiBold',
    fontSize: 15,
    lineHeight: 23,
    textAlign: 'center',
    flexShrink: 1,
  },
  secondaryButton: {
    borderWidth: 1,
    borderColor: '#D6DFE9',
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    minHeight: 48,
    padding: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryText: {
    color: ink,
    fontFamily: 'InterSemiBold',
    fontSize: 14,
    lineHeight: 22,
    textAlign: 'center',
  },
  filterEmpty: {
    backgroundColor: '#FFFFFF',
    padding: 24,
    borderRadius: 20,
    gap: 14,
    borderWidth: 1,
    borderColor: '#E0E4EA',
  },
  skeleton: { gap: 10 },
  skeletonLine: {
    backgroundColor: '#E4EAF0',
    height: 16,
    borderRadius: 6,
    width: '80%',
  },
  skeletonBadge: {
    width: '45%',
    height: 24,
    borderRadius: 12,
    backgroundColor: '#EBEFF4',
  },
  detailHero: {
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#E0E4EA',
  },
  detailImage: { width: '100%', aspectRatio: 1.65, maxHeight: 300 },
  detailHeading: {
    padding: 20,
    gap: 10,
    borderTopWidth: 4,
    borderTopColor: warmAccent,
  },
  detailTitle: {
    color: ink,
    fontFamily: 'Jomolhari',
    fontSize: 25,
    lineHeight: 36,
  },
  detailCard: {
    backgroundColor: '#FFFFFF',
    padding: 20,
    borderRadius: 20,
    gap: 16,
    borderWidth: 1,
    borderColor: '#E0E4EA',
  },
  detailRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 12 },
  detailIcon: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: '#EDF2F7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  detailLabel: {
    color: muted,
    fontFamily: 'Inter',
    fontSize: 12,
    lineHeight: 18,
  },
  detailValue: {
    color: ink,
    fontFamily: 'InterMedium',
    fontSize: 15,
    lineHeight: 23,
  },
  statusPanel: { borderRadius: 20, padding: 20, gap: 12, borderWidth: 1 },
  statusHeading: { flexDirection: 'row', alignItems: 'flex-start', gap: 10 },
  statusTitle: {
    flex: 1,
    minWidth: 0,
    fontFamily: 'InterSemiBold',
    fontSize: 15,
    lineHeight: 23,
  },
  reason: {
    color: ink,
    fontFamily: 'InterMedium',
    fontSize: 14,
    lineHeight: 22,
  },
  pressed: { opacity: 0.76 },
  disabled: { opacity: 0.5 },
});
