import { StyleSheet } from 'react-native';

export const clientNotificationsStyles = StyleSheet.create({
  container: {
    backgroundColor: '#ffffff',
    flex: 1,
    overflow: 'hidden',
  },
  backgroundImage: {
    bottom: 0,
    height: '100%',
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
    width: '100%',
  },
  content: {
    paddingHorizontal: 16,
  },
  headerRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  headerCopy: {
    flex: 1,
    paddingTop: 27,
  },
  closeButton: {
    alignItems: 'center',
    height: 44,
    justifyContent: 'center',
    marginRight: 1,
    width: 44,
  },
  title: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 28,
    includeFontPadding: false,
    lineHeight: 37,
  },
  subtitle: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 14,
    includeFontPadding: false,
    lineHeight: 17,
    marginTop: 2,
    maxWidth: 230,
  },
  filterRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 9,
    marginTop: 17,
  },
  filterChip: {
    alignItems: 'center',
    backgroundColor: '#CEDFF7',
    borderRadius: 10,
    minHeight: 44,
    paddingVertical: 10,
    paddingHorizontal: 12,
    justifyContent: 'center',
    shadowColor: 'transparent',
  },
  filterChipAll: {
    minWidth: 64,
  },
  filterChipBookings: {
    minWidth: 64,
  },
  filterChipAnnouncements: {
    minWidth: 64,
  },
  filterChipActive: {
    backgroundColor: '#142C4C',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.16,
    shadowRadius: 4,
    elevation: 2,
  },
  filterText: {
    color: '#083979',
    fontFamily: 'Inter',
    fontSize: 14,
    includeFontPadding: false,
    lineHeight: 17,
  },
  filterTextActive: {
    color: '#ffffff',
  },
  loadingText: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 14,
    includeFontPadding: false,
    lineHeight: 20,
    marginTop: 26,
    textAlign: 'center',
  },
  section: {
    marginTop: 18,
  },
  sectionHeader: {
    alignItems: 'flex-end',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    justifyContent: 'space-between',
    marginBottom: 10,
    paddingHorizontal: 1,
  },
  sectionTitle: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 20,
    includeFontPadding: false,
    lineHeight: 30,
  },
  sectionDate: {
    color: '#62748C',
    fontFamily: 'Inter',
    fontSize: 12,
    includeFontPadding: false,
    lineHeight: 17,
    marginBottom: 5,
  },
  list: {
    gap: 9,
  },
  card: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: 'rgba(76, 94, 118, 0.13)',
    borderRadius: 10,
    borderWidth: 1,
    flexDirection: 'row',
    minHeight: 91,
    paddingVertical: 10,
    paddingLeft: 9,
    paddingRight: 11,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 3,
  },
  badge: {
    alignItems: 'center',
    borderRadius: 36,
    height: 72,
    justifyContent: 'center',
    marginRight: 13,
    width: 72,
  },
  badgeApproved: {
    backgroundColor: '#96F5AE',
  },
  badgeAppointment: {
    backgroundColor: '#E1EFFC',
  },
  badgeReview: {
    backgroundColor: '#FFE5AB',
  },
  badgeRejected: {
    backgroundColor: '#FFDDE6',
  },
  badgeAnnouncement: {
    backgroundColor: '#E8D9FF',
  },
  badgeCompleted: {
    backgroundColor: '#DFF1FF',
  },
  copy: {
    flex: 1,
    minWidth: 0,
    paddingRight: 8,
  },
  cardTitle: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 14,
    includeFontPadding: false,
    lineHeight: 19,
  },
  message: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 11,
    includeFontPadding: false,
    lineHeight: 14,
    marginTop: 2,
  },
  timeRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 4,
    marginTop: 3,
  },
  meta: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 11,
    includeFontPadding: false,
    lineHeight: 14,
  },
  unreadDot: {
    backgroundColor: '#CF2027',
    borderRadius: 3.5,
    height: 7,
    marginRight: 9,
    width: 7,
  },
});
