import { StyleSheet } from 'react-native';

export const homeStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F3EEEE',
    overflow: 'hidden',
  },
  heroImage: {
    position: 'absolute',
    top: 0,
  },
  contentPanel: {
    position: 'absolute',
    bottom: 0,
    backgroundColor: '#F3EEEE',
  },
  brandTitle: {
    position: 'absolute',
    color: '#ffffff',
    fontFamily: 'Jomolhari',
    includeFontPadding: false,
    textAlign: 'center',
  },
  notificationButton: {
    position: 'absolute',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: 'rgba(255, 255, 255, 0.4)',
    borderWidth: 1,
    justifyContent: 'center',
  },
  notificationDot: {
    position: 'absolute',
    right: 7,
    top: 7,
    backgroundColor: '#ED2314',
    borderColor: '#ffffff',
    borderWidth: 1,
  },
  notificationPopover: {
    position: 'absolute',
    backgroundColor: '#ffffff',
    borderColor: 'rgba(76, 94, 118, 0.14)',
    borderWidth: 1,
    padding: 12,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.16,
    shadowRadius: 10,
    elevation: 7,
    zIndex: 10,
  },
  notificationHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  notificationTitle: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    includeFontPadding: false,
  },
  notificationMeta: {
    color: '#ED2314',
    fontFamily: 'InterBold',
    includeFontPadding: false,
  },
  notificationEmpty: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    includeFontPadding: false,
  },
  notificationCard: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: 'rgba(76, 94, 118, 0.12)',
    borderRadius: 10,
    borderWidth: 1,
    flexDirection: 'row',
    minHeight: 56,
    paddingHorizontal: 9,
    paddingVertical: 8,
    marginTop: 7,
  },
  notificationCardIcon: {
    alignItems: 'center',
    backgroundColor: '#FFF1F1',
    borderRadius: 10,
    height: 34,
    justifyContent: 'center',
    marginRight: 9,
    width: 34,
  },
  notificationCardCopy: {
    flex: 1,
    minWidth: 0,
  },
  notificationCardTitle: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    includeFontPadding: false,
  },
  notificationCardMessage: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    includeFontPadding: false,
    marginTop: 2,
  },
  notificationUnreadDot: {
    backgroundColor: '#ED2314',
    borderRadius: 4,
    height: 8,
    marginLeft: 6,
    width: 8,
  },
  cameraIcon: {
    position: 'absolute',
  },
  photographerName: {
    position: 'absolute',
    color: '#ffffff',
    fontFamily: 'Italianno',
    includeFontPadding: false,
  },
  photographyRow: {
    position: 'absolute',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  photographyLine: {
    height: 1,
    backgroundColor: '#ffffff',
  },
  photographyText: {
    color: '#ffffff',
    fontFamily: 'Inter',
    includeFontPadding: false,
  },
  headline: {
    position: 'absolute',
    color: '#ffffff',
    fontFamily: 'Jomolhari',
    includeFontPadding: false,
  },
  subtitle: {
    position: 'absolute',
    color: '#ffffff',
    fontFamily: 'Inter',
    includeFontPadding: false,
  },
  bookButton: {
    position: 'absolute',
    alignItems: 'center',
    backgroundColor: '#4C77A5',
    justifyContent: 'center',
  },
  bookButtonText: {
    color: '#ffffff',
    fontFamily: 'Inter',
    includeFontPadding: false,
  },
  highlightsTitle: {
    position: 'absolute',
    color: '#162B4A',
    fontFamily: 'InterBold',
    includeFontPadding: false,
  },
  panelDot: {
    position: 'absolute',
    backgroundColor: '#162B4A',
  },
  highlightImage: {
    position: 'absolute',
    shadowColor: '#142C4C',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.55,
    shadowRadius: 4,
    elevation: 4,
  },
  highlightLabel: {
    position: 'absolute',
    color: '#162B4A',
    fontFamily: 'InterBold',
    includeFontPadding: false,
    textAlign: 'center',
  },
});
