import { StyleSheet } from 'react-native';

export const notificationInboxStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#F4F6F9' },
  header: { backgroundColor: '#142C4C', borderBottomLeftRadius: 24, borderBottomRightRadius: 24 },
  headerInner: { width: '100%', maxWidth: 760, alignSelf: 'center', padding: 20, paddingBottom: 22, gap: 8 },
  titleRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  title: { flex: 1, fontFamily: 'Jomolhari', fontSize: 28, lineHeight: 42, color: '#FFFFFF' },
  close: { width: 44, minHeight: 44, borderRadius: 22, backgroundColor: '#294363', alignItems: 'center', justifyContent: 'center' },
  subtitle: { fontFamily: 'Inter', fontSize: 14, lineHeight: 21, color: '#D5E2F0' },
  count: { alignSelf: 'flex-start', borderRadius: 20, backgroundColor: '#294363', paddingHorizontal: 12, paddingVertical: 6 },
  countText: { fontFamily: 'InterSemiBold', color: '#EDF5FF', fontSize: 12, lineHeight: 18 },
  list: { flex: 1 },
  content: { width: '100%', maxWidth: 760, alignSelf: 'center', paddingHorizontal: 20, paddingTop: 20, flexGrow: 1 },
  toolbar: { gap: 8, marginBottom: 8 },
  filterRow: { flexDirection: 'row', gap: 8, flexWrap: 'wrap' },
  filter: { minHeight: 44, paddingVertical: 12, paddingHorizontal: 18, borderRadius: 22, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#DBE3ED', justifyContent: 'center' },
  filterActive: { backgroundColor: '#142C4C', borderColor: '#142C4C' },
  filterText: { fontFamily: 'InterSemiBold', fontSize: 14, lineHeight: 20, color: '#425A77' },
  filterTextActive: { color: '#FFFFFF' },
  actions: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', columnGap: 16 },
  action: { minHeight: 44, justifyContent: 'center', paddingVertical: 10 },
  actionText: { fontFamily: 'InterSemiBold', fontSize: 13, lineHeight: 20, color: '#2D6899' },
  mutedAction: { color: '#74869A' },
  section: { fontFamily: 'InterSemiBold', fontSize: 13, lineHeight: 20, color: '#5C6E83', marginTop: 14, marginBottom: 10 },
  card: { padding: 16, borderRadius: 18, borderWidth: 1, borderColor: '#E0E6ED', backgroundColor: '#FFFFFF', marginBottom: 10, gap: 12 },
  unreadCard: { backgroundColor: '#EAF3FC', borderColor: '#C8DEF2' },
  cardTop: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  icon: { width: 42, height: 42, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  cardTitle: { fontFamily: 'InterSemiBold', fontSize: 15, lineHeight: 23, color: '#142C4C', flex: 1 },
  unreadDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: '#287CC2' },
  message: { fontFamily: 'Inter', fontSize: 14, lineHeight: 22, color: '#4D617A' },
  metaRow: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', columnGap: 12, rowGap: 6 },
  time: { fontFamily: 'Inter', fontSize: 12, lineHeight: 19, color: '#65778C', flexGrow: 1 },
  link: { fontFamily: 'InterSemiBold', fontSize: 12, lineHeight: 19, color: '#2D6899' },
  empty: { alignItems: 'center', gap: 12, paddingVertical: 44, paddingHorizontal: 18 },
  emptyIcon: { width: 80, height: 80, borderRadius: 28, backgroundColor: '#E2EDF8', alignItems: 'center', justifyContent: 'center', marginBottom: 6 },
  emptyTitle: { fontFamily: 'Jomolhari', fontSize: 23, lineHeight: 34, color: '#142C4C', textAlign: 'center' },
  emptyText: { fontFamily: 'Inter', fontSize: 14, lineHeight: 23, color: '#5C6E83', textAlign: 'center', maxWidth: 360 },
  error: { backgroundColor: '#FFF1EA', borderRadius: 12, padding: 14, marginBottom: 12 },
  errorText: { color: '#985233', fontFamily: 'Inter', fontSize: 13, lineHeight: 21 },
  skeleton: { height: 12, backgroundColor: '#E1E7EF', borderRadius: 6, width: '100%' },
  skeletonTitle: { height: 17, width: '65%' },
  footer: { alignItems: 'center', paddingVertical: 12 },
  pressed: { opacity: 0.75 },
});
