import { StyleSheet } from 'react-native';

export const photographerStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F3EEEE',
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 48,
  },
  header: {
    marginBottom: 18,
  },
  eyebrow: {
    color: '#4C5E76',
    fontFamily: 'InterBold',
    fontSize: 11,
    includeFontPadding: false,
    letterSpacing: 0,
    marginBottom: 8,
    textTransform: 'uppercase',
  },
  title: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 32,
    includeFontPadding: false,
    lineHeight: 42,
  },
  subtitle: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 14,
    includeFontPadding: false,
    lineHeight: 20,
    marginTop: 4,
  },
  heroPanel: {
    backgroundColor: '#142C4C',
    borderRadius: 20,
    marginBottom: 14,
    overflow: 'hidden',
    padding: 20,
  },
  heroLabel: {
    color: '#8AA3C3',
    fontFamily: 'InterBold',
    fontSize: 11,
    includeFontPadding: false,
    marginBottom: 10,
    textTransform: 'uppercase',
  },
  heroTitle: {
    color: '#ffffff',
    fontFamily: 'Jomolhari',
    fontSize: 28,
    includeFontPadding: false,
    lineHeight: 36,
  },
  heroMeta: {
    color: '#EAF2FA',
    fontFamily: 'Inter',
    fontSize: 13,
    includeFontPadding: false,
    lineHeight: 18,
    marginTop: 8,
  },
  statsGrid: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 14,
  },
  statCard: {
    flex: 1,
    backgroundColor: '#ffffff',
    borderColor: 'rgba(76, 94, 118, 0.18)',
    borderRadius: 12,
    borderWidth: 1,
    minHeight: 88,
    padding: 12,
  },
  statValue: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 26,
    includeFontPadding: false,
    lineHeight: 32,
  },
  statLabel: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 12,
    includeFontPadding: false,
    lineHeight: 16,
    marginTop: 4,
  },
  sectionTitle: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 18,
    includeFontPadding: false,
    lineHeight: 24,
    marginBottom: 10,
    marginTop: 4,
  },
  actionRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 16,
  },
  actionButton: {
    alignItems: 'center',
    backgroundColor: '#8AA3C3',
    borderRadius: 14,
    flex: 1,
    justifyContent: 'center',
    minHeight: 54,
  },
  secondaryActionButton: {
    backgroundColor: '#ffffff',
    borderColor: 'rgba(20, 44, 76, 0.22)',
    borderWidth: 1,
  },
  actionText: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 13,
    includeFontPadding: false,
  },
  listCard: {
    backgroundColor: '#ffffff',
    borderColor: 'rgba(76, 94, 118, 0.18)',
    borderRadius: 12,
    borderWidth: 1,
    marginBottom: 10,
    padding: 14,
  },
  listTopRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  listTitle: {
    color: '#142C4C',
    flex: 1,
    fontFamily: 'Jomolhari',
    fontSize: 17,
    includeFontPadding: false,
    lineHeight: 24,
  },
  badge: {
    alignItems: 'center',
    backgroundColor: '#EAF2FA',
    borderRadius: 999,
    justifyContent: 'center',
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  badgeText: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 10,
    includeFontPadding: false,
    textTransform: 'uppercase',
  },
  listMeta: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 12,
    includeFontPadding: false,
    lineHeight: 17,
    marginTop: 4,
  },
  placeholderPanel: {
    backgroundColor: '#ffffff',
    borderColor: 'rgba(76, 94, 118, 0.18)',
    borderRadius: 16,
    borderWidth: 1,
    padding: 18,
  },
  adminHomeContent: {
    paddingHorizontal: 18,
    paddingTop: 52,
  },
  adminTopBar: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 22,
  },
  iconButton: {
    alignItems: 'center',
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  adminBrand: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  adminBrandText: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 24,
    includeFontPadding: false,
    lineHeight: 35,
  },
  adminAvatar: {
    alignItems: 'center',
    backgroundColor: '#EAF2FA',
    borderColor: '#ffffff',
    borderRadius: 19,
    borderWidth: 2,
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  adminAvatarText: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 15,
    includeFontPadding: false,
  },
  floatingBellButton: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: 'rgba(76, 94, 118, 0.12)',
    borderRadius: 19,
    borderWidth: 1,
    height: 38,
    justifyContent: 'center',
    position: 'relative',
    width: 38,
  },
  floatingBellDot: {
    backgroundColor: '#ED2314',
    borderColor: '#ffffff',
    borderRadius: 5,
    borderWidth: 1,
    height: 10,
    position: 'absolute',
    right: 7,
    top: 7,
    width: 10,
  },
  notificationPopover: {
    alignSelf: 'flex-end',
    backgroundColor: '#ffffff',
    borderColor: 'rgba(76, 94, 118, 0.14)',
    borderRadius: 14,
    borderWidth: 1,
    gap: 8,
    marginTop: -12,
    marginBottom: 16,
    padding: 12,
    width: 286,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 5,
  },
  notificationPopoverHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  notificationPopoverTitle: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 15,
    includeFontPadding: false,
  },
  notificationPopoverMeta: {
    color: '#ED2314',
    fontFamily: 'InterBold',
    fontSize: 11,
    includeFontPadding: false,
  },
  adminHero: {
    minHeight: 105,
    marginBottom: 18,
    overflow: 'hidden',
    position: 'relative',
  },
  heroDecorationOne: {
    position: 'absolute',
    right: 6,
    top: 0,
    width: 124,
    height: 74,
    borderRadius: 12,
    backgroundColor: 'rgba(138, 163, 195, 0.22)',
    transform: [{ rotate: '-16deg' }],
  },
  heroDecorationTwo: {
    position: 'absolute',
    right: 48,
    top: 28,
    width: 82,
    height: 58,
    borderRadius: 10,
    backgroundColor: 'rgba(20, 44, 76, 0.12)',
    transform: [{ rotate: '12deg' }],
  },
  adminGreeting: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 28,
    includeFontPadding: false,
    lineHeight: 35,
  },
  adminDate: {
    color: '#8AA3C3',
    fontFamily: 'InterBold',
    fontSize: 12,
    includeFontPadding: false,
    lineHeight: 17,
    marginTop: 6,
  },
  adminStatsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 26,
  },
  adminStatCard: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: 'rgba(76, 94, 118, 0.12)',
    borderRadius: 12,
    borderWidth: 1,
    minHeight: 112,
    paddingHorizontal: 5,
    paddingVertical: 10,
    width: '31.6%',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 2,
  },
  adminStatIconWrap: {
    alignItems: 'center',
    backgroundColor: '#F2F7FD',
    borderRadius: 11,
    height: 34,
    justifyContent: 'center',
    marginBottom: 8,
    width: 34,
  },
  adminStatValue: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 29,
    includeFontPadding: false,
    lineHeight: 34,
    textAlign: 'center',
  },
  adminStatLabel: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 10,
    includeFontPadding: false,
    lineHeight: 12,
    marginTop: 4,
    textAlign: 'center',
  },
  adminSectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  adminSectionTitle: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 19,
    includeFontPadding: false,
    lineHeight: 25,
  },
  viewAllButton: {
    paddingHorizontal: 4,
    paddingVertical: 4,
  },
  viewAllText: {
    color: '#4C77A5',
    fontFamily: 'InterBold',
    fontSize: 13,
    includeFontPadding: false,
  },
  adminListPanel: {
    gap: 10,
    marginBottom: 22,
  },
  adminAppointmentCard: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: 'rgba(76, 94, 118, 0.12)',
    borderRadius: 13,
    borderWidth: 1,
    flexDirection: 'row',
    minHeight: 74,
    paddingHorizontal: 10,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 5,
    elevation: 2,
  },
  appointmentThumb: {
    alignItems: 'center',
    backgroundColor: '#EAF2FA',
    borderRadius: 9,
    height: 56,
    justifyContent: 'center',
    marginRight: 12,
    width: 56,
  },
  appointmentCopy: {
    flex: 1,
    minWidth: 0,
  },
  appointmentTime: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 18,
    includeFontPadding: false,
    lineHeight: 22,
  },
  appointmentService: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 17,
    includeFontPadding: false,
    lineHeight: 22,
  },
  appointmentClient: {
    color: '#4C5E76',
    fontFamily: 'InterBold',
    fontSize: 12,
    includeFontPadding: false,
    lineHeight: 16,
  },
  appointmentBadge: {
    alignItems: 'center',
    borderRadius: 999,
    justifyContent: 'center',
    marginHorizontal: 8,
    minWidth: 70,
    paddingHorizontal: 9,
    paddingVertical: 6,
  },
  ongoingBadge: {
    backgroundColor: '#DDF5EC',
  },
  upcomingBadge: {
    backgroundColor: '#E4F0FF',
  },
  appointmentBadgeText: {
    fontFamily: 'InterBold',
    fontSize: 11,
    includeFontPadding: false,
  },
  ongoingText: {
    color: '#3D9D7A',
  },
  upcomingText: {
    color: '#4C8DEB',
  },
  adminNotificationCard: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: 'rgba(76, 94, 118, 0.12)',
    borderRadius: 13,
    borderWidth: 1,
    flexDirection: 'row',
    minHeight: 64,
    paddingHorizontal: 12,
  },
  readNotificationCard: {
    opacity: 0.72,
  },
  notificationUnreadDot: {
    backgroundColor: '#ED2314',
    borderRadius: 4,
    height: 8,
    marginLeft: 8,
    width: 8,
  },
  notificationIconWrap: {
    alignItems: 'center',
    backgroundColor: '#FFF1F1',
    borderRadius: 12,
    height: 42,
    justifyContent: 'center',
    marginRight: 12,
    width: 42,
  },
  notificationCopy: {
    flex: 1,
    minWidth: 0,
  },
  notificationTitle: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 14,
    includeFontPadding: false,
    lineHeight: 19,
  },
  notificationMeta: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 12,
    includeFontPadding: false,
    lineHeight: 17,
  },
  adminRequestContent: {
    paddingHorizontal: 18,
    paddingTop: 62,
  },
  adminPageTitle: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 30,
    includeFontPadding: false,
    lineHeight: 38,
  },
  adminPageSubtitle: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 14,
    includeFontPadding: false,
    lineHeight: 20,
    marginTop: 2,
  },
  requestFilterContent: {
    gap: 8,
    paddingVertical: 18,
  },
  requestFilterPill: {
    alignItems: 'center',
    backgroundColor: '#EAF2FA',
    borderRadius: 9,
    justifyContent: 'center',
    minHeight: 36,
    paddingHorizontal: 14,
  },
  activeRequestFilter: {
    backgroundColor: '#4C77A5',
  },
  requestFilterText: {
    color: '#4C5E76',
    fontFamily: 'InterBold',
    fontSize: 12,
    includeFontPadding: false,
  },
  activeRequestFilterText: {
    color: '#ffffff',
  },
  requestSearchRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    marginBottom: 18,
  },
  requestSearchBox: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: 'rgba(76, 94, 118, 0.2)',
    borderRadius: 10,
    borderWidth: 1,
    flex: 1,
    flexDirection: 'row',
    height: 50,
    paddingHorizontal: 12,
  },
  requestSearchInput: {
    color: '#142C4C',
    flex: 1,
    fontFamily: 'Inter',
    fontSize: 13,
    includeFontPadding: false,
    paddingHorizontal: 10,
    paddingVertical: 0,
  },
  requestFilterButton: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: 'rgba(76, 94, 118, 0.2)',
    borderRadius: 10,
    borderWidth: 1,
    height: 50,
    justifyContent: 'center',
    width: 50,
  },
  requestList: {
    gap: 10,
  },
  requestCard: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: 'rgba(76, 94, 118, 0.1)',
    borderRadius: 15,
    borderWidth: 1,
    flexDirection: 'row',
    minHeight: 84,
    paddingHorizontal: 11,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 2,
  },
  requestAvatar: {
    alignItems: 'center',
    backgroundColor: '#EAF2FA',
    borderRadius: 28,
    height: 56,
    justifyContent: 'center',
    marginRight: 13,
    width: 56,
  },
  requestAvatarText: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 26,
    includeFontPadding: false,
  },
  requestCopy: {
    flex: 1,
    minWidth: 0,
  },
  requestName: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 16,
    includeFontPadding: false,
    lineHeight: 21,
  },
  requestPackage: {
    color: '#4C5E76',
    fontFamily: 'InterBold',
    fontSize: 13,
    includeFontPadding: false,
    lineHeight: 18,
  },
  requestDate: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 12,
    includeFontPadding: false,
    lineHeight: 17,
  },
  pendingPill: {
    alignItems: 'center',
    backgroundColor: '#FFF1D8',
    borderRadius: 999,
    justifyContent: 'center',
    marginHorizontal: 8,
    minWidth: 76,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  pendingPillText: {
    color: '#F49A28',
    fontFamily: 'InterBold',
    fontSize: 12,
    includeFontPadding: false,
  },
  requestDetailContent: {
    paddingHorizontal: 22,
    paddingTop: 58,
  },
  detailTopBar: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 22,
  },
  detailIconButton: {
    alignItems: 'center',
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  detailBrand: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  detailBrandText: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 24,
    includeFontPadding: false,
    lineHeight: 35,
  },
  detailPendingPill: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: '#FFF1D8',
    borderRadius: 999,
    marginBottom: 18,
    paddingHorizontal: 18,
    paddingVertical: 7,
  },
  detailConfirmedPill: {
    backgroundColor: '#DDF4EC',
  },
  detailRejectedPill: {
    backgroundColor: '#FFE3E4',
  },
  detailPendingText: {
    color: '#F49A28',
    fontFamily: 'InterBold',
    fontSize: 13,
    includeFontPadding: false,
  },
  detailConfirmedText: {
    color: '#2D8F78',
  },
  detailRejectedText: {
    color: '#E45F62',
  },
  clientHeaderRow: {
    alignItems: 'center',
    flexDirection: 'row',
    marginBottom: 22,
  },
  detailAvatar: {
    alignItems: 'center',
    backgroundColor: '#EAF2FA',
    borderRadius: 35,
    height: 70,
    justifyContent: 'center',
    marginRight: 18,
    width: 70,
  },
  detailAvatarText: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 34,
    includeFontPadding: false,
  },
  clientInfo: {
    flex: 1,
  },
  clientName: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 19,
    includeFontPadding: false,
    lineHeight: 25,
    marginBottom: 6,
  },
  clientInfoRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 9,
    marginTop: 3,
  },
  clientMeta: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 13,
    includeFontPadding: false,
    lineHeight: 18,
  },
  detailSectionTitle: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 17,
    includeFontPadding: false,
    lineHeight: 23,
    marginBottom: 10,
    marginTop: 8,
  },
  serviceDetailRow: {
    flexDirection: 'row',
    marginBottom: 16,
  },
  serviceImagePlaceholder: {
    alignItems: 'center',
    backgroundColor: '#EAF2FA',
    borderRadius: 10,
    height: 106,
    justifyContent: 'center',
    marginRight: 16,
    width: 106,
  },
  serviceDetailCopy: {
    flex: 1,
  },
  serviceDetailTitle: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 20,
    includeFontPadding: false,
    lineHeight: 26,
  },
  serviceDetailPrice: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 18,
    includeFontPadding: false,
    lineHeight: 23,
    marginBottom: 5,
  },
  serviceBullet: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 12,
    includeFontPadding: false,
    lineHeight: 17,
  },
  dateTimeRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 16,
  },
  dateTimePill: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: 'rgba(76, 94, 118, 0.18)',
    borderRadius: 10,
    borderWidth: 1,
    flex: 1,
    flexDirection: 'row',
    gap: 7,
    minHeight: 50,
    paddingHorizontal: 10,
  },
  dateTimeText: {
    color: '#4C5E76',
    flexShrink: 1,
    fontFamily: 'InterBold',
    fontSize: 12,
    includeFontPadding: false,
    lineHeight: 17,
  },
  notesBox: {
    backgroundColor: '#EAF4FF',
    borderRadius: 12,
    marginBottom: 20,
    padding: 18,
  },
  sessionDetailBlock: {
    marginTop: 8,
  },
  sessionDetailLabel: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 12,
    includeFontPadding: false,
    lineHeight: 17,
    marginBottom: 3,
  },
  sessionDetailRow: {
    marginBottom: 11,
  },
  sessionDetailValue: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 14,
    includeFontPadding: false,
    lineHeight: 20,
  },
  notesText: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 14,
    includeFontPadding: false,
    lineHeight: 21,
  },
  detailActionRow: {
    flexDirection: 'row',
    gap: 12,
  },
  rejectButton: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: '#F37C7E',
    borderRadius: 14,
    borderWidth: 1.5,
    flex: 1,
    height: 58,
    justifyContent: 'center',
  },
  rejectButtonText: {
    color: '#E45F62',
    fontFamily: 'InterBold',
    fontSize: 14,
    includeFontPadding: false,
  },
  confirmButton: {
    alignItems: 'center',
    backgroundColor: '#142C4C',
    borderRadius: 14,
    flex: 1,
    height: 58,
    justifyContent: 'center',
  },
  confirmButtonText: {
    color: '#ffffff',
    fontFamily: 'InterBold',
    fontSize: 14,
    includeFontPadding: false,
  },
  resolvedRequestPanel: {
    backgroundColor: '#ffffff',
    borderColor: 'rgba(76, 94, 118, 0.14)',
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 16,
    paddingVertical: 15,
  },
  resolvedRequestTitle: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 15,
    includeFontPadding: false,
    lineHeight: 21,
  },
  resolvedRequestText: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 13,
    includeFontPadding: false,
    lineHeight: 19,
    marginTop: 5,
  },
  rejectionReasonBox: {
    backgroundColor: '#FFF6F6',
    borderColor: 'rgba(228, 95, 98, 0.18)',
    borderRadius: 12,
    borderWidth: 1,
    marginTop: 12,
    padding: 12,
  },
  rejectionReasonLabel: {
    color: '#E45F62',
    fontFamily: 'InterBold',
    fontSize: 12,
    includeFontPadding: false,
    lineHeight: 16,
  },
  rejectionReasonText: {
    color: '#142C4C',
    fontFamily: 'Inter',
    fontSize: 13,
    includeFontPadding: false,
    lineHeight: 18,
    marginTop: 4,
  },
  rejectModalOverlay: {
    alignItems: 'center',
    backgroundColor: 'rgba(20, 44, 76, 0.38)',
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 22,
  },
  rejectModalCard: {
    backgroundColor: '#F3EEEE',
    borderRadius: 18,
    padding: 18,
    width: '100%',
  },
  rejectModalTitle: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 24,
    includeFontPadding: false,
    lineHeight: 34,
  },
  rejectModalMessage: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 13,
    includeFontPadding: false,
    lineHeight: 19,
    marginTop: 4,
  },
  rejectReasonInput: {
    backgroundColor: '#ffffff',
    borderColor: 'rgba(76, 94, 118, 0.22)',
    borderRadius: 12,
    borderWidth: 1,
    color: '#142C4C',
    fontFamily: 'Inter',
    fontSize: 14,
    includeFontPadding: false,
    marginTop: 14,
    minHeight: 106,
    paddingHorizontal: 12,
    paddingVertical: 10,
    textAlignVertical: 'top',
  },
  rejectModalActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 14,
  },
  rejectModalCancelButton: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: 'rgba(76, 94, 118, 0.22)',
    borderRadius: 12,
    borderWidth: 1,
    flex: 1,
    height: 50,
    justifyContent: 'center',
  },
  rejectModalCancelText: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 14,
    includeFontPadding: false,
  },
  rejectModalSubmitButton: {
    alignItems: 'center',
    backgroundColor: '#E45F62',
    borderRadius: 12,
    flex: 1,
    height: 50,
    justifyContent: 'center',
  },
  rejectModalSubmitText: {
    color: '#ffffff',
    fontFamily: 'InterBold',
    fontSize: 14,
    includeFontPadding: false,
  },
  adminCalendarContent: {
    paddingHorizontal: 18,
    paddingTop: 62,
  },
  calendarHeaderRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 18,
  },
  calendarAddButton: {
    alignItems: 'center',
    backgroundColor: '#142C4C',
    borderRadius: 10,
    height: 48,
    justifyContent: 'center',
    width: 48,
  },
  calendarMonthCard: {
    backgroundColor: '#ffffff',
    borderColor: 'rgba(76, 94, 118, 0.12)',
    borderRadius: 15,
    borderWidth: 1,
    overflow: 'hidden',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  calendarMonthHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    height: 58,
    justifyContent: 'space-between',
    paddingHorizontal: 16,
  },
  calendarMonthText: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 19,
    includeFontPadding: false,
    lineHeight: 27,
  },
  calendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  calendarWeekText: {
    backgroundColor: '#F6FAFF',
    color: '#4C5E76',
    fontFamily: 'InterBold',
    fontSize: 12,
    includeFontPadding: false,
    lineHeight: 44,
    textAlign: 'center',
    width: `${100 / 7}%`,
  },
  calendarDayCell: {
    alignItems: 'center',
    borderColor: '#EDF2F6',
    borderRightWidth: 1,
    borderTopWidth: 1,
    height: 58,
    justifyContent: 'center',
    width: `${100 / 7}%`,
  },
  selectedCalendarDay: {
    backgroundColor: '#D9EAFF',
  },
  calendarDayText: {
    color: '#4C5E76',
    fontFamily: 'InterBold',
    fontSize: 14,
    includeFontPadding: false,
    lineHeight: 19,
  },
  selectedDayText: {
    color: '#142C4C',
  },
  unavailableDayText: {
    color: '#F37C7E',
  },
  calendarDots: {
    flexDirection: 'row',
    gap: 3,
    height: 8,
    marginTop: 4,
  },
  calendarDot: {
    borderRadius: 3,
    height: 5,
    width: 5,
  },
  availableDot: {
    backgroundColor: '#4FB69F',
  },
  bookedDot: {
    backgroundColor: '#142C4C',
  },
  unavailableDot: {
    backgroundColor: '#F37C7E',
  },
  calendarLegendRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 28,
  },
  legendItem: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  legendDot: {
    borderRadius: 9,
    height: 18,
    width: 18,
  },
  legendText: {
    color: '#4C5E76',
    fontFamily: 'InterBold',
    fontSize: 13,
    includeFontPadding: false,
  },
  timeSlotPanel: {
    marginTop: 28,
  },
  timeSlotPanelHeaderRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
  },
  timeSlotPanelCopy: {
    flex: 1,
    minWidth: 0,
  },
  timeSlotPanelTitle: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 18,
    includeFontPadding: false,
    lineHeight: 24,
  },
  timeSlotPanelSubtitle: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 13,
    includeFontPadding: false,
    lineHeight: 18,
    marginTop: 3,
  },
  fullDayButton: {
    alignItems: 'center',
    backgroundColor: '#FFE3E4',
    borderColor: '#F37C7E',
    borderRadius: 999,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 38,
    paddingHorizontal: 14,
  },
  fullDayButtonText: {
    color: '#E45F62',
    fontFamily: 'InterBold',
    fontSize: 12,
    includeFontPadding: false,
    lineHeight: 16,
  },
  reopenDayButton: {
    backgroundColor: '#EAF8F4',
    borderColor: '#4FB69F',
  },
  reopenDayButtonText: {
    color: '#2D8F78',
  },
  timeSlotList: {
    gap: 10,
    marginTop: 14,
  },
  timeSlotCard: {
    backgroundColor: '#ffffff',
    borderColor: 'rgba(76, 94, 118, 0.12)',
    borderRadius: 13,
    borderWidth: 1,
    padding: 12,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 2,
  },
  timeSlotCopy: {
    marginBottom: 10,
  },
  timeSlotTime: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 16,
    includeFontPadding: false,
    lineHeight: 22,
  },
  timeSlotStatus: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 13,
    includeFontPadding: false,
    lineHeight: 18,
    marginTop: 3,
  },
  timeSlotActions: {
    flexDirection: 'row',
    gap: 8,
  },
  timeSlotManageRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 8,
  },
  slotAvailableButton: {
    alignItems: 'center',
    backgroundColor: '#EAF8F4',
    borderColor: '#4FB69F',
    borderRadius: 10,
    borderWidth: 1,
    flex: 1,
    minHeight: 40,
    justifyContent: 'center',
  },
  activeSlotButton: {
    backgroundColor: '#4FB69F',
  },
  slotAvailableText: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 12,
    includeFontPadding: false,
  },
  slotUnavailableButton: {
    alignItems: 'center',
    backgroundColor: '#FFF1F1',
    borderColor: '#F37C7E',
    borderRadius: 10,
    borderWidth: 1,
    flex: 1,
    minHeight: 40,
    justifyContent: 'center',
  },
  activeUnavailableButton: {
    backgroundColor: '#F37C7E',
  },
  slotUnavailableText: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 12,
    includeFontPadding: false,
  },
  slotEditButton: {
    alignItems: 'center',
    backgroundColor: '#EAF2FA',
    borderRadius: 10,
    flex: 1,
    minHeight: 38,
    justifyContent: 'center',
  },
  slotEditText: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 12,
    includeFontPadding: false,
  },
  slotDeleteButton: {
    alignItems: 'center',
    backgroundColor: '#FFF1F1',
    borderColor: '#F37C7E',
    borderRadius: 10,
    borderWidth: 1,
    flex: 1,
    minHeight: 38,
    justifyContent: 'center',
  },
  slotDeleteText: {
    color: '#E45F62',
    fontFamily: 'InterBold',
    fontSize: 12,
    includeFontPadding: false,
  },
  calendarSlotFieldRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 16,
  },
  calendarSlotField: {
    flex: 1,
  },
  calendarSlotInput: {
    backgroundColor: '#ffffff',
    borderColor: 'rgba(76, 94, 118, 0.22)',
    borderRadius: 10,
    borderWidth: 1,
    color: '#142C4C',
    fontFamily: 'Inter',
    fontSize: 14,
    height: 48,
    includeFontPadding: false,
    paddingHorizontal: 12,
  },
  adminServicesContent: {
    paddingHorizontal: 18,
    paddingTop: 62,
  },
  servicesHeaderRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  servicesHeaderCopy: {
    flex: 1,
    paddingRight: 10,
  },
  serviceAddButton: {
    alignItems: 'center',
    backgroundColor: '#142C4C',
    borderRadius: 9,
    flexDirection: 'row',
    gap: 4,
    minHeight: 38,
    paddingHorizontal: 12,
  },
  serviceAddText: {
    color: '#ffffff',
    fontFamily: 'InterBold',
    fontSize: 12,
    includeFontPadding: false,
  },
  servicesSegmentedControl: {
    backgroundColor: '#D8E8F8',
    borderRadius: 12,
    flexDirection: 'row',
    marginBottom: 17,
    padding: 4,
  },
  servicesSegment: {
    alignItems: 'center',
    borderRadius: 9,
    flex: 1,
    height: 39,
    justifyContent: 'center',
  },
  activeServicesSegment: {
    backgroundColor: '#ffffff',
  },
  servicesSegmentText: {
    color: '#4C77A5',
    fontFamily: 'InterBold',
    fontSize: 13,
    includeFontPadding: false,
  },
  activeServicesSegmentText: {
    color: '#142C4C',
  },
  serviceCategoryList: {
    gap: 10,
  },
  serviceCategoryCard: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: 'rgba(76, 94, 118, 0.12)',
    borderRadius: 13,
    borderWidth: 1,
    flexDirection: 'row',
    minHeight: 76,
    paddingHorizontal: 10,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 2,
  },
  serviceCategoryThumb: {
    alignItems: 'center',
    borderRadius: 10,
    height: 56,
    justifyContent: 'center',
    marginRight: 13,
    overflow: 'hidden',
    width: 80,
  },
  serviceThumbImage: {
    height: '100%',
    width: '100%',
  },
  serviceThumbTone1: {
    backgroundColor: '#EAF2FA',
  },
  serviceThumbTone2: {
    backgroundColor: '#F2E9E4',
  },
  serviceThumbTone3: {
    backgroundColor: '#EDE7DD',
  },
  serviceThumbTone4: {
    backgroundColor: '#E3EFE8',
  },
  serviceCategoryCopy: {
    flex: 1,
    minWidth: 0,
  },
  serviceCategoryName: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 15,
    includeFontPadding: false,
    lineHeight: 21,
  },
  serviceCategoryCount: {
    color: '#4C77A5',
    fontFamily: 'Inter',
    fontSize: 12,
    includeFontPadding: false,
    lineHeight: 17,
    marginTop: 2,
  },
  serviceManageActions: {
    gap: 6,
    marginLeft: 8,
  },
  serviceManageButton: {
    alignItems: 'center',
    backgroundColor: '#EAF2FA',
    borderRadius: 8,
    justifyContent: 'center',
    minHeight: 28,
    minWidth: 47,
    paddingHorizontal: 8,
  },
  serviceManageText: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 11,
    includeFontPadding: false,
  },
  formOverlay: {
    flex: 1,
    backgroundColor: 'rgba(20, 44, 76, 0.35)',
    justifyContent: 'flex-end',
  },
  formSheet: {
    backgroundColor: '#F3EEEE',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: '86%',
    paddingBottom: 24,
    paddingHorizontal: 18,
    paddingTop: 20,
  },
  formTitle: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 24,
    includeFontPadding: false,
    lineHeight: 34,
    marginBottom: 14,
  },
  formField: {
    marginBottom: 12,
  },
  formLabel: {
    color: '#4C5E76',
    fontFamily: 'InterBold',
    fontSize: 12,
    includeFontPadding: false,
    lineHeight: 17,
    marginBottom: 6,
  },
  formInput: {
    backgroundColor: '#ffffff',
    borderColor: 'rgba(76, 94, 118, 0.22)',
    borderRadius: 10,
    borderWidth: 1,
    color: '#142C4C',
    fontFamily: 'Inter',
    fontSize: 14,
    includeFontPadding: false,
    minHeight: 46,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  formTextarea: {
    minHeight: 92,
    textAlignVertical: 'top',
  },
  imagePickerRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
  },
  imagePickerPreview: {
    alignItems: 'center',
    backgroundColor: '#EAF2FA',
    borderColor: 'rgba(76, 94, 118, 0.22)',
    borderRadius: 12,
    borderWidth: 1,
    height: 78,
    justifyContent: 'center',
    overflow: 'hidden',
    width: 104,
  },
  imagePickerPreviewImage: {
    height: '100%',
    width: '100%',
  },
  imagePickerButton: {
    alignItems: 'center',
    backgroundColor: '#142C4C',
    borderRadius: 12,
    flex: 1,
    height: 48,
    justifyContent: 'center',
  },
  imagePickerButtonText: {
    color: '#ffffff',
    fontFamily: 'InterBold',
    fontSize: 13,
    includeFontPadding: false,
  },
  imagePickerHint: {
    color: '#6D7E94',
    fontFamily: 'Inter',
    fontSize: 11,
    includeFontPadding: false,
    lineHeight: 15,
    marginTop: 7,
  },
  activeToggleRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    marginBottom: 16,
    marginTop: 2,
  },
  activeToggleBox: {
    backgroundColor: '#E45F62',
    borderRadius: 9,
    height: 18,
    width: 18,
  },
  activeToggleBoxOn: {
    backgroundColor: '#4FB69F',
  },
  activeToggleText: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 13,
    includeFontPadding: false,
  },
  formActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 4,
  },
  formCancelButton: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: 'rgba(76, 94, 118, 0.22)',
    borderRadius: 12,
    borderWidth: 1,
    flex: 1,
    height: 52,
    justifyContent: 'center',
  },
  formCancelText: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 14,
    includeFontPadding: false,
  },
  formSaveButton: {
    alignItems: 'center',
    backgroundColor: '#142C4C',
    borderRadius: 12,
    flex: 1,
    height: 52,
    justifyContent: 'center',
  },
  formSaveText: {
    color: '#ffffff',
    fontFamily: 'InterBold',
    fontSize: 14,
    includeFontPadding: false,
  },
  servicePickerList: {
    gap: 8,
    marginBottom: 12,
  },
  servicePickerOption: {
    backgroundColor: '#ffffff',
    borderColor: 'rgba(76, 94, 118, 0.2)',
    borderRadius: 10,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  activeServicePickerOption: {
    backgroundColor: '#142C4C',
    borderColor: '#142C4C',
  },
  servicePickerText: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 13,
    includeFontPadding: false,
  },
  activeServicePickerText: {
    color: '#ffffff',
  },
  simpleProfileContainer: {
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 22,
    paddingTop: 84,
  },
  adminProfileContent: {
    paddingHorizontal: 22,
    paddingTop: 62,
  },
  simpleProfileHeader: {
    alignItems: 'center',
    marginBottom: 20,
  },
  simpleProfileLogo: {
    alignItems: 'center',
    backgroundColor: '#142C4C',
    borderColor: '#BCD0EA',
    borderRadius: 50,
    borderWidth: 4,
    height: 100,
    justifyContent: 'center',
    marginBottom: 18,
    width: 100,
  },
  simpleProfileName: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 30,
    includeFontPadding: false,
    lineHeight: 40,
  },
  simpleProfileRole: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 15,
    includeFontPadding: false,
    lineHeight: 21,
  },
  studioSettingsCard: {
    backgroundColor: '#ffffff',
    borderColor: 'rgba(76, 94, 118, 0.14)',
    borderRadius: 16,
    borderWidth: 1,
    marginBottom: 18,
    padding: 16,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  studioSettingsTitle: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 18,
    includeFontPadding: false,
    lineHeight: 24,
  },
  studioSettingsSubtitle: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 12,
    includeFontPadding: false,
    lineHeight: 18,
    marginBottom: 14,
    marginTop: 4,
  },
  studioField: {
    marginBottom: 12,
  },
  studioSaveButton: {
    alignItems: 'center',
    backgroundColor: '#142C4C',
    borderRadius: 12,
    height: 52,
    justifyContent: 'center',
    marginTop: 4,
  },
  studioSaveText: {
    color: '#ffffff',
    fontFamily: 'InterBold',
    fontSize: 14,
    includeFontPadding: false,
  },
  simpleLogoutButton: {
    alignItems: 'center',
    alignSelf: 'stretch',
    backgroundColor: '#ffffff',
    borderColor: '#F1A8AA',
    borderRadius: 12,
    borderWidth: 1.5,
    flexDirection: 'row',
    gap: 10,
    height: 58,
    justifyContent: 'center',
  },
  simpleLogoutText: {
    color: '#E45F62',
    fontFamily: 'InterBold',
    fontSize: 16,
    includeFontPadding: false,
  },
});
