import { StyleSheet } from 'react-native';

export const photographerStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F3EEEE',
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 48,
  },
  header: {
    marginBottom: 18,
  },
  eyebrow: {
    color: '#4C5E76',
    fontFamily: 'InterBold',
    fontSize: 11,
    includeFontPadding: false,
    letterSpacing: 0,
    marginBottom: 8,
    textTransform: 'uppercase',
  },
  title: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 32,
    includeFontPadding: false,
    lineHeight: 42,
  },
  subtitle: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 14,
    includeFontPadding: false,
    lineHeight: 20,
    marginTop: 4,
  },
  heroPanel: {
    backgroundColor: '#142C4C',
    borderRadius: 20,
    marginBottom: 14,
    overflow: 'hidden',
    padding: 20,
  },
  heroLabel: {
    color: '#8AA3C3',
    fontFamily: 'InterBold',
    fontSize: 11,
    includeFontPadding: false,
    marginBottom: 10,
    textTransform: 'uppercase',
  },
  heroTitle: {
    color: '#ffffff',
    fontFamily: 'Jomolhari',
    fontSize: 28,
    includeFontPadding: false,
    lineHeight: 36,
  },
  heroMeta: {
    color: '#EAF2FA',
    fontFamily: 'Inter',
    fontSize: 13,
    includeFontPadding: false,
    lineHeight: 18,
    marginTop: 8,
  },
  statsGrid: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 14,
  },
  statCard: {
    flex: 1,
    backgroundColor: '#ffffff',
    borderColor: 'rgba(76, 94, 118, 0.18)',
    borderRadius: 12,
    borderWidth: 1,
    minHeight: 88,
    padding: 12,
  },
  statValue: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 26,
    includeFontPadding: false,
    lineHeight: 32,
  },
  statLabel: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 12,
    includeFontPadding: false,
    lineHeight: 16,
    marginTop: 4,
  },
  sectionTitle: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 18,
    includeFontPadding: false,
    lineHeight: 24,
    marginBottom: 10,
    marginTop: 4,
  },
  actionRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 16,
  },
  actionButton: {
    alignItems: 'center',
    backgroundColor: '#8AA3C3',
    borderRadius: 14,
    flex: 1,
    justifyContent: 'center',
    minHeight: 54,
  },
  secondaryActionButton: {
    backgroundColor: '#ffffff',
    borderColor: 'rgba(20, 44, 76, 0.22)',
    borderWidth: 1,
  },
  actionText: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 13,
    includeFontPadding: false,
  },
  listCard: {
    backgroundColor: '#ffffff',
    borderColor: 'rgba(76, 94, 118, 0.18)',
    borderRadius: 12,
    borderWidth: 1,
    marginBottom: 10,
    padding: 14,
  },
  listTopRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  listTitle: {
    color: '#142C4C',
    flex: 1,
    fontFamily: 'Jomolhari',
    fontSize: 17,
    includeFontPadding: false,
    lineHeight: 24,
  },
  badge: {
    alignItems: 'center',
    backgroundColor: '#EAF2FA',
    borderRadius: 999,
    justifyContent: 'center',
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  badgeText: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 10,
    includeFontPadding: false,
    textTransform: 'uppercase',
  },
  listMeta: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 12,
    includeFontPadding: false,
    lineHeight: 17,
    marginTop: 4,
  },
  placeholderPanel: {
    backgroundColor: '#ffffff',
    borderColor: 'rgba(76, 94, 118, 0.18)',
    borderRadius: 16,
    borderWidth: 1,
    padding: 18,
  },
  adminHomeContent: {
    paddingHorizontal: 18,
    paddingTop: 52,
  },
  adminDashboardBackground: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 104,
  },
  adminDashboardContent: {
    minHeight: '100%',
    paddingHorizontal: 0,
  },
  adminDashboardHeader: {
    alignItems: 'center',
    backgroundColor: '#142C4C',
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    height: 120,
    justifyContent: 'flex-start',
    overflow: 'hidden',
    position: 'relative',
  },
  adminHeaderTexture: {
    height: 118,
    left: 117,
    opacity: 0.1,
    position: 'absolute',
    top: -8,
    width: 236,
  },
  adminDashboardBrand: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    marginTop: 20,
  },
  adminDashboardBrandText: {
    color: '#ffffff',
    fontFamily: 'Jomolhari',
    fontSize: 24,
    includeFontPadding: false,
    lineHeight: 34,
  },
  adminDashboardBrandLogo: {
    height: 44,
    width: 54,
  },
  adminDashboardHero: {
    minHeight: 173,
    paddingLeft: 24,
    paddingTop: 10,
    position: 'relative',
  },
  adminDashboardHeroImage: {
    height: 248,
    position: 'absolute',
    right: -48,
    top: -30,
    width: 246,
  },
  adminDashboardGreeting: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 32,
    includeFontPadding: false,
    lineHeight: 44,
  },
  adminDashboardGreetingRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    marginTop: -2,
  },
  adminDashboardNotificationButton: {
    alignItems: 'center',
    height: 32,
    justifyContent: 'center',
    position: 'relative',
    width: 32,
  },
  adminDashboardNotificationBadge: {
    alignItems: 'center',
    backgroundColor: '#ED2314',
    borderColor: '#ffffff',
    borderRadius: 9,
    borderWidth: 1,
    height: 18,
    justifyContent: 'center',
    minWidth: 18,
    paddingHorizontal: 4,
    position: 'absolute',
    right: -5,
    top: -5,
  },
  adminDashboardNotificationBadgeText: {
    color: '#ffffff',
    fontFamily: 'InterBold',
    fontSize: 10,
    includeFontPadding: false,
    lineHeight: 13,
    textAlign: 'center',
  },
  adminDashboardGreetingAccent: {
    color: '#4689E1',
    fontFamily: 'Jomolhari',
    fontSize: 32,
    includeFontPadding: false,
    lineHeight: 44,
  },
  adminDashboardSubtitle: {
    color: '#142C4C',
    fontFamily: 'Inter',
    fontSize: 15,
    fontStyle: 'italic',
    includeFontPadding: false,
    lineHeight: 21,
    marginTop: 20,
    maxWidth: 220,
  },
  adminDashboardStatsRow: {
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 25,
  },
  adminDashboardStatCard: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: 'rgba(234, 227, 226, 0.85)',
    borderRadius: 10,
    borderWidth: 1,
    flex: 1,
    height: 138,
    paddingHorizontal: 4,
    paddingTop: 12,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.16,
    shadowRadius: 8,
    elevation: 4,
  },
  adminDashboardStatIconWrap: {
    alignItems: 'center',
    backgroundColor: '#C9F4FF',
    borderRadius: 10,
    height: 34,
    justifyContent: 'center',
    marginBottom: 15,
    width: 34,
  },
  adminDashboardStatIconOrange: {
    backgroundColor: '#FFE3B6',
  },
  adminDashboardStatIconRed: {
    backgroundColor: '#FFC9CA',
  },
  adminDashboardStatValue: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 24,
    includeFontPadding: false,
    lineHeight: 33,
    textAlign: 'center',
  },
  adminDashboardStatLabel: {
    color: '#142C4C',
    fontFamily: 'Inter',
    fontSize: 10,
    includeFontPadding: false,
    lineHeight: 16,
    marginTop: 5,
    textAlign: 'center',
  },
  adminDashboardSectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 18,
    paddingHorizontal: 25,
  },
  adminDashboardSectionTitle: {
    color: '#2B3B67',
    fontFamily: 'InterBold',
    fontSize: 16,
    includeFontPadding: false,
    lineHeight: 22,
  },
  adminDashboardHeaderActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 16,
  },
  adminDashboardUpcomingPill: {
    alignItems: 'center',
    backgroundColor: '#BAD9F8',
    borderRadius: 3,
    height: 26,
    justifyContent: 'center',
    width: 68,
  },
  adminDashboardUpcomingText: {
    color: '#232BA8',
    fontFamily: 'Inter',
    fontSize: 10,
    includeFontPadding: false,
    lineHeight: 14,
  },
  adminDashboardViewAllButton: {
    paddingVertical: 4,
  },
  adminDashboardViewAllText: {
    color: '#142C4C',
    fontFamily: 'Inter',
    fontSize: 15,
    includeFontPadding: false,
    lineHeight: 21,
  },
  adminDashboardAppointmentList: {
    gap: 13,
    marginTop: 16,
    paddingHorizontal: 25,
  },
  adminDashboardAppointmentStateCard: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: '#EAE3E2',
    borderRadius: 10,
    borderWidth: 1,
    height: 97,
    justifyContent: 'center',
    paddingHorizontal: 18,
  },
  adminDashboardAppointmentStateText: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 14,
    includeFontPadding: false,
    lineHeight: 20,
    textAlign: 'center',
  },
  adminDashboardAppointmentCard: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: '#EAE3E2',
    borderRadius: 10,
    borderWidth: 1,
    flexDirection: 'row',
    height: 97,
    paddingLeft: 8,
    paddingRight: 12,
  },
  adminDashboardAppointmentImage: {
    borderRadius: 10,
    height: 83,
    marginRight: 8,
    width: 83,
  },
  adminDashboardAppointmentCopy: {
    flex: 1,
    minWidth: 0,
  },
  adminDashboardAppointmentTime: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 15,
    includeFontPadding: false,
    lineHeight: 21,
  },
  adminDashboardAppointmentService: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 13,
    includeFontPadding: false,
    lineHeight: 18,
    marginTop: 2,
  },
  adminDashboardAppointmentClient: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 14,
    includeFontPadding: false,
    lineHeight: 20,
    marginTop: 3,
  },
  adminDashboardAppointmentBadge: {
    alignItems: 'center',
    borderRadius: 3,
    height: 26,
    justifyContent: 'center',
    marginLeft: 6,
    marginRight: 3,
    width: 68,
  },
  adminDashboardAppointmentBadgeText: {
    fontFamily: 'Inter',
    fontSize: 10,
    includeFontPadding: false,
    lineHeight: 14,
  },
  adminTopBar: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 22,
  },
  iconButton: {
    alignItems: 'center',
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  adminBrand: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  adminBrandText: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 24,
    includeFontPadding: false,
    lineHeight: 35,
  },
  adminAvatar: {
    alignItems: 'center',
    backgroundColor: '#EAF2FA',
    borderColor: '#ffffff',
    borderRadius: 19,
    borderWidth: 2,
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  adminAvatarText: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 15,
    includeFontPadding: false,
  },
  floatingBellButton: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: 'rgba(76, 94, 118, 0.12)',
    borderRadius: 19,
    borderWidth: 1,
    height: 38,
    justifyContent: 'center',
    position: 'relative',
    width: 38,
  },
  floatingBellDot: {
    backgroundColor: '#ED2314',
    borderColor: '#ffffff',
    borderRadius: 5,
    borderWidth: 1,
    height: 10,
    position: 'absolute',
    right: 7,
    top: 7,
    width: 10,
  },
  notificationPopover: {
    alignSelf: 'flex-end',
    backgroundColor: '#ffffff',
    borderColor: 'rgba(76, 94, 118, 0.14)',
    borderRadius: 14,
    borderWidth: 1,
    gap: 8,
    marginTop: -12,
    marginBottom: 16,
    padding: 12,
    width: 286,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 5,
  },
  notificationPopoverHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  notificationPopoverTitle: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 15,
    includeFontPadding: false,
  },
  notificationPopoverMeta: {
    color: '#ED2314',
    fontFamily: 'InterBold',
    fontSize: 11,
    includeFontPadding: false,
  },
  adminHero: {
    minHeight: 105,
    marginBottom: 18,
    overflow: 'hidden',
    position: 'relative',
  },
  heroDecorationOne: {
    position: 'absolute',
    right: 6,
    top: 0,
    width: 124,
    height: 74,
    borderRadius: 12,
    backgroundColor: 'rgba(138, 163, 195, 0.22)',
    transform: [{ rotate: '-16deg' }],
  },
  heroDecorationTwo: {
    position: 'absolute',
    right: 48,
    top: 28,
    width: 82,
    height: 58,
    borderRadius: 10,
    backgroundColor: 'rgba(20, 44, 76, 0.12)',
    transform: [{ rotate: '12deg' }],
  },
  adminGreeting: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 28,
    includeFontPadding: false,
    lineHeight: 35,
  },
  adminDate: {
    color: '#8AA3C3',
    fontFamily: 'InterBold',
    fontSize: 12,
    includeFontPadding: false,
    lineHeight: 17,
    marginTop: 6,
  },
  adminStatsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 26,
  },
  adminStatCard: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: 'rgba(76, 94, 118, 0.12)',
    borderRadius: 12,
    borderWidth: 1,
    minHeight: 112,
    paddingHorizontal: 5,
    paddingVertical: 10,
    width: '31.6%',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 2,
  },
  adminStatIconWrap: {
    alignItems: 'center',
    backgroundColor: '#F2F7FD',
    borderRadius: 11,
    height: 34,
    justifyContent: 'center',
    marginBottom: 8,
    width: 34,
  },
  adminStatValue: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 29,
    includeFontPadding: false,
    lineHeight: 34,
    textAlign: 'center',
  },
  adminStatLabel: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 10,
    includeFontPadding: false,
    lineHeight: 12,
    marginTop: 4,
    textAlign: 'center',
  },
  adminSectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  adminSectionTitle: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 19,
    includeFontPadding: false,
    lineHeight: 25,
  },
  viewAllButton: {
    paddingHorizontal: 4,
    paddingVertical: 4,
  },
  viewAllText: {
    color: '#4C77A5',
    fontFamily: 'InterBold',
    fontSize: 13,
    includeFontPadding: false,
  },
  adminListPanel: {
    gap: 10,
    marginBottom: 22,
  },
  adminAppointmentCard: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: 'rgba(76, 94, 118, 0.12)',
    borderRadius: 13,
    borderWidth: 1,
    flexDirection: 'row',
    minHeight: 74,
    paddingHorizontal: 10,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 5,
    elevation: 2,
  },
  appointmentThumb: {
    alignItems: 'center',
    backgroundColor: '#EAF2FA',
    borderRadius: 9,
    height: 56,
    justifyContent: 'center',
    marginRight: 12,
    width: 56,
  },
  appointmentCopy: {
    flex: 1,
    minWidth: 0,
  },
  appointmentTime: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 18,
    includeFontPadding: false,
    lineHeight: 22,
  },
  appointmentService: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 17,
    includeFontPadding: false,
    lineHeight: 22,
  },
  appointmentClient: {
    color: '#4C5E76',
    fontFamily: 'InterBold',
    fontSize: 12,
    includeFontPadding: false,
    lineHeight: 16,
  },
  appointmentBadge: {
    alignItems: 'center',
    borderRadius: 999,
    justifyContent: 'center',
    marginHorizontal: 8,
    minWidth: 70,
    paddingHorizontal: 9,
    paddingVertical: 6,
  },
  ongoingBadge: {
    backgroundColor: '#DDF5EC',
  },
  upcomingBadge: {
    backgroundColor: '#E4F0FF',
  },
  appointmentBadgeText: {
    fontFamily: 'InterBold',
    fontSize: 11,
    includeFontPadding: false,
  },
  ongoingText: {
    color: '#3D9D7A',
  },
  upcomingText: {
    color: '#4C8DEB',
  },
  adminNotificationCard: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: 'rgba(76, 94, 118, 0.12)',
    borderRadius: 13,
    borderWidth: 1,
    flexDirection: 'row',
    minHeight: 64,
    paddingHorizontal: 12,
  },
  readNotificationCard: {
    opacity: 0.72,
  },
  notificationUnreadDot: {
    backgroundColor: '#ED2314',
    borderRadius: 4,
    height: 8,
    marginLeft: 8,
    width: 8,
  },
  notificationIconWrap: {
    alignItems: 'center',
    backgroundColor: '#FFF1F1',
    borderRadius: 12,
    height: 42,
    justifyContent: 'center',
    marginRight: 12,
    width: 42,
  },
  notificationCopy: {
    flex: 1,
    minWidth: 0,
  },
  notificationTitle: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 14,
    includeFontPadding: false,
    lineHeight: 19,
  },
  notificationMeta: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 12,
    includeFontPadding: false,
    lineHeight: 17,
  },
  adminNotificationsBackground: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  adminNotificationsCamera: {
    height: 135,
    opacity: 0.42,
    position: 'absolute',
    right: -11,
    top: 49,
    width: 139,
  },
  adminNotificationsContent: {
    minHeight: '100%',
    paddingHorizontal: 16,
  },
  adminNotificationsCloseButton: {
    alignItems: 'center',
    alignSelf: 'flex-end',
    backgroundColor: '#142C4C',
    borderRadius: 15,
    height: 30,
    justifyContent: 'center',
    width: 30,
  },
  adminNotificationsHeader: {
    marginTop: 2,
    maxWidth: 230,
  },
  adminNotificationsTitle: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 28,
    includeFontPadding: false,
    lineHeight: 39,
  },
  adminNotificationsSubtitle: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 14,
    includeFontPadding: false,
    lineHeight: 19,
    marginTop: 2,
  },
  adminNotificationsFilters: {
    flexDirection: 'row',
    gap: 9,
    marginTop: 13,
  },
  adminNotificationsFilterChip: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 10,
    height: 32,
    justifyContent: 'center',
    paddingHorizontal: 7,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.22,
    shadowRadius: 4,
    elevation: 3,
  },
  activeAdminNotificationsFilterChip: {
    backgroundColor: '#142C4C',
    shadowOpacity: 0,
    elevation: 0,
  },
  adminNotificationsFilterText: {
    color: '#083979',
    fontFamily: 'Inter',
    fontSize: 14,
    includeFontPadding: false,
    lineHeight: 19,
  },
  activeAdminNotificationsFilterText: {
    color: '#ffffff',
  },
  adminNotificationsEmptyText: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 13,
    includeFontPadding: false,
    lineHeight: 19,
    marginTop: 22,
  },
  adminNotificationsGroup: {
    marginTop: 17,
  },
  adminNotificationsGroupHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingLeft: 8,
    paddingRight: 1,
  },
  adminNotificationsGroupTitle: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 20,
    includeFontPadding: false,
    lineHeight: 29,
  },
  adminNotificationsGroupDate: {
    color: '#62748C',
    fontFamily: 'Inter',
    fontSize: 12,
    includeFontPadding: false,
    lineHeight: 17,
  },
  adminNotificationsList: {
    gap: 8,
    marginTop: 8,
  },
  adminNotificationItemCard: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: 'rgba(20, 44, 76, 0.08)',
    borderRadius: 10,
    borderWidth: 1,
    flexDirection: 'row',
    minHeight: 91,
    paddingLeft: 9,
    paddingRight: 10,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.22,
    shadowRadius: 4,
    elevation: 3,
  },
  adminNotificationIconCircle: {
    alignItems: 'center',
    backgroundColor: '#FFD7DC',
    borderRadius: 36,
    height: 72,
    justifyContent: 'center',
    marginRight: 12,
    width: 72,
  },
  adminNotificationIconCircleBlue: {
    backgroundColor: '#DDEFFB',
  },
  adminNotificationIconCircleYellow: {
    backgroundColor: '#FBD17A',
  },
  adminNotificationItemCopy: {
    flex: 1,
    minWidth: 0,
  },
  adminNotificationItemTitle: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 14,
    includeFontPadding: false,
    lineHeight: 22,
  },
  adminNotificationItemMessage: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 11,
    includeFontPadding: false,
    lineHeight: 15,
    marginTop: 2,
  },
  adminNotificationTimeRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 4,
    marginTop: 2,
  },
  adminNotificationItemTime: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 11,
    includeFontPadding: false,
    lineHeight: 15,
  },
  adminNotificationUnreadDot: {
    backgroundColor: '#D3262C',
    borderRadius: 3.5,
    height: 7,
    marginHorizontal: 10,
    width: 7,
  },
  adminRequestContent: {
    paddingHorizontal: 18,
    paddingTop: 62,
  },
  adminCurvedHeaderScreen: {
    backgroundColor: '#142C4C',
  },
  adminBrandHeader: {
    alignItems: 'center',
    backgroundColor: '#142C4C',
    height: 156,
    justifyContent: 'flex-start',
    overflow: 'hidden',
    position: 'relative',
  },
  adminBrandHeaderAbsolute: {
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 3,
  },
  adminBrandHeaderElevated: {
    elevation: 3,
    zIndex: 3,
  },
  adminBrandHeaderTexture: {
    height: 156,
    left: 0,
    opacity: 0.5,
    position: 'absolute',
    top: 0,
    transform: [{ scaleX: -1 }],
    width: '100%',
  },
  adminBrandHeaderBackButton: {
    alignItems: 'center',
    height: 42,
    justifyContent: 'center',
    left: 25,
    position: 'absolute',
    top: 67,
    width: 42,
    zIndex: 2,
  },
  adminBrandHeaderBrand: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    marginTop: 60,
  },
  adminBrandHeaderBrandText: {
    color: '#ffffff',
    fontFamily: 'Jomolhari',
    fontSize: 28,
    includeFontPadding: false,
    lineHeight: 39,
  },
  adminBrandHeaderLogo: {
    height: 52,
    width: 62,
  },
  adminRequestsScreenContent: {
    backgroundColor: '#142C4C',
    flex: 1,
    minHeight: '100%',
    paddingHorizontal: 0,
  },
  adminRequestsHeroHeader: {
    alignItems: 'center',
    backgroundColor: '#142C4C',
    height: 156,
    justifyContent: 'flex-start',
    overflow: 'hidden',
    position: 'relative',
  },
  adminRequestsHeaderCamera: {
    height: 114,
    opacity: 0.2,
    position: 'absolute',
    right: -51,
    top: 32,
    width: 240,
  },
  adminRequestsHeaderBrand: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    marginTop: 60,
  },
  adminRequestsHeaderBrandText: {
    color: '#ffffff',
    fontFamily: 'Jomolhari',
    fontSize: 28,
    includeFontPadding: false,
    lineHeight: 39,
  },
  adminRequestsHeaderLogo: {
    height: 52,
    width: 62,
  },
  adminRequestsPanel: {
    backgroundColor: '#ffffff',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    flex: 1,
    marginTop: 0,
    overflow: 'hidden',
    paddingHorizontal: 20,
    paddingTop: 25,
    position: 'relative',
  },
  adminRequestsPanelBackground: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  adminRequestsTitle: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 28,
    includeFontPadding: false,
    lineHeight: 39,
  },
  adminRequestsSubtitle: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 15,
    includeFontPadding: false,
    lineHeight: 21,
    marginTop: 5,
  },
  adminRequestsFilterRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 15,
  },
  adminRequestsFilterPill: {
    alignItems: 'center',
    backgroundColor: '#CFDEF0',
    borderRadius: 10,
    flex: 1,
    height: 31,
    justifyContent: 'center',
    paddingHorizontal: 4,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.18,
    shadowRadius: 4,
    elevation: 2,
  },
  activeAdminRequestsFilterPill: {
    backgroundColor: '#142C4C',
    shadowOpacity: 0,
    elevation: 0,
  },
  adminRequestsFilterText: {
    color: '#142C4C',
    fontFamily: 'Inter',
    fontSize: 12,
    includeFontPadding: false,
    lineHeight: 17,
  },
  activeAdminRequestsFilterText: {
    color: '#ffffff',
  },
  adminRequestsSearchRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 5,
    marginTop: 7,
  },
  adminRequestsSearchBox: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: 'rgba(76, 94, 118, 0.5)',
    borderRadius: 10,
    borderWidth: 1,
    flex: 1,
    flexDirection: 'row',
    height: 45,
    paddingHorizontal: 14,
  },
  adminRequestsSearchInput: {
    color: '#142C4C',
    flex: 1,
    fontFamily: 'Inter',
    fontSize: 13,
    includeFontPadding: false,
    lineHeight: 18,
    paddingHorizontal: 12,
    paddingVertical: 0,
  },
  adminRequestsFilterButton: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: 'rgba(76, 94, 118, 0.5)',
    borderRadius: 13,
    borderWidth: 1.3,
    height: 45,
    justifyContent: 'center',
    width: 51,
  },
  activeAdminRequestsDateFilterButton: {
    backgroundColor: '#142C4C',
    borderColor: '#142C4C',
  },
  adminRequestsDateFilterScroller: {
    marginTop: 9,
    maxHeight: 34,
  },
  adminRequestsDateFilterRow: {
    gap: 8,
    paddingRight: 3,
  },
  adminRequestsDateFilterPill: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: 'rgba(76, 94, 118, 0.35)',
    borderRadius: 10,
    borderWidth: 1,
    height: 32,
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  activeAdminRequestsDateFilterPill: {
    backgroundColor: '#142C4C',
    borderColor: '#142C4C',
  },
  adminRequestsDateFilterText: {
    color: '#142C4C',
    fontFamily: 'Inter',
    fontSize: 12,
    includeFontPadding: false,
    lineHeight: 17,
  },
  activeAdminRequestsDateFilterText: {
    color: '#ffffff',
  },
  adminRequestsList: {
    gap: 3,
  },
  adminRequestsListScroller: {
    flex: 1,
    marginTop: 8,
  },
  adminRequestsEmptyText: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 13,
    includeFontPadding: false,
    lineHeight: 18,
    paddingHorizontal: 5,
    paddingVertical: 16,
  },
  adminRequestListCard: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: '#EAE3E2',
    borderRadius: 10,
    borderWidth: 1,
    flexDirection: 'row',
    height: 97,
    paddingLeft: 8,
    paddingRight: 9,
  },
  adminRequestListImage: {
    borderRadius: 10,
    height: 83,
    marginRight: 8,
    width: 83,
  },
  adminRequestListCopy: {
    flex: 1,
    minWidth: 0,
    paddingRight: 6,
  },
  adminRequestListName: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 15,
    includeFontPadding: false,
    lineHeight: 21,
  },
  adminRequestListPackage: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 13,
    includeFontPadding: false,
    lineHeight: 18,
    marginTop: 1,
  },
  adminRequestListDate: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 13,
    includeFontPadding: false,
    lineHeight: 18,
    marginTop: 4,
  },
  adminRequestStatusPill: {
    alignItems: 'center',
    borderRadius: 10,
    height: 26,
    justifyContent: 'center',
    marginRight: 7,
    paddingHorizontal: 10,
    minWidth: 68,
  },
  pendingRequestStatusPill: {
    backgroundColor: '#FDC860',
  },
  confirmedRequestStatusPill: {
    backgroundColor: '#DAF0ED',
  },
  rejectedRequestStatusPill: {
    backgroundColor: '#FFDADC',
  },
  adminRequestStatusText: {
    fontFamily: 'Inter',
    fontSize: 12,
    includeFontPadding: false,
    lineHeight: 16,
  },
  pendingRequestStatusText: {
    color: '#685123',
  },
  confirmedRequestStatusText: {
    color: '#23865E',
  },
  rejectedRequestStatusText: {
    color: '#A53E45',
  },
  adminPageTitle: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 30,
    includeFontPadding: false,
    lineHeight: 38,
  },
  adminPageSubtitle: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 14,
    includeFontPadding: false,
    lineHeight: 20,
    marginTop: 2,
  },
  requestFilterContent: {
    gap: 8,
    paddingVertical: 18,
  },
  requestFilterPill: {
    alignItems: 'center',
    backgroundColor: '#EAF2FA',
    borderRadius: 9,
    justifyContent: 'center',
    minHeight: 36,
    paddingHorizontal: 14,
  },
  activeRequestFilter: {
    backgroundColor: '#4C77A5',
  },
  requestFilterText: {
    color: '#4C5E76',
    fontFamily: 'InterBold',
    fontSize: 12,
    includeFontPadding: false,
  },
  activeRequestFilterText: {
    color: '#ffffff',
  },
  requestSearchRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    marginBottom: 18,
  },
  requestSearchBox: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: 'rgba(76, 94, 118, 0.2)',
    borderRadius: 10,
    borderWidth: 1,
    flex: 1,
    flexDirection: 'row',
    height: 50,
    paddingHorizontal: 12,
  },
  requestSearchInput: {
    color: '#142C4C',
    flex: 1,
    fontFamily: 'Inter',
    fontSize: 13,
    includeFontPadding: false,
    paddingHorizontal: 10,
    paddingVertical: 0,
  },
  requestFilterButton: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: 'rgba(76, 94, 118, 0.2)',
    borderRadius: 10,
    borderWidth: 1,
    height: 50,
    justifyContent: 'center',
    width: 50,
  },
  requestList: {
    gap: 10,
  },
  requestCard: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: 'rgba(76, 94, 118, 0.1)',
    borderRadius: 15,
    borderWidth: 1,
    flexDirection: 'row',
    minHeight: 84,
    paddingHorizontal: 11,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 2,
  },
  requestAvatar: {
    alignItems: 'center',
    backgroundColor: '#EAF2FA',
    borderRadius: 28,
    height: 56,
    justifyContent: 'center',
    marginRight: 13,
    width: 56,
  },
  requestAvatarText: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 26,
    includeFontPadding: false,
  },
  requestCopy: {
    flex: 1,
    minWidth: 0,
  },
  requestName: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 16,
    includeFontPadding: false,
    lineHeight: 21,
  },
  requestPackage: {
    color: '#4C5E76',
    fontFamily: 'InterBold',
    fontSize: 13,
    includeFontPadding: false,
    lineHeight: 18,
  },
  requestDate: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 12,
    includeFontPadding: false,
    lineHeight: 17,
  },
  pendingPill: {
    alignItems: 'center',
    backgroundColor: '#FFF1D8',
    borderRadius: 999,
    justifyContent: 'center',
    marginHorizontal: 8,
    minWidth: 76,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  pendingPillText: {
    color: '#F49A28',
    fontFamily: 'InterBold',
    fontSize: 12,
    includeFontPadding: false,
  },
  requestDetailContent: {
    paddingHorizontal: 22,
    paddingTop: 58,
  },
  adminBookingDetailContent: {
    backgroundColor: '#ffffff',
    minHeight: '100%',
    paddingHorizontal: 0,
  },
  adminBookingDetailScroller: {
    backgroundColor: '#ffffff',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    flex: 1,
    overflow: 'hidden',
  },
  adminBookingDetailHeader: {
    alignItems: 'center',
    backgroundColor: '#142C4C',
    height: 156,
    justifyContent: 'flex-start',
    overflow: 'hidden',
    position: 'relative',
  },
  adminBookingDetailHeaderCamera: {
    height: 171,
    opacity: 0.2,
    position: 'absolute',
    right: -34,
    top: -3,
    width: 304,
  },
  adminBookingDetailBackButton: {
    alignItems: 'center',
    height: 42,
    justifyContent: 'center',
    left: 25,
    position: 'absolute',
    top: 67,
    width: 42,
    zIndex: 2,
  },
  adminBookingDetailBrand: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    marginTop: 60,
  },
  adminBookingDetailBrandText: {
    color: '#ffffff',
    fontFamily: 'Jomolhari',
    fontSize: 28,
    includeFontPadding: false,
    lineHeight: 39,
  },
  adminBookingDetailBrandLogo: {
    height: 52,
    width: 62,
  },
  adminBookingDetailPanel: {
    backgroundColor: '#ffffff',
    flexGrow: 1,
    overflow: 'hidden',
    paddingHorizontal: 18,
    paddingTop: 18,
    position: 'relative',
  },
  adminBookingDetailBackground: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  adminBookingDetailLoading: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 14,
    includeFontPadding: false,
    lineHeight: 20,
    marginTop: 12,
  },
  adminBookingDetailStatusPill: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    borderRadius: 12,
    flexDirection: 'row',
    gap: 6,
    height: 37,
    justifyContent: 'center',
    marginLeft: 4,
    minWidth: 118,
    paddingHorizontal: 14,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.22,
    shadowRadius: 4,
    elevation: 4,
  },
  adminBookingDetailPendingPill: {
    backgroundColor: '#FFEDCF',
  },
  adminBookingDetailConfirmedPill: {
    backgroundColor: '#DAF0ED',
  },
  adminBookingDetailRejectedPill: {
    backgroundColor: '#F5E8E8',
  },
  adminBookingDetailStatusText: {
    fontFamily: 'Jomolhari',
    fontSize: 16,
    includeFontPadding: false,
    lineHeight: 22,
  },
  adminBookingDetailPendingText: {
    color: '#FF7E00',
  },
  adminBookingDetailConfirmedText: {
    color: '#23865E',
  },
  adminBookingDetailRejectedText: {
    color: '#E00000',
  },
  adminBookingDetailClientBlock: {
    minHeight: 96,
    marginTop: 14,
    position: 'relative',
  },
  adminBookingDetailAvatar: {
    borderRadius: 46,
    height: 92,
    left: 0,
    overflow: 'hidden',
    position: 'absolute',
    top: 0,
    width: 92,
  },
  adminBookingDetailClientCopy: {
    marginLeft: 106,
    paddingRight: 0,
    paddingTop: 4,
  },
  adminBookingDetailClientName: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 22,
    includeFontPadding: false,
    lineHeight: 32,
  },
  adminBookingDetailContactRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    marginTop: 4,
  },
  adminBookingDetailContactText: {
    color: '#4C5E76',
    flex: 1,
    fontFamily: 'Inter',
    fontSize: 15,
    includeFontPadding: false,
    lineHeight: 21,
  },
  adminBookingDetailSectionTitle: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 20,
    includeFontPadding: false,
    lineHeight: 29,
    marginTop: 12,
  },
  adminBookingDetailServiceCard: {
    backgroundColor: '#ffffff',
    borderColor: 'rgba(138, 163, 195, 0.24)',
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: 'row',
    marginTop: 6,
    minHeight: 136,
    padding: 10,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 3,
  },
  adminBookingDetailServiceImage: {
    borderRadius: 10,
    height: 116,
    width: 104,
  },
  adminBookingDetailServiceCopy: {
    flex: 1,
    minWidth: 0,
    paddingLeft: 10,
    paddingTop: 2,
  },
  adminBookingDetailServiceTitle: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 14,
    includeFontPadding: false,
    lineHeight: 21,
  },
  adminBookingDetailServicePrice: {
    color: '#70A2E3',
    fontFamily: 'InterBold',
    fontSize: 15,
    includeFontPadding: false,
    lineHeight: 22,
    marginTop: 1,
  },
  adminBookingDetailInclusionRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
    marginTop: 3,
  },
  adminBookingDetailInclusionText: {
    color: '#395276',
    flex: 1,
    fontFamily: 'Inter',
    fontSize: 11,
    includeFontPadding: false,
    lineHeight: 15,
  },
  adminBookingDetailDateTimeRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 6,
  },
  adminBookingDetailDateTimeCard: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: 'rgba(138, 163, 195, 0.55)',
    borderRadius: 11,
    borderWidth: 1,
    flex: 1,
    flexDirection: 'row',
    gap: 7,
    minHeight: 54,
    paddingHorizontal: 9,
    paddingVertical: 8,
  },
  adminBookingDetailDateTimeCopy: {
    flex: 1,
    minWidth: 0,
  },
  adminBookingDetailDateTimePrimary: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 11,
    includeFontPadding: false,
    lineHeight: 15,
  },
  adminBookingDetailDateTimeSecondary: {
    color: '#8AA3C3',
    fontFamily: 'InterBold',
    fontSize: 10,
    includeFontPadding: false,
    lineHeight: 14,
    marginTop: 2,
  },
  adminBookingDetailNotesBox: {
    alignItems: 'flex-start',
    backgroundColor: '#EAF4FF',
    borderRadius: 12,
    flexDirection: 'row',
    gap: 12,
    marginTop: 6,
    minHeight: 76,
    paddingHorizontal: 16,
    paddingVertical: 16,
  },
  adminBookingDetailNotesText: {
    color: '#395276',
    flex: 1,
    fontFamily: 'Inter',
    fontSize: 14,
    includeFontPadding: false,
    lineHeight: 19,
  },
  adminBookingDetailMetaPanel: {
    backgroundColor: 'rgba(255, 255, 255, 0.82)',
    borderColor: 'rgba(138, 163, 195, 0.35)',
    borderRadius: 10,
    borderWidth: 1,
    marginTop: 8,
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 6,
  },
  adminBookingDetailMetaRow: {
    marginBottom: 8,
  },
  adminBookingDetailMetaLabel: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 12,
    includeFontPadding: false,
    lineHeight: 16,
  },
  adminBookingDetailMetaValue: {
    color: '#395276',
    fontFamily: 'Inter',
    fontSize: 13,
    includeFontPadding: false,
    lineHeight: 18,
    marginTop: 2,
  },
  adminBookingDetailActionRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 14,
  },
  adminBookingDetailRejectButton: {
    alignItems: 'center',
    backgroundColor: '#F5E8E8',
    borderColor: '#FF0000',
    borderRadius: 10,
    borderWidth: 1,
    flex: 1,
    flexDirection: 'row',
    gap: 7,
    minHeight: 50,
    paddingHorizontal: 10,
    justifyContent: 'center',
  },
  adminBookingDetailRejectText: {
    color: '#FF0000',
    fontFamily: 'Inter',
    fontSize: 13,
    includeFontPadding: false,
    lineHeight: 21,
  },
  adminBookingDetailConfirmButton: {
    alignItems: 'center',
    backgroundColor: '#083979',
    borderRadius: 10,
    flex: 1,
    flexDirection: 'row',
    gap: 7,
    minHeight: 50,
    paddingHorizontal: 10,
    justifyContent: 'center',
  },
  adminBookingDetailConfirmText: {
    color: '#ffffff',
    fontFamily: 'Inter',
    fontSize: 13,
    includeFontPadding: false,
    lineHeight: 21,
  },
  bookingDecisionModalOverlay: {
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.45)',
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 38,
  },
  bookingDecisionModalCard: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 30,
    minHeight: 340,
    paddingBottom: 34,
    paddingHorizontal: 31,
    paddingTop: 30,
    position: 'relative',
    width: '100%',
  },
  bookingDecisionModalClose: {
    alignItems: 'center',
    height: 42,
    justifyContent: 'center',
    position: 'absolute',
    right: 19,
    top: 17,
    width: 42,
    zIndex: 2,
  },
  bookingDecisionSuccessIconWrap: {
    alignItems: 'center',
    backgroundColor: '#142C4C',
    borderColor: '#8AA3C3',
    borderRadius: 50,
    borderWidth: 7,
    height: 100,
    justifyContent: 'center',
    width: 100,
  },
  bookingDecisionWarningIconWrap: {
    alignItems: 'center',
    backgroundColor: '#F5E1E1',
    borderRadius: 50,
    height: 100,
    justifyContent: 'center',
    width: 100,
  },
  bookingDecisionModalTitle: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 20,
    includeFontPadding: false,
    lineHeight: 29,
    marginTop: 16,
    textAlign: 'center',
  },
  bookingDecisionModalMessage: {
    color: '#4C5E76',
    fontFamily: 'InterBold',
    fontSize: 16,
    includeFontPadding: false,
    lineHeight: 20,
    marginTop: 20,
    textAlign: 'center',
  },
  bookingDecisionOkButton: {
    alignItems: 'center',
    backgroundColor: '#142C4C',
    borderRadius: 15,
    height: 48,
    justifyContent: 'center',
    marginTop: 25,
    width: '100%',
  },
  bookingDecisionOkText: {
    color: '#ffffff',
    fontFamily: 'InterBold',
    fontSize: 20,
    includeFontPadding: false,
    lineHeight: 25,
  },
  bookingDecisionReasonInput: {
    backgroundColor: '#F6FAFF',
    borderColor: 'rgba(76, 94, 118, 0.24)',
    borderRadius: 12,
    borderWidth: 1,
    color: '#142C4C',
    fontFamily: 'Inter',
    fontSize: 13,
    includeFontPadding: false,
    marginTop: 14,
    minHeight: 66,
    paddingHorizontal: 12,
    paddingVertical: 9,
    textAlignVertical: 'top',
    width: '100%',
  },
  bookingDecisionModalActions: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 14,
    width: '100%',
  },
  bookingDecisionCancelButton: {
    alignItems: 'center',
    backgroundColor: '#D1DAEA',
    borderRadius: 15,
    flex: 1,
    height: 48,
    justifyContent: 'center',
  },
  bookingDecisionCancelText: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 20,
    includeFontPadding: false,
    lineHeight: 25,
  },
  bookingDecisionRejectButton: {
    alignItems: 'center',
    backgroundColor: '#B32B2B',
    borderRadius: 15,
    flex: 1,
    height: 48,
    justifyContent: 'center',
  },
  bookingDecisionRejectText: {
    color: '#ffffff',
    fontFamily: 'InterBold',
    fontSize: 20,
    includeFontPadding: false,
    lineHeight: 25,
  },
  detailTopBar: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 22,
  },
  detailIconButton: {
    alignItems: 'center',
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  detailBrand: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  detailBrandText: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 24,
    includeFontPadding: false,
    lineHeight: 35,
  },
  detailPendingPill: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: '#FFF1D8',
    borderRadius: 999,
    marginBottom: 18,
    paddingHorizontal: 18,
    paddingVertical: 7,
  },
  detailConfirmedPill: {
    backgroundColor: '#DDF4EC',
  },
  detailRejectedPill: {
    backgroundColor: '#FFE3E4',
  },
  detailPendingText: {
    color: '#F49A28',
    fontFamily: 'InterBold',
    fontSize: 13,
    includeFontPadding: false,
  },
  detailConfirmedText: {
    color: '#2D8F78',
  },
  detailRejectedText: {
    color: '#E45F62',
  },
  clientHeaderRow: {
    alignItems: 'center',
    flexDirection: 'row',
    marginBottom: 22,
  },
  detailAvatar: {
    alignItems: 'center',
    backgroundColor: '#EAF2FA',
    borderRadius: 35,
    height: 70,
    justifyContent: 'center',
    marginRight: 18,
    width: 70,
  },
  detailAvatarText: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 34,
    includeFontPadding: false,
  },
  clientInfo: {
    flex: 1,
  },
  clientName: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 19,
    includeFontPadding: false,
    lineHeight: 25,
    marginBottom: 6,
  },
  clientInfoRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 9,
    marginTop: 3,
  },
  clientMeta: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 13,
    includeFontPadding: false,
    lineHeight: 18,
  },
  detailSectionTitle: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 17,
    includeFontPadding: false,
    lineHeight: 23,
    marginBottom: 10,
    marginTop: 8,
  },
  serviceDetailRow: {
    flexDirection: 'row',
    marginBottom: 16,
  },
  serviceImagePlaceholder: {
    alignItems: 'center',
    backgroundColor: '#EAF2FA',
    borderRadius: 10,
    height: 106,
    justifyContent: 'center',
    marginRight: 16,
    width: 106,
  },
  serviceDetailCopy: {
    flex: 1,
  },
  serviceDetailTitle: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 20,
    includeFontPadding: false,
    lineHeight: 26,
  },
  serviceDetailPrice: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 18,
    includeFontPadding: false,
    lineHeight: 23,
    marginBottom: 5,
  },
  serviceBullet: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 12,
    includeFontPadding: false,
    lineHeight: 17,
  },
  dateTimeRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 16,
  },
  dateTimePill: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: 'rgba(76, 94, 118, 0.18)',
    borderRadius: 10,
    borderWidth: 1,
    flex: 1,
    flexDirection: 'row',
    gap: 7,
    minHeight: 50,
    paddingHorizontal: 10,
  },
  dateTimeText: {
    color: '#4C5E76',
    flexShrink: 1,
    fontFamily: 'InterBold',
    fontSize: 12,
    includeFontPadding: false,
    lineHeight: 17,
  },
  notesBox: {
    backgroundColor: '#EAF4FF',
    borderRadius: 12,
    marginBottom: 20,
    padding: 18,
  },
  sessionDetailBlock: {
    marginTop: 8,
  },
  sessionDetailLabel: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 12,
    includeFontPadding: false,
    lineHeight: 17,
    marginBottom: 3,
  },
  sessionDetailRow: {
    marginBottom: 11,
  },
  sessionDetailValue: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 14,
    includeFontPadding: false,
    lineHeight: 20,
  },
  notesText: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 14,
    includeFontPadding: false,
    lineHeight: 21,
  },
  detailActionRow: {
    flexDirection: 'row',
    gap: 12,
  },
  rejectButton: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: '#F37C7E',
    borderRadius: 14,
    borderWidth: 1.5,
    flex: 1,
    height: 58,
    justifyContent: 'center',
  },
  rejectButtonText: {
    color: '#E45F62',
    fontFamily: 'InterBold',
    fontSize: 14,
    includeFontPadding: false,
  },
  confirmButton: {
    alignItems: 'center',
    backgroundColor: '#142C4C',
    borderRadius: 14,
    flex: 1,
    height: 58,
    justifyContent: 'center',
  },
  confirmButtonText: {
    color: '#ffffff',
    fontFamily: 'InterBold',
    fontSize: 14,
    includeFontPadding: false,
  },
  resolvedRequestPanel: {
    backgroundColor: '#ffffff',
    borderColor: 'rgba(76, 94, 118, 0.14)',
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 16,
    paddingVertical: 15,
  },
  resolvedRequestTitle: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 15,
    includeFontPadding: false,
    lineHeight: 21,
  },
  resolvedRequestText: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 13,
    includeFontPadding: false,
    lineHeight: 19,
    marginTop: 5,
  },
  rejectionReasonBox: {
    backgroundColor: '#FFF6F6',
    borderColor: 'rgba(228, 95, 98, 0.18)',
    borderRadius: 12,
    borderWidth: 1,
    marginTop: 12,
    padding: 12,
  },
  rejectionReasonLabel: {
    color: '#E45F62',
    fontFamily: 'InterBold',
    fontSize: 12,
    includeFontPadding: false,
    lineHeight: 16,
  },
  rejectionReasonText: {
    color: '#142C4C',
    fontFamily: 'Inter',
    fontSize: 13,
    includeFontPadding: false,
    lineHeight: 18,
    marginTop: 4,
  },
  rejectModalOverlay: {
    alignItems: 'center',
    backgroundColor: 'rgba(20, 44, 76, 0.38)',
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 22,
  },
  rejectModalCard: {
    backgroundColor: '#F3EEEE',
    borderRadius: 18,
    padding: 18,
    width: '100%',
  },
  rejectModalTitle: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 24,
    includeFontPadding: false,
    lineHeight: 34,
  },
  rejectModalMessage: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 13,
    includeFontPadding: false,
    lineHeight: 19,
    marginTop: 4,
  },
  rejectReasonInput: {
    backgroundColor: '#ffffff',
    borderColor: 'rgba(76, 94, 118, 0.22)',
    borderRadius: 12,
    borderWidth: 1,
    color: '#142C4C',
    fontFamily: 'Inter',
    fontSize: 14,
    includeFontPadding: false,
    marginTop: 14,
    minHeight: 106,
    paddingHorizontal: 12,
    paddingVertical: 10,
    textAlignVertical: 'top',
  },
  rejectModalActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 14,
  },
  rejectModalCancelButton: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: 'rgba(76, 94, 118, 0.22)',
    borderRadius: 12,
    borderWidth: 1,
    flex: 1,
    height: 50,
    justifyContent: 'center',
  },
  rejectModalCancelText: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 14,
    includeFontPadding: false,
  },
  rejectModalSubmitButton: {
    alignItems: 'center',
    backgroundColor: '#E45F62',
    borderRadius: 12,
    flex: 1,
    height: 50,
    justifyContent: 'center',
  },
  rejectModalSubmitText: {
    color: '#ffffff',
    fontFamily: 'InterBold',
    fontSize: 14,
    includeFontPadding: false,
  },
  manageDateScreen: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  manageDateContent: {
    minHeight: '100%',
    paddingHorizontal: 20,
  },
  manageDateHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    height: 95,
    justifyContent: 'center',
    position: 'relative',
  },
  manageDateBackButton: {
    alignItems: 'center',
    height: 35,
    justifyContent: 'center',
    left: 0,
    position: 'absolute',
    top: 35,
    width: 35,
  },
  manageDateTitle: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 24,
    includeFontPadding: false,
    lineHeight: 34,
    marginTop: 22,
  },
  manageDateCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.7)',
    borderColor: 'rgba(138, 163, 195, 0.16)',
    borderRadius: 30,
    borderWidth: 1,
    marginHorizontal: 9,
    minHeight: 740,
    paddingBottom: 22,
    paddingHorizontal: 17,
    paddingTop: 23,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.22,
    shadowRadius: 4,
    elevation: 3,
  },
  manageDateLabel: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 20,
    includeFontPadding: false,
    lineHeight: 25,
    marginLeft: 9,
  },
  manageDateInput: {
    alignItems: 'center',
    backgroundColor: '#FAFBFE',
    borderColor: 'rgba(138, 163, 195, 0.25)',
    borderRadius: 15,
    borderWidth: 1,
    flexDirection: 'row',
    height: 56,
    justifyContent: 'space-between',
    marginTop: 8,
    paddingLeft: 14,
    paddingRight: 17,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  manageDateInputText: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 20,
    includeFontPadding: false,
    lineHeight: 29,
  },
  manageDateSectionLabel: {
    color: '#142C4C',
    fontFamily: 'InterSemiBold',
    fontSize: 20,
    includeFontPadding: false,
    lineHeight: 25,
  },
  manageStatusOptions: {
    gap: 7,
    marginTop: 5,
  },
  manageTimeSlotsHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 25,
  },
  manageAddTimeButton: {
    alignItems: 'center',
    backgroundColor: '#122D48',
    borderRadius: 20,
    height: 38,
    justifyContent: 'center',
    minWidth: 146,
    paddingHorizontal: 8,
  },
  manageAddTimeText: {
    color: '#ffffff',
    fontFamily: 'InterMedium',
    fontSize: 16,
    includeFontPadding: false,
    lineHeight: 20,
  },
  manageSlotList: {
    gap: 13,
    marginTop: 25,
  },
  manageSlotCard: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: 'rgba(138, 163, 195, 0.14)',
    borderRadius: 15,
    flexDirection: 'row',
    minHeight: 74,
    paddingLeft: 13,
    paddingRight: 17,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.22,
    shadowRadius: 4,
    elevation: 3,
  },
  manageSlotTime: {
    color: '#142C4C',
    flex: 1,
    fontFamily: 'InterMedium',
    fontSize: 16,
    includeFontPadding: false,
    lineHeight: 20,
    marginLeft: 11,
  },
  manageSlotActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 13,
  },
  manageSaveButton: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: '#122D48',
    borderRadius: 15,
    height: 51,
    justifyContent: 'center',
    marginTop: 13,
    width: 303,
  },
  manageSaveText: {
    color: '#ffffff',
    fontFamily: 'Jomolhari',
    fontSize: 20,
    includeFontPadding: false,
    lineHeight: 28,
  },
  timeEntryOverlay: {
    alignItems: 'center',
    backgroundColor: 'rgba(20, 44, 76, 0.28)',
    bottom: 0,
    justifyContent: 'center',
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 20,
  },
  timeEntryCard: {
    backgroundColor: '#ffffff',
    borderRadius: 30,
    minHeight: 388,
    paddingBottom: 43,
    paddingHorizontal: 30,
    paddingTop: 23,
    width: 334,
  },
  timeEntryHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  timeEntryTitle: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 20,
    includeFontPadding: false,
    lineHeight: 29,
  },
  timeEntryCloseButton: {
    alignItems: 'center',
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  timeEntryFields: {
    gap: 17,
    marginTop: 23,
  },
  timeEntryField: {
    width: '100%',
  },
  timeEntryLabel: {
    color: '#142C4C',
    fontSize: 16,
    lineHeight: 20,
    marginBottom: 9,
  },
  timeEntryActions: {
    flexDirection: 'row',
    gap: 21,
    marginTop: 34,
    paddingHorizontal: 2,
  },
  timeEntryCancelButton: {
    alignItems: 'center',
    backgroundColor: '#D5DDEB',
    borderRadius: 15,
    flex: 1,
    height: 48,
    justifyContent: 'center',
  },
  timeEntryCancelText: {
    color: '#142C4C',
    fontFamily: 'Inter',
    fontSize: 16,
    includeFontPadding: false,
    lineHeight: 20,
  },
  timeEntrySubmitButton: {
    alignItems: 'center',
    backgroundColor: '#142C4C',
    borderRadius: 15,
    flex: 1,
    height: 48,
    justifyContent: 'center',
  },
  timeEntrySubmitText: {
    color: '#ffffff',
    fontFamily: 'Inter',
    fontSize: 16,
    includeFontPadding: false,
    lineHeight: 20,
  },
  deleteTimeSlotOverlay: {
    alignItems: 'center',
    backgroundColor: 'rgba(20, 44, 76, 0.28)',
    bottom: 0,
    justifyContent: 'center',
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 30,
  },
  deleteTimeSlotCard: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 30,
    minHeight: 341,
    paddingBottom: 47,
    paddingHorizontal: 32,
    paddingTop: 30,
    position: 'relative',
    width: 334,
  },
  deleteTimeSlotCloseButton: {
    alignItems: 'center',
    height: 34,
    justifyContent: 'center',
    position: 'absolute',
    right: 19,
    top: 21,
    width: 34,
  },
  deleteTimeSlotTitle: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 20,
    includeFontPadding: false,
    lineHeight: 29,
    marginTop: 30,
    textAlign: 'center',
  },
  deleteTimeSlotMessage: {
    color: '#4C5E76',
    fontFamily: 'InterMedium',
    fontSize: 16,
    includeFontPadding: false,
    lineHeight: 21,
    marginTop: 11,
    textAlign: 'center',
    width: 235,
  },
  deleteTimeSlotActions: {
    flexDirection: 'row',
    gap: 7,
    marginTop: 22,
  },
  deleteTimeSlotCancelButton: {
    alignItems: 'center',
    backgroundColor: '#D1DAEA',
    borderRadius: 15,
    height: 48,
    justifyContent: 'center',
    width: 123,
  },
  deleteTimeSlotCancelText: {
    color: '#142C4C',
    fontFamily: 'InterMedium',
    fontSize: 20,
    includeFontPadding: false,
    lineHeight: 24,
  },
  deleteTimeSlotDeleteButton: {
    alignItems: 'center',
    backgroundColor: '#B32B2B',
    borderRadius: 15,
    height: 48,
    justifyContent: 'center',
    width: 123,
  },
  deleteTimeSlotDeleteText: {
    color: '#ffffff',
    fontFamily: 'InterMedium',
    fontSize: 20,
    includeFontPadding: false,
    lineHeight: 24,
  },
  timeSlotNoticeOkButton: {
    alignItems: 'center',
    backgroundColor: '#142C4C',
    borderRadius: 15,
    height: 48,
    justifyContent: 'center',
    width: 170,
  },
  timeSlotNoticeOkText: {
    color: '#ffffff',
    fontFamily: 'InterMedium',
    fontSize: 20,
    includeFontPadding: false,
    lineHeight: 24,
  },
  adminCalendarHero: {
    alignItems: 'center',
    backgroundColor: '#142C4C',
    height: 156,
    justifyContent: 'flex-start',
    overflow: 'hidden',
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    zIndex: 3,
    elevation: 3,
  },
  adminCalendarHeroTexture: {
    height: 156,
    left: 0,
    opacity: 0.5,
    position: 'absolute',
    top: 0,
    transform: [{ scaleX: -1 }],
    width: '100%',
  },
  adminCalendarBrand: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    marginTop: 60,
  },
  adminCalendarBrandText: {
    color: '#ffffff',
    fontFamily: 'Jomolhari',
    fontSize: 28,
    includeFontPadding: false,
    lineHeight: 39,
  },
  adminCalendarBrandLogo: {
    height: 52,
    width: 62,
  },
  adminCalendarSurface: {
    backgroundColor: '#ffffff',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    flex: 1,
    overflow: 'hidden',
    position: 'relative',
  },
  adminCalendarBackground: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  adminCalendarContent: {
    paddingHorizontal: 18,
    paddingTop: 17,
  },
  calendarHeaderRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 29,
  },
  calendarMonthCard: {
    backgroundColor: '#ffffff',
    borderColor: 'rgba(76, 94, 118, 0.18)',
    borderRadius: 13,
    borderWidth: 1,
    overflow: 'hidden',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.16,
    shadowRadius: 8,
    elevation: 4,
  },
  calendarMonthHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    height: 77,
    justifyContent: 'space-between',
    paddingHorizontal: 25,
  },
  calendarArrowButton: {
    alignItems: 'center',
    height: 36,
    justifyContent: 'center',
    width: 32,
  },
  calendarPickerGroup: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 9,
  },
  calendarPickerPill: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: 'rgba(76, 94, 118, 0.25)',
    borderRadius: 9,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    height: 35,
    justifyContent: 'center',
    minWidth: 86,
    paddingHorizontal: 9,
  },
  calendarMonthText: {
    color: '#142C4C',
    fontFamily: 'Inter',
    fontSize: 20,
    includeFontPadding: false,
    lineHeight: 25,
  },
  calendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingBottom: 18,
    paddingHorizontal: 24,
  },
  calendarWeekText: {
    color: '#7A7A7A',
    fontFamily: 'Inter',
    fontSize: 14,
    includeFontPadding: false,
    lineHeight: 31,
    marginBottom: 2,
    textAlign: 'center',
    width: `${100 / 7}%`,
  },
  calendarDayCell: {
    alignItems: 'center',
    height: 50,
    justifyContent: 'center',
    marginVertical: 0,
    width: `${100 / 7}%`,
  },
  selectedCalendarDay: {
    backgroundColor: '#D1E0F0',
    borderRadius: 9,
  },
  calendarDayText: {
    color: '#222222',
    fontFamily: 'Inter',
    fontSize: 20,
    includeFontPadding: false,
    lineHeight: 26,
  },
  selectedDayText: {
    color: '#142C4C',
  },
  outsideCalendarDayText: {
    color: '#B8B8B8',
  },
  availableDayText: {
    color: '#009D74',
  },
  bookedDayText: {
    color: '#3B70D5',
  },
  unavailableDayText: {
    color: '#FF344B',
  },
  calendarDots: {
    flexDirection: 'row',
    gap: 3,
    height: 5,
    marginTop: 0,
  },
  calendarDot: {
    borderRadius: 2,
    height: 4,
    width: 4,
  },
  availableDot: {
    backgroundColor: '#19B18A',
  },
  bookedDot: {
    backgroundColor: '#3B70D5',
  },
  unavailableDot: {
    backgroundColor: '#F04B5E',
  },
  calendarLegendRow: {
    alignItems: 'flex-start',
    backgroundColor: '#ffffff',
    borderColor: 'rgba(76, 94, 118, 0.06)',
    borderRadius: 18,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'space-between',
    marginTop: 19,
    paddingHorizontal: 14,
    paddingVertical: 28,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.22,
    shadowRadius: 7,
    elevation: 5,
  },
  legendItem: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    flex: 1,
    gap: 5,
  },
  legendDot: {
    borderRadius: 8,
    height: 16,
    marginTop: 2,
    width: 16,
  },
  legendCopy: {
    flex: 1,
    minWidth: 0,
  },
  legendText: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 16,
    includeFontPadding: false,
    lineHeight: 20,
  },
  legendSubtext: {
    color: '#142C4C',
    fontFamily: 'Inter',
    fontSize: 11,
    includeFontPadding: false,
    lineHeight: 15,
    marginTop: 6,
  },
  viewTimeSlotsButton: {
    alignItems: 'center',
    backgroundColor: '#142C4C',
    borderRadius: 15,
    height: 62,
    justifyContent: 'center',
    marginTop: 20,
    width: '100%',
  },
  viewTimeSlotsText: {
    color: '#ffffff',
    fontFamily: 'Jomolhari',
    fontSize: 25,
    includeFontPadding: false,
    lineHeight: 34,
  },
  timeSlotBackButton: {
    alignItems: 'center',
    height: 42,
    justifyContent: 'center',
    left: 24,
    position: 'absolute',
    top: 67,
    width: 42,
    zIndex: 4,
  },
  timeSlotFigmaBackground: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  timeSlotFigmaContent: {
    alignSelf: 'center',
    minHeight: '100%',
    paddingHorizontal: 16,
    width: '100%',
  },
  figmaDateHeaderRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 18,
    marginTop: 0,
  },
  figmaBackButton: {
    alignItems: 'center',
    height: 35,
    justifyContent: 'center',
    width: 35,
  },
  figmaDatePill: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: 'rgba(138, 163, 195, 0.2)',
    borderRadius: 18,
    flexDirection: 'row',
    gap: 10,
    height: 56,
    justifyContent: 'center',
    width: 284,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.18,
    shadowRadius: 4,
    elevation: 3,
  },
  figmaDatePillText: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 20,
    includeFontPadding: false,
    lineHeight: 29,
  },
  figmaSlotLegend: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 47,
    justifyContent: 'center',
    marginTop: 21,
  },
  figmaLegendItem: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  figmaLegendDot: {
    borderRadius: 8,
    height: 15,
    width: 15,
  },
  figmaAvailableDot: {
    backgroundColor: '#0AB543',
  },
  figmaBookedDot: {
    backgroundColor: '#083979',
  },
  figmaUnavailableDot: {
    backgroundColor: '#F04B5E',
  },
  figmaLegendText: {
    color: '#142C4C',
    fontFamily: 'Inter',
    fontSize: 16,
    includeFontPadding: false,
    lineHeight: 20,
  },
  figmaTimeSlotHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 32,
  },
  figmaTimeSlotTitle: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 24,
    includeFontPadding: false,
    lineHeight: 34,
  },
  figmaEditButton: {
    alignItems: 'center',
    backgroundColor: '#122D48',
    borderRadius: 20,
    flexDirection: 'row',
    gap: 8,
    height: 42,
    justifyContent: 'center',
    width: 144,
  },
  figmaEditButtonText: {
    color: '#ffffff',
    fontFamily: 'Jomolhari',
    fontSize: 20,
    includeFontPadding: false,
    lineHeight: 28,
  },
  figmaTimeSlotList: {
    gap: 14,
    marginTop: 18,
  },
  figmaSlotCard: {
    backgroundColor: '#ffffff',
    borderColor: 'rgba(138, 163, 195, 0.16)',
    borderRadius: 15,
    minHeight: 74,
    paddingHorizontal: 10,
    paddingVertical: 13,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  figmaSlotCardTop: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 9,
  },
  figmaSlotCopy: {
    flex: 1,
    minWidth: 0,
  },
  figmaSlotTime: {
    color: '#142C4C',
    fontFamily: 'InterMedium',
    fontSize: 16,
    includeFontPadding: false,
    lineHeight: 20,
  },
  figmaSlotDuration: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 14,
    includeFontPadding: false,
    lineHeight: 17,
    marginTop: 2,
  },
  figmaStatusPill: {
    alignItems: 'center',
    borderRadius: 20,
    flexDirection: 'row',
    gap: 9,
    justifyContent: 'center',
    minHeight: 37,
    minWidth: 130,
    paddingHorizontal: 14,
  },
  figmaStatusPillDot: {
    borderRadius: 8,
    height: 15,
    width: 15,
  },
  figmaStatusPillText: {
    fontFamily: 'InterMedium',
    fontSize: 16,
    includeFontPadding: false,
    lineHeight: 20,
  },
  figmaBookedInfoBox: {
    backgroundColor: '#E4EEFC',
    borderRadius: 10,
    marginLeft: 14,
    marginRight: 6,
    marginTop: 14,
    minHeight: 52,
    paddingHorizontal: 27,
    paddingVertical: 8,
  },
  figmaBookedClient: {
    color: '#142C4C',
    fontFamily: 'InterMedium',
    fontSize: 16,
    includeFontPadding: false,
    lineHeight: 20,
  },
  figmaBookedPackage: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 14,
    includeFontPadding: false,
    lineHeight: 17,
  },
  timeSlotManageSheetList: {
    gap: 10,
    marginTop: 14,
    maxHeight: 280,
  },
  timeSlotScreenContent: {
    minHeight: '100%',
    paddingHorizontal: 18,
    paddingTop: 177,
  },
  dayAvailabilityCard: {
    backgroundColor: '#ffffff',
    borderColor: 'rgba(76, 94, 118, 0.12)',
    borderRadius: 16,
    borderWidth: 1,
    marginTop: 22,
    padding: 16,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.14,
    shadowRadius: 8,
    elevation: 4,
  },
  dayAvailabilityHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  dayAvailabilityTitle: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 16,
    includeFontPadding: false,
    lineHeight: 22,
  },
  dayAvailabilityMeta: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 12,
    includeFontPadding: false,
    lineHeight: 17,
  },
  dayAvailabilityOptions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 14,
  },
  dayAvailabilityOption: {
    alignItems: 'center',
    backgroundColor: 'transparent',
    borderColor: 'transparent',
    borderRadius: 0,
    borderWidth: 0,
    flexDirection: 'row',
    gap: 21,
    minHeight: 33,
    paddingHorizontal: 15,
    width: 230,
  },
  activeAvailableOption: {
    backgroundColor: 'transparent',
    borderColor: 'transparent',
  },
  activeUnavailableOption: {
    backgroundColor: 'transparent',
    borderColor: 'transparent',
  },
  radioOuter: {
    alignItems: 'center',
    borderColor: '#142C4C',
    borderRadius: 12,
    borderWidth: 1,
    height: 24,
    justifyContent: 'center',
    width: 24,
  },
  availableRadioOuter: {
    backgroundColor: '#142C4C',
    borderColor: '#142C4C',
  },
  unavailableRadioOuter: {
    backgroundColor: '#142C4C',
    borderColor: '#142C4C',
  },
  radioInner: {
    backgroundColor: '#ffffff',
    borderRadius: 4,
    height: 8,
    width: 8,
  },
  availableRadioInner: {
    backgroundColor: '#ffffff',
  },
  unavailableRadioInner: {
    backgroundColor: '#ffffff',
  },
  dayAvailabilityOptionText: {
    color: '#142C4C',
    fontFamily: 'Inter',
    fontSize: 16,
    includeFontPadding: false,
    lineHeight: 20,
  },
  activeDayAvailabilityOptionText: {
    color: '#142C4C',
  },
  timeSlotSectionHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    marginTop: 24,
  },
  timeSlotSectionTitle: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 23,
    includeFontPadding: false,
    lineHeight: 31,
  },
  timeSlotSectionSubtitle: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 12,
    includeFontPadding: false,
    lineHeight: 17,
    maxWidth: 220,
  },
  timeSlotPanel: {
    marginTop: 24,
  },
  timeSlotPanelHeaderRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
  },
  timeSlotPanelCopy: {
    flex: 1,
    minWidth: 0,
  },
  timeSlotPanelTitle: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 18,
    includeFontPadding: false,
    lineHeight: 24,
  },
  timeSlotPanelSubtitle: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 13,
    includeFontPadding: false,
    lineHeight: 18,
    marginTop: 3,
  },
  timeSlotHeaderActions: {
    alignItems: 'stretch',
    gap: 8,
  },
  addTimeButton: {
    alignItems: 'center',
    backgroundColor: '#142C4C',
    borderRadius: 999,
    justifyContent: 'center',
    minHeight: 38,
    paddingHorizontal: 14,
  },
  disabledAddTimeButton: {
    backgroundColor: '#8AA3C3',
  },
  addTimeButtonText: {
    color: '#ffffff',
    fontFamily: 'InterBold',
    fontSize: 12,
    includeFontPadding: false,
    lineHeight: 16,
  },
  fullDayButton: {
    alignItems: 'center',
    backgroundColor: '#FFE3E4',
    borderColor: '#F37C7E',
    borderRadius: 999,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 38,
    paddingHorizontal: 14,
  },
  fullDayButtonText: {
    color: '#E45F62',
    fontFamily: 'InterBold',
    fontSize: 12,
    includeFontPadding: false,
    lineHeight: 16,
  },
  reopenDayButton: {
    backgroundColor: '#EAF8F4',
    borderColor: '#4FB69F',
  },
  reopenDayButtonText: {
    color: '#2D8F78',
  },
  timeSlotList: {
    gap: 10,
    marginTop: 14,
  },
  timeSlotCard: {
    backgroundColor: '#ffffff',
    borderColor: 'rgba(76, 94, 118, 0.12)',
    borderRadius: 13,
    borderWidth: 1,
    padding: 12,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 2,
  },
  timeSlotCardTopRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
  },
  timeSlotCopy: {
    flex: 1,
    marginBottom: 10,
    minWidth: 0,
  },
  timeSlotTime: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 16,
    includeFontPadding: false,
    lineHeight: 22,
  },
  timeSlotStatus: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 13,
    includeFontPadding: false,
    lineHeight: 18,
    marginTop: 3,
  },
  timeSlotActions: {
    flexDirection: 'row',
    gap: 8,
  },
  slotStatusPill: {
    alignItems: 'center',
    borderRadius: 999,
    justifyContent: 'center',
    minHeight: 28,
    minWidth: 92,
    paddingHorizontal: 10,
  },
  availableSlotPill: {
    backgroundColor: 'rgba(10, 181, 67, 0.3)',
  },
  bookedSlotPill: {
    backgroundColor: 'rgba(8, 57, 121, 0.3)',
  },
  unavailableSlotPill: {
    backgroundColor: '#FFF1F1',
  },
  slotStatusPillText: {
    fontFamily: 'InterBold',
    fontSize: 11,
    includeFontPadding: false,
    lineHeight: 15,
  },
  availableSlotPillText: {
    color: '#086959',
  },
  bookedSlotPillText: {
    color: '#142C4C',
  },
  unavailableSlotPillText: {
    color: '#E45F62',
  },
  closedDayPanel: {
    backgroundColor: '#ffffff',
    borderColor: 'rgba(76, 94, 118, 0.12)',
    borderRadius: 14,
    borderWidth: 1,
    padding: 16,
  },
  closedDayTitle: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 16,
    includeFontPadding: false,
    lineHeight: 22,
  },
  closedDayText: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 13,
    includeFontPadding: false,
    lineHeight: 19,
    marginTop: 4,
  },
  timeSlotManageRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 8,
  },
  slotAvailableButton: {
    alignItems: 'center',
    backgroundColor: '#EAF8F4',
    borderColor: '#4FB69F',
    borderRadius: 10,
    borderWidth: 1,
    flex: 1,
    minHeight: 40,
    justifyContent: 'center',
  },
  activeSlotButton: {
    backgroundColor: '#4FB69F',
  },
  slotAvailableText: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 12,
    includeFontPadding: false,
  },
  slotUnavailableButton: {
    alignItems: 'center',
    backgroundColor: '#FFF1F1',
    borderColor: '#F37C7E',
    borderRadius: 10,
    borderWidth: 1,
    flex: 1,
    minHeight: 40,
    justifyContent: 'center',
  },
  activeUnavailableButton: {
    backgroundColor: '#F37C7E',
  },
  slotUnavailableText: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 12,
    includeFontPadding: false,
  },
  slotEditButton: {
    alignItems: 'center',
    backgroundColor: '#EAF2FA',
    borderRadius: 10,
    flex: 1,
    minHeight: 38,
    justifyContent: 'center',
  },
  slotEditText: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 12,
    includeFontPadding: false,
  },
  slotDeleteButton: {
    alignItems: 'center',
    backgroundColor: '#FFF1F1',
    borderColor: '#F37C7E',
    borderRadius: 10,
    borderWidth: 1,
    flex: 1,
    minHeight: 38,
    justifyContent: 'center',
  },
  slotDeleteText: {
    color: '#E45F62',
    fontFamily: 'InterBold',
    fontSize: 12,
    includeFontPadding: false,
  },
  calendarSlotFieldRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 16,
  },
  calendarSlotField: {
    flex: 1,
  },
  calendarSlotInput: {
    backgroundColor: '#ffffff',
    borderColor: 'rgba(138, 163, 195, 0.35)',
    borderRadius: 10,
    borderWidth: 1,
    color: '#142C4C',
    fontFamily: 'Inter',
    fontSize: 16,
    height: 48,
    includeFontPadding: false,
    paddingHorizontal: 17,
    shadowColor: '#142C4C',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.24,
    shadowRadius: 4,
    elevation: 3,
  },
  adminServicesContent: {
    paddingHorizontal: 18,
    paddingTop: 62,
  },
  servicesFigmaSurface: {
    backgroundColor: '#ffffff',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    flex: 1,
    overflow: 'hidden',
    paddingHorizontal: 18,
    paddingTop: 17,
    position: 'relative',
  },
  servicesFigmaBackground: {
    bottom: 0,
    left: 0,
    opacity: 0.6,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  servicesFigmaTopBand: {
    backgroundColor: '#142C4C',
    left: 0,
    overflow: 'hidden',
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 1,
  },
  servicesFigmaTopTexture: {
    bottom: 0,
    left: 0,
    opacity: 0.1,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  servicesFigmaContent: {
    flex: 1,
    minHeight: '100%',
    paddingHorizontal: 18,
    paddingTop: 147,
  },
  servicesCategoryBrandRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    left: 0,
    position: 'absolute',
    right: 0,
    zIndex: 3,
  },
  servicesCategoryBrandText: {
    color: '#ffffff',
    fontFamily: 'Jomolhari',
    fontSize: 28,
    includeFontPadding: false,
    lineHeight: 44,
  },
  servicesCategoryBrandLogo: {
    height: 52,
    marginLeft: -2,
    width: 62,
  },
  servicesCategoryIntro: {
    minHeight: 94,
    paddingLeft: 6,
    paddingTop: 0,
    position: 'relative',
  },
  servicesCategoryTitle: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 30,
    includeFontPadding: false,
    lineHeight: 42,
  },
  servicesCategorySubtitle: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 16,
    includeFontPadding: false,
    lineHeight: 20,
    marginTop: 4,
    maxWidth: 250,
  },
  servicesCategoryAddButton: {
    alignItems: 'center',
    backgroundColor: '#142C4C',
    borderRadius: 10,
    height: 46,
    justifyContent: 'center',
    position: 'absolute',
    right: 4,
    top: 4,
    width: 115,
  },
  servicesCategoryAddText: {
    color: '#ffffff',
    fontFamily: 'InterMedium',
    fontSize: 20,
    includeFontPadding: false,
    lineHeight: 24,
  },
  servicesTabsRow: {
    flexDirection: 'row',
    gap: 14,
    marginTop: 0,
    paddingHorizontal: 10,
  },
  servicesFigmaTabActive: {
    alignItems: 'center',
    backgroundColor: '#E4EEFC',
    borderRadius: 10,
    flex: 1,
    height: 48,
    justifyContent: 'center',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 3,
  },
  servicesFigmaTab: {
    alignItems: 'center',
    backgroundColor: '#EEEDF1',
    borderRadius: 10,
    flex: 1,
    height: 48,
    justifyContent: 'center',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 3,
  },
  servicesFigmaTabText: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 16,
    includeFontPadding: false,
    lineHeight: 24,
  },
  servicesCategoryFigmaList: {
    gap: 8,
    paddingBottom: 12,
    paddingHorizontal: 10,
    paddingTop: 16,
  },
  servicesCategoryFigmaCard: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: 'rgba(138, 163, 195, 0.12)',
    borderRadius: 10,
    flexDirection: 'row',
    height: 92,
    paddingLeft: 3,
    paddingRight: 15,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 3,
  },
  servicesCategoryFigmaOpenArea: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    minWidth: 0,
  },
  servicesCategoryFigmaImage: {
    borderRadius: 10,
    height: 85,
    width: 133,
  },
  servicesCategoryFigmaCopy: {
    flex: 1,
    marginLeft: 13,
    minWidth: 0,
  },
  servicesCategoryFigmaName: {
    color: '#142C4C',
    fontFamily: 'InterMedium',
    fontSize: 14,
    includeFontPadding: false,
    lineHeight: 18,
  },
  servicesCategoryFigmaCount: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 13,
    includeFontPadding: false,
    lineHeight: 17,
    marginTop: 2,
  },
  servicesCategoryFigmaActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    marginLeft: 8,
  },
  servicesCategoryArrowCircle: {
    alignItems: 'center',
    backgroundColor: '#EEE9EA',
    borderRadius: 16,
    height: 32,
    justifyContent: 'center',
    width: 32,
  },
  servicesCategoryHiddenActions: {
    display: 'none',
  },
  servicesBrandRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 7,
  },
  servicesBrandText: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 23,
    includeFontPadding: false,
    lineHeight: 36,
  },
  servicesBrandLogo: {
    height: 43,
    marginLeft: -2,
    width: 52,
  },
  servicesPackageHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    marginTop: 0,
  },
  servicesBackButton: {
    alignItems: 'center',
    height: 35,
    justifyContent: 'center',
    marginRight: 24,
    width: 35,
  },
  servicesPackageHeaderCopy: {
    flex: 1,
    minWidth: 0,
  },
  servicesPackageTitle: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 18,
    includeFontPadding: false,
    lineHeight: 26,
  },
  servicesPackageCount: {
    color: '#515354',
    fontFamily: 'Inter',
    fontSize: 14,
    includeFontPadding: false,
    lineHeight: 18,
    marginTop: 4,
  },
  servicesFigmaAddButton: {
    alignItems: 'center',
    backgroundColor: '#142C4C',
    borderRadius: 10,
    height: 55,
    justifyContent: 'center',
    width: 74,
  },
  servicesFigmaAddText: {
    color: '#ffffff',
    fontFamily: 'Inter',
    fontSize: 43,
    includeFontPadding: false,
    lineHeight: 48,
    marginTop: -5,
  },
  servicesPackageList: {
    gap: 15,
    paddingBottom: 12,
    paddingTop: 15,
  },
  servicesFigmaListScroller: {
    flex: 1,
  },
  servicesPackageCard: {
    alignItems: 'flex-start',
    backgroundColor: '#ffffff',
    borderColor: 'rgba(138, 163, 195, 0.16)',
    borderRadius: 10,
    flexDirection: 'row',
    minHeight: 103,
    paddingBottom: 6,
    paddingLeft: 6,
    paddingRight: 9,
    paddingTop: 6,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 3,
  },
  servicesPackageImage: {
    borderRadius: 10,
    height: 91,
    width: 91,
  },
  servicesPackageCopy: {
    flex: 1,
    marginLeft: 9,
    minWidth: 0,
    paddingRight: 6,
    paddingTop: 1,
  },
  servicesPackageName: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 13,
    includeFontPadding: false,
    lineHeight: 19,
  },
  servicesPackagePrice: {
    color: '#142C4C',
    fontFamily: 'InterSemiBold',
    fontSize: 13,
    includeFontPadding: false,
    lineHeight: 16,
    marginTop: -1,
  },
  servicesInclusionList: {
    marginTop: 1,
  },
  servicesInclusionRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 7,
    height: 10,
  },
  servicesInclusionDot: {
    backgroundColor: '#142C4C',
    borderRadius: 2,
    height: 4,
    width: 4,
  },
  servicesInclusionText: {
    color: '#515354',
    flex: 1,
    fontFamily: 'Inter',
    fontSize: 8,
    includeFontPadding: false,
    lineHeight: 10,
  },
  servicesPackageActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    paddingTop: 10,
  },
  servicesEmptyPackagesCard: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: 'rgba(138, 163, 195, 0.16)',
    borderRadius: 14,
    minHeight: 184,
    justifyContent: 'center',
    paddingHorizontal: 28,
    paddingVertical: 26,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.18,
    shadowRadius: 4,
    elevation: 3,
  },
  servicesEmptyPackagesTitle: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 22,
    includeFontPadding: false,
    lineHeight: 31,
    marginTop: 12,
    textAlign: 'center',
  },
  servicesEmptyPackagesText: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 14,
    includeFontPadding: false,
    lineHeight: 20,
    marginTop: 4,
    textAlign: 'center',
  },
  servicesHeaderRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  servicesHeaderCopy: {
    flex: 1,
    paddingRight: 10,
  },
  serviceAddButton: {
    alignItems: 'center',
    backgroundColor: '#142C4C',
    borderRadius: 9,
    flexDirection: 'row',
    gap: 4,
    minHeight: 38,
    paddingHorizontal: 12,
  },
  serviceAddText: {
    color: '#ffffff',
    fontFamily: 'InterBold',
    fontSize: 12,
    includeFontPadding: false,
  },
  servicesSegmentedControl: {
    backgroundColor: '#D8E8F8',
    borderRadius: 12,
    flexDirection: 'row',
    marginBottom: 17,
    padding: 4,
  },
  servicesSegment: {
    alignItems: 'center',
    borderRadius: 9,
    flex: 1,
    height: 39,
    justifyContent: 'center',
  },
  activeServicesSegment: {
    backgroundColor: '#ffffff',
  },
  servicesSegmentText: {
    color: '#4C77A5',
    fontFamily: 'InterBold',
    fontSize: 13,
    includeFontPadding: false,
  },
  activeServicesSegmentText: {
    color: '#142C4C',
  },
  serviceCategoryList: {
    gap: 10,
  },
  serviceCategoryCard: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: 'rgba(76, 94, 118, 0.12)',
    borderRadius: 13,
    borderWidth: 1,
    flexDirection: 'row',
    minHeight: 76,
    paddingHorizontal: 10,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 2,
  },
  serviceCategoryThumb: {
    alignItems: 'center',
    borderRadius: 10,
    height: 56,
    justifyContent: 'center',
    marginRight: 13,
    overflow: 'hidden',
    width: 80,
  },
  serviceThumbImage: {
    height: '100%',
    width: '100%',
  },
  serviceThumbTone1: {
    backgroundColor: '#EAF2FA',
  },
  serviceThumbTone2: {
    backgroundColor: '#F2E9E4',
  },
  serviceThumbTone3: {
    backgroundColor: '#EDE7DD',
  },
  serviceThumbTone4: {
    backgroundColor: '#E3EFE8',
  },
  serviceCategoryCopy: {
    flex: 1,
    minWidth: 0,
  },
  serviceCategoryName: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 15,
    includeFontPadding: false,
    lineHeight: 21,
  },
  serviceCategoryCount: {
    color: '#4C77A5',
    fontFamily: 'Inter',
    fontSize: 12,
    includeFontPadding: false,
    lineHeight: 17,
    marginTop: 2,
  },
  serviceManageActions: {
    gap: 6,
    marginLeft: 8,
  },
  serviceManageButton: {
    alignItems: 'center',
    backgroundColor: '#EAF2FA',
    borderRadius: 8,
    justifyContent: 'center',
    minHeight: 28,
    minWidth: 47,
    paddingHorizontal: 8,
  },
  serviceManageText: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 11,
    includeFontPadding: false,
  },
  formOverlay: {
    flex: 1,
    backgroundColor: 'rgba(20, 44, 76, 0.35)',
    justifyContent: 'flex-end',
  },
  formSheet: {
    backgroundColor: '#F3EEEE',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: '86%',
    paddingBottom: 24,
    paddingHorizontal: 18,
    paddingTop: 20,
  },
  formTitle: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 24,
    includeFontPadding: false,
    lineHeight: 34,
    marginBottom: 14,
  },
  formField: {
    marginBottom: 12,
  },
  formLabel: {
    color: '#4C5E76',
    fontFamily: 'InterBold',
    fontSize: 12,
    includeFontPadding: false,
    lineHeight: 17,
    marginBottom: 6,
  },
  formInput: {
    backgroundColor: '#ffffff',
    borderColor: 'rgba(76, 94, 118, 0.22)',
    borderRadius: 10,
    borderWidth: 1,
    color: '#142C4C',
    fontFamily: 'Inter',
    fontSize: 14,
    includeFontPadding: false,
    minHeight: 46,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  formTextarea: {
    minHeight: 92,
    textAlignVertical: 'top',
  },
  imagePickerRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
  },
  imagePickerPreview: {
    alignItems: 'center',
    backgroundColor: '#EAF2FA',
    borderColor: 'rgba(76, 94, 118, 0.22)',
    borderRadius: 12,
    borderWidth: 1,
    height: 78,
    justifyContent: 'center',
    overflow: 'hidden',
    width: 104,
  },
  imagePickerPreviewImage: {
    height: '100%',
    width: '100%',
  },
  imagePickerButton: {
    alignItems: 'center',
    backgroundColor: '#142C4C',
    borderRadius: 12,
    flex: 1,
    height: 48,
    justifyContent: 'center',
  },
  imagePickerButtonText: {
    color: '#ffffff',
    fontFamily: 'InterBold',
    fontSize: 13,
    includeFontPadding: false,
  },
  imagePickerHint: {
    color: '#6D7E94',
    fontFamily: 'Inter',
    fontSize: 11,
    includeFontPadding: false,
    lineHeight: 15,
    marginTop: 7,
  },
  activeToggleRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    marginBottom: 16,
    marginTop: 2,
  },
  activeToggleBox: {
    backgroundColor: '#E45F62',
    borderRadius: 9,
    height: 18,
    width: 18,
  },
  activeToggleBoxOn: {
    backgroundColor: '#4FB69F',
  },
  activeToggleText: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 13,
    includeFontPadding: false,
  },
  formActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 4,
  },
  formCancelButton: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: 'rgba(76, 94, 118, 0.22)',
    borderRadius: 12,
    borderWidth: 1,
    flex: 1,
    height: 52,
    justifyContent: 'center',
  },
  formCancelText: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 14,
    includeFontPadding: false,
  },
  formSaveButton: {
    alignItems: 'center',
    backgroundColor: '#142C4C',
    borderRadius: 12,
    flex: 1,
    height: 52,
    justifyContent: 'center',
  },
  formSaveText: {
    color: '#ffffff',
    fontFamily: 'InterBold',
    fontSize: 14,
    includeFontPadding: false,
  },
  servicePickerList: {
    gap: 8,
    marginBottom: 12,
  },
  servicePickerOption: {
    backgroundColor: '#ffffff',
    borderColor: 'rgba(76, 94, 118, 0.2)',
    borderRadius: 10,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  activeServicePickerOption: {
    backgroundColor: '#142C4C',
    borderColor: '#142C4C',
  },
  servicePickerText: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 13,
    includeFontPadding: false,
  },
  activeServicePickerText: {
    color: '#ffffff',
  },
  simpleProfileContainer: {
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 22,
    paddingTop: 84,
  },
  adminProfileBackgroundImage: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  adminProfileScrollView: {
    flex: 1,
  },
  adminProfileContent: {
    alignSelf: 'center',
    paddingHorizontal: 14,
  },
  simpleProfileHeader: {
    alignItems: 'center',
    marginBottom: 15,
  },
  simpleProfileLogo: {
    alignItems: 'center',
    backgroundColor: '#142C4C',
    borderColor: 'rgba(255, 255, 255, 0.85)',
    borderRadius: 43,
    borderWidth: 4,
    height: 86,
    justifyContent: 'center',
    marginBottom: 7,
    position: 'relative',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.18,
    shadowRadius: 4,
    width: 86,
    elevation: 4,
  },
  adminProfileLogoImage: {
    height: 47,
    width: 56,
  },
  adminProfileCameraBadge: {
    alignItems: 'center',
    backgroundColor: '#546D91',
    borderColor: '#ffffff',
    borderRadius: 15,
    borderWidth: 2,
    bottom: -4,
    height: 30,
    justifyContent: 'center',
    position: 'absolute',
    right: -4,
    width: 30,
  },
  simpleProfileName: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 18,
    includeFontPadding: false,
    lineHeight: 28,
    textAlign: 'center',
  },
  simpleProfileRole: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 13,
    includeFontPadding: false,
    lineHeight: 18,
    marginTop: 1,
    textAlign: 'center',
  },
  studioSettingsCard: {
    backgroundColor: '#ffffff',
    borderRadius: 20,
    marginBottom: 14,
    paddingBottom: 12,
    paddingHorizontal: 12,
    paddingTop: 13,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 4,
  },
  studioSettingsTitle: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 15,
    includeFontPadding: false,
    lineHeight: 22,
    marginBottom: 11,
  },
  studioSettingsSubtitle: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 12,
    includeFontPadding: false,
    lineHeight: 18,
    marginBottom: 14,
    marginTop: 4,
  },
  studioField: {
    marginBottom: 8,
  },
  studioFormLabel: {
    color: '#142C4C',
    fontFamily: 'InterMedium',
    fontSize: 13,
    includeFontPadding: false,
    lineHeight: 18,
    marginBottom: 5,
  },
  studioFormInput: {
    backgroundColor: '#ffffff',
    borderColor: 'rgba(76, 94, 118, 0.5)',
    borderRadius: 10,
    borderWidth: 1,
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 13,
    height: 43,
    includeFontPadding: false,
    paddingHorizontal: 11,
    paddingVertical: 9,
  },
  studioAddressInput: {
    height: 71,
    paddingTop: 10,
    textAlignVertical: 'top',
  },
  businessHoursInputRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  businessHoursInput: {
    flex: 1,
  },
  businessHoursSeparator: {
    color: '#4C5E76',
    fontFamily: 'InterMedium',
    fontSize: 13,
    includeFontPadding: false,
  },
  studioSaveButton: {
    alignItems: 'center',
    backgroundColor: '#142C4C',
    borderRadius: 10,
    height: 50,
    justifyContent: 'center',
    marginTop: 2,
  },
  studioSaveText: {
    color: '#ffffff',
    fontFamily: 'Jomolhari',
    fontSize: 20,
    includeFontPadding: false,
    lineHeight: 30,
  },
  simpleLogoutButton: {
    alignItems: 'center',
    alignSelf: 'stretch',
    backgroundColor: '#142C4C',
    borderRadius: 10,
    flexDirection: 'row',
    gap: 12,
    height: 44,
    justifyContent: 'center',
  },
  simpleLogoutText: {
    color: '#ffffff',
    fontFamily: 'Jomolhari',
    fontSize: 20,
    includeFontPadding: false,
    lineHeight: 30,
  },
});
