import { StyleSheet } from 'react-native';

export const profileStyles = StyleSheet.create({
  container: {
    backgroundColor: '#142C4C',
    flex: 1,
  },
  compactHeader: {
    alignItems: 'center',
    backgroundColor: '#142C4C',
    height: 130,
    justifyContent: 'center',
  },
  profileBrandRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
  },
  profileBrandText: {
    color: '#ffffff',
    fontFamily: 'Jomolhari',
    fontSize: 24,
    includeFontPadding: false,
    lineHeight: 38,
  },
  editBrandText: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 18,
    includeFontPadding: false,
    lineHeight: 30,
  },
  profileBrandLogo: {
    height: 38,
    marginLeft: 0,
    width: 46,
  },
  profileDesignBody: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    flex: 1,
    overflow: 'hidden',
    paddingHorizontal: 28,
    paddingTop: 23,
  },
  profileBackgroundImage: {
    bottom: 0,
    height: '100%',
    left: 0,
    opacity: 0.9,
    position: 'absolute',
    right: 0,
    top: 0,
    width: '100%',
  },
  profileHeader: {
    alignItems: 'center',
    backgroundColor: '#142C4C',
    height: 178,
    justifyContent: 'center',
    paddingHorizontal: 22,
  },
  profileHeaderTitle: {
    color: '#ffffff',
    fontFamily: 'Jomolhari',
    fontSize: 28,
    includeFontPadding: false,
    lineHeight: 40,
  },
  profileSheet: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    flex: 1,
    marginTop: -28,
    paddingHorizontal: 24,
    paddingTop: 68,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
  },
  avatarOuter: {
    alignItems: 'center',
    backgroundColor: '#8AA3C3',
    borderColor: '#ffffff',
    borderRadius: 56,
    borderWidth: 5,
    height: 112,
    justifyContent: 'center',
    position: 'absolute',
    top: -56,
    width: 112,
  },
  avatarImage: {
    borderRadius: 51,
    height: 102,
    width: 102,
  },
  avatarInitials: {
    color: '#ffffff',
    fontFamily: 'Jomolhari',
    fontSize: 36,
    includeFontPadding: false,
    lineHeight: 48,
  },
  profileAvatarWrap: {
    alignItems: 'center',
    backgroundColor: '#D9D9D9',
    borderRadius: 66,
    height: 132,
    justifyContent: 'center',
    marginTop: 0,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.22,
    shadowRadius: 4,
    elevation: 4,
    width: 132,
  },
  profileAvatarImage: {
    borderRadius: 66,
    height: 132,
    width: 132,
  },
  defaultAvatar: {
    alignItems: 'center',
    borderRadius: 66,
    height: 132,
    justifyContent: 'flex-end',
    overflow: 'hidden',
    width: 132,
  },
  defaultAvatarHead: {
    backgroundColor: '#ffffff',
    borderRadius: 25,
    height: 50,
    position: 'absolute',
    top: 37,
    width: 50,
  },
  defaultAvatarBody: {
    backgroundColor: '#ffffff',
    borderTopLeftRadius: 54,
    borderTopRightRadius: 54,
    height: 45,
    width: 98,
  },
  profileCameraBadge: {
    alignItems: 'center',
    backgroundColor: '#142C4C',
    borderRadius: 28,
    bottom: -1,
    height: 56,
    justifyContent: 'center',
    position: 'absolute',
    right: -12,
    width: 56,
  },
  designProfileName: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 32,
    includeFontPadding: false,
    lineHeight: 42,
    marginTop: 19,
    maxWidth: '100%',
    textAlign: 'center',
  },
  designProfileEmail: {
    color: '#4C5E76',
    fontFamily: 'InterBold',
    fontSize: 20,
    includeFontPadding: false,
    lineHeight: 23,
    marginTop: -1,
    maxWidth: 245,
    textAlign: 'center',
  },
  designActionStack: {
    alignSelf: 'stretch',
    gap: 10,
    marginTop: 7,
  },
  profileMenuRow: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: 'rgba(76, 94, 118, 0.16)',
    borderRadius: 10,
    borderWidth: 1,
    flexDirection: 'row',
    height: 70,
    justifyContent: 'space-between',
    paddingLeft: 35,
    paddingRight: 28,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 4,
  },
  profileMenuLeft: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  profileMenuText: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 20,
    includeFontPadding: false,
    lineHeight: 32,
  },
  designLogoutWrap: {
    alignSelf: 'stretch',
    left: 27,
    position: 'absolute',
    right: 24,
  },
  designLogoutButton: {
    alignItems: 'center',
    backgroundColor: '#142C4C',
    borderRadius: 30,
    flexDirection: 'row',
    gap: 8,
    height: 70,
    justifyContent: 'center',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 4,
  },
  designLogoutText: {
    color: '#ffffff',
    fontFamily: 'Jomolhari',
    fontSize: 20,
    includeFontPadding: false,
    lineHeight: 31,
  },
  profileName: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 27,
    includeFontPadding: false,
    lineHeight: 38,
    maxWidth: '100%',
    textAlign: 'center',
  },
  profileRole: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 14,
    includeFontPadding: false,
    lineHeight: 20,
    marginTop: 4,
  },
  profileInfoCard: {
    alignSelf: 'stretch',
    backgroundColor: '#F6FAFF',
    borderColor: 'rgba(76, 94, 118, 0.12)',
    borderRadius: 18,
    borderWidth: 1,
    marginTop: 28,
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  profileInfoRow: {
    alignItems: 'center',
    borderBottomColor: 'rgba(138, 163, 195, 0.22)',
    borderBottomWidth: 1,
    flexDirection: 'row',
    minHeight: 64,
  },
  profileInfoIcon: {
    alignItems: 'center',
    backgroundColor: '#E6F1FD',
    borderRadius: 18,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  profileInfoCopy: {
    flex: 1,
    marginLeft: 12,
  },
  profileInfoLabel: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 12,
    includeFontPadding: false,
    lineHeight: 16,
  },
  profileInfoValue: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 14,
    includeFontPadding: false,
    lineHeight: 19,
    marginTop: 3,
  },
  profileActionStack: {
    alignSelf: 'stretch',
    gap: 12,
    marginTop: 26,
  },
  editProfileButton: {
    alignItems: 'center',
    backgroundColor: '#142C4C',
    borderRadius: 18,
    flexDirection: 'row',
    gap: 10,
    height: 58,
    justifyContent: 'center',
  },
  editProfileText: {
    color: '#ffffff',
    fontFamily: 'InterBold',
    fontSize: 16,
    includeFontPadding: false,
    lineHeight: 20,
  },
  logoutButton: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: '#F1A8AA',
    borderRadius: 18,
    borderWidth: 1.5,
    flexDirection: 'row',
    gap: 10,
    height: 58,
    justifyContent: 'center',
  },
  logoutText: {
    color: '#E45F62',
    fontFamily: 'InterBold',
    fontSize: 16,
    includeFontPadding: false,
  },
  editContainer: {
    backgroundColor: '#CEDFF7',
    flex: 1,
  },
  editCompactHeader: {
    alignItems: 'center',
    backgroundColor: '#CFE1F5',
    height: 91,
    justifyContent: 'center',
  },
  editBackButton: {
    alignItems: 'center',
    height: 48,
    justifyContent: 'center',
    left: 17,
    position: 'absolute',
    top: 20,
    width: 48,
  },
  editHeaderTitle: {
    color: '#ffffff',
    fontFamily: 'Jomolhari',
    fontSize: 25,
    includeFontPadding: false,
    lineHeight: 36,
    marginTop: 18,
  },
  editContent: {
    alignItems: 'stretch',
    paddingHorizontal: 27,
    paddingTop: 8,
  },
  editBackgroundImage: {
    bottom: 0,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    height: '100%',
    left: 0,
    opacity: 0.9,
    position: 'absolute',
    right: 0,
    top: 91,
    width: '100%',
  },
  editScreenTitle: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 24,
    includeFontPadding: false,
    lineHeight: 38,
    marginBottom: 0,
  },
  editAvatarWrap: {
    alignSelf: 'center',
    alignItems: 'center',
    backgroundColor: '#D9D9D9',
    borderRadius: 58,
    height: 116,
    justifyContent: 'center',
    marginTop: 0,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.22,
    shadowRadius: 4,
    elevation: 4,
    width: 116,
  },
  editAvatarImage: {
    borderRadius: 58,
    height: 116,
    width: 116,
  },
  editDefaultAvatar: {
    alignItems: 'center',
    borderRadius: 58,
    height: 116,
    justifyContent: 'flex-end',
    overflow: 'hidden',
    width: 116,
  },
  editDefaultAvatarHead: {
    backgroundColor: '#ffffff',
    borderRadius: 19,
    height: 38,
    position: 'absolute',
    top: 32,
    width: 38,
  },
  editDefaultAvatarBody: {
    backgroundColor: '#ffffff',
    borderTopLeftRadius: 46,
    borderTopRightRadius: 46,
    height: 38,
    width: 86,
  },
  editAvatarBadge: {
    alignItems: 'center',
    backgroundColor: '#142C4C',
    borderRadius: 22,
    bottom: 3,
    height: 44,
    justifyContent: 'center',
    position: 'absolute',
    right: -1,
    width: 44,
  },
  editAvatarHint: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 12,
    includeFontPadding: false,
    lineHeight: 17,
    marginTop: 10,
  },
  editFormCard: {
    alignSelf: 'stretch',
    backgroundColor: 'transparent',
    marginTop: 22,
  },
  editSectionTitle: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 24,
    includeFontPadding: false,
    lineHeight: 38,
    marginTop: 20,
  },
  editField: {
    marginBottom: 14,
  },
  editLabel: {
    color: '#142C4C',
    fontFamily: 'Inter',
    fontSize: 16,
    includeFontPadding: false,
    lineHeight: 22,
    marginBottom: 7,
  },
  requiredMark: {
    color: '#E45F62',
  },
  editInputShell: {
    alignSelf: 'stretch',
    justifyContent: 'center',
  },
  editInput: {
    backgroundColor: '#ffffff',
    borderColor: 'rgba(169, 183, 202, 0.5)',
    borderRadius: 10,
    borderWidth: 1,
    color: '#757575',
    fontFamily: 'Inter',
    fontSize: 16,
    height: 49,
    includeFontPadding: false,
    paddingHorizontal: 20,
  },
  editInputWithAccessory: {
    paddingRight: 56,
  },
  editInputAccessory: {
    alignItems: 'center',
    height: 49,
    justifyContent: 'center',
    position: 'absolute',
    right: 13,
    top: 0,
    width: 32,
  },
  editInputDisabled: {
    color: '#6E7F94',
    opacity: 0.82,
  },
  editButtonRow: {
    flexDirection: 'row',
    gap: 16,
    marginTop: 14,
  },
  cancelEditButton: {
    alignItems: 'center',
    backgroundColor: '#D6DFEA',
    borderRadius: 10,
    flex: 1,
    height: 53,
    justifyContent: 'center',
  },
  cancelEditText: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 20,
    includeFontPadding: false,
    lineHeight: 31,
  },
  saveProfileButton: {
    alignItems: 'center',
    backgroundColor: '#142C4C',
    borderRadius: 10,
    flex: 1,
    height: 53,
    justifyContent: 'center',
  },
  saveProfileText: {
    color: '#ffffff',
    fontFamily: 'Jomolhari',
    fontSize: 20,
    includeFontPadding: false,
    lineHeight: 31,
  },
});
