import { StyleSheet } from 'react-native';

export const profileStyles = StyleSheet.create({
  container: {
    backgroundColor: '#F3EEEE',
    flex: 1,
  },
  profileHeader: {
    alignItems: 'center',
    backgroundColor: '#142C4C',
    height: 178,
    justifyContent: 'center',
    paddingHorizontal: 22,
  },
  profileHeaderTitle: {
    color: '#ffffff',
    fontFamily: 'Jomolhari',
    fontSize: 28,
    includeFontPadding: false,
    lineHeight: 40,
  },
  profileSheet: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    flex: 1,
    marginTop: -28,
    paddingHorizontal: 24,
    paddingTop: 68,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
  },
  avatarOuter: {
    alignItems: 'center',
    backgroundColor: '#8AA3C3',
    borderColor: '#ffffff',
    borderRadius: 56,
    borderWidth: 5,
    height: 112,
    justifyContent: 'center',
    position: 'absolute',
    top: -56,
    width: 112,
  },
  avatarImage: {
    borderRadius: 51,
    height: 102,
    width: 102,
  },
  avatarInitials: {
    color: '#ffffff',
    fontFamily: 'Jomolhari',
    fontSize: 36,
    includeFontPadding: false,
    lineHeight: 48,
  },
  profileName: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 27,
    includeFontPadding: false,
    lineHeight: 38,
    maxWidth: '100%',
    textAlign: 'center',
  },
  profileRole: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 14,
    includeFontPadding: false,
    lineHeight: 20,
    marginTop: 4,
  },
  profileInfoCard: {
    alignSelf: 'stretch',
    backgroundColor: '#F6FAFF',
    borderColor: 'rgba(76, 94, 118, 0.12)',
    borderRadius: 18,
    borderWidth: 1,
    marginTop: 28,
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  profileInfoRow: {
    alignItems: 'center',
    borderBottomColor: 'rgba(138, 163, 195, 0.22)',
    borderBottomWidth: 1,
    flexDirection: 'row',
    minHeight: 64,
  },
  profileInfoIcon: {
    alignItems: 'center',
    backgroundColor: '#E6F1FD',
    borderRadius: 18,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  profileInfoCopy: {
    flex: 1,
    marginLeft: 12,
  },
  profileInfoLabel: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 12,
    includeFontPadding: false,
    lineHeight: 16,
  },
  profileInfoValue: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 14,
    includeFontPadding: false,
    lineHeight: 19,
    marginTop: 3,
  },
  profileActionStack: {
    alignSelf: 'stretch',
    gap: 12,
    marginTop: 26,
  },
  editProfileButton: {
    alignItems: 'center',
    backgroundColor: '#142C4C',
    borderRadius: 18,
    flexDirection: 'row',
    gap: 10,
    height: 58,
    justifyContent: 'center',
  },
  editProfileText: {
    color: '#ffffff',
    fontFamily: 'InterBold',
    fontSize: 16,
    includeFontPadding: false,
    lineHeight: 20,
  },
  logoutButton: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: '#F1A8AA',
    borderRadius: 18,
    borderWidth: 1.5,
    flexDirection: 'row',
    gap: 10,
    height: 58,
    justifyContent: 'center',
  },
  logoutText: {
    color: '#E45F62',
    fontFamily: 'InterBold',
    fontSize: 16,
    includeFontPadding: false,
  },
  editContainer: {
    backgroundColor: '#F3EEEE',
    flex: 1,
  },
  editBackButton: {
    alignItems: 'center',
    height: 44,
    justifyContent: 'center',
    left: 18,
    position: 'absolute',
    top: 54,
    width: 44,
  },
  editHeaderTitle: {
    color: '#ffffff',
    fontFamily: 'Jomolhari',
    fontSize: 25,
    includeFontPadding: false,
    lineHeight: 36,
    marginTop: 18,
  },
  editContent: {
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingTop: 28,
  },
  editAvatarWrap: {
    alignItems: 'center',
    backgroundColor: '#8AA3C3',
    borderColor: '#ffffff',
    borderRadius: 58,
    borderWidth: 5,
    height: 116,
    justifyContent: 'center',
    marginTop: -86,
    width: 116,
  },
  editAvatarImage: {
    borderRadius: 53,
    height: 106,
    width: 106,
  },
  editAvatarBadge: {
    alignItems: 'center',
    backgroundColor: '#142C4C',
    borderColor: '#ffffff',
    borderRadius: 18,
    borderWidth: 2,
    bottom: 0,
    height: 36,
    justifyContent: 'center',
    position: 'absolute',
    right: -2,
    width: 36,
  },
  editAvatarHint: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 12,
    includeFontPadding: false,
    lineHeight: 17,
    marginTop: 10,
  },
  editFormCard: {
    alignSelf: 'stretch',
    backgroundColor: '#ffffff',
    borderRadius: 22,
    marginTop: 24,
    padding: 18,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 3,
  },
  editField: {
    marginBottom: 16,
  },
  editLabel: {
    color: '#142C4C',
    fontFamily: 'InterBold',
    fontSize: 13,
    includeFontPadding: false,
    lineHeight: 18,
    marginBottom: 8,
  },
  editInput: {
    backgroundColor: '#F6FAFF',
    borderColor: 'rgba(76, 94, 118, 0.16)',
    borderRadius: 14,
    borderWidth: 1,
    color: '#142C4C',
    fontFamily: 'Inter',
    fontSize: 15,
    height: 50,
    includeFontPadding: false,
    paddingHorizontal: 14,
  },
  editInputDisabled: {
    color: '#6E7F94',
    opacity: 0.82,
  },
  saveProfileButton: {
    alignItems: 'center',
    backgroundColor: '#142C4C',
    borderRadius: 18,
    height: 56,
    justifyContent: 'center',
    marginTop: 6,
  },
  saveProfileText: {
    color: '#ffffff',
    fontFamily: 'InterBold',
    fontSize: 16,
    includeFontPadding: false,
    lineHeight: 20,
  },
});
