import { StyleSheet } from 'react-native';

export const responsiveStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#F3EEEE' },
  scroll: { flex: 1 },
  content: {
    width: '100%',
    maxWidth: 720,
    alignSelf: 'center',
    padding: 20,
    gap: 16,
  },
  hero: {
    backgroundColor: '#142C4C',
    position: 'relative',
    overflow: 'hidden',
  },
  backdrop: { ...StyleSheet.absoluteFill },
  scrim: { ...StyleSheet.absoluteFill, backgroundColor: 'rgba(7,18,32,0.55)' },
  heroContent: {
    width: '100%',
    maxWidth: 720,
    alignSelf: 'center',
    padding: 24,
    gap: 12,
  },
  brandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    justifyContent: 'center',
  },
  brand: {
    flex: 1,
    color: '#FFFFFF',
    fontFamily: 'Jomolhari',
    fontSize: 28,
    lineHeight: 42,
    textAlign: 'center',
  },
  title: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 28,
    lineHeight: 38,
  },
  heroTitle: {
    color: '#FFFFFF',
    fontFamily: 'Jomolhari',
    fontSize: 32,
    lineHeight: 42,
  },
  script: {
    color: '#70A2E3',
    fontFamily: 'Italianno',
    fontSize: 48,
    lineHeight: 58,
  },
  eyebrow: {
    color: '#FFFFFF',
    fontFamily: 'Inter',
    fontSize: 12,
    lineHeight: 18,
  },
  heroText: {
    color: '#FFFFFF',
    fontFamily: 'Inter',
    fontSize: 15,
    lineHeight: 22,
  },
  text: { color: '#4C5E76', fontFamily: 'Inter', fontSize: 15, lineHeight: 22 },
  label: {
    color: '#142C4C',
    fontFamily: 'InterSemiBold',
    fontSize: 16,
    lineHeight: 24,
  },
  heading: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 22,
    lineHeight: 32,
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    padding: 16,
    gap: 12,
    borderWidth: 1,
    borderColor: '#E5E0E0',
  },
  row: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  wrapRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 12,
  },
  copy: { flex: 1, minWidth: 0, gap: 6 },
  thumbnail: {
    width: '30%',
    maxWidth: 132,
    aspectRatio: 1.15,
    borderRadius: 12,
  },
  fullImage: { width: '100%', aspectRatio: 1.2, borderRadius: 14 },
  button: {
    backgroundColor: '#142C4C',
    borderRadius: 16,
    minHeight: 52,
    paddingHorizontal: 20,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  buttonText: {
    color: '#FFFFFF',
    fontFamily: 'InterSemiBold',
    fontSize: 16,
    lineHeight: 24,
    textAlign: 'center',
  },
  iconButton: {
    minHeight: 44,
    minWidth: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 22,
  },
  badge: {
    alignSelf: 'flex-start',
    backgroundColor: '#D8E8F8',
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  badgeText: {
    color: '#142C4C',
    fontFamily: 'InterMedium',
    fontSize: 12,
    lineHeight: 18,
  },
  price: {
    color: '#142C4C',
    fontFamily: 'InterSemiBold',
    fontSize: 22,
    lineHeight: 30,
  },
  input: {
    color: '#142C4C',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#8AA3C3',
    borderRadius: 10,
    minHeight: 48,
    padding: 12,
    fontFamily: 'Inter',
    fontSize: 16,
    lineHeight: 24,
  },
  field: { gap: 6 },
  chip: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#C1D0E0',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    minHeight: 44,
    justifyContent: 'center',
  },
  selectedChip: { backgroundColor: '#D8E8F8', borderColor: '#4689E1' },
  disabled: { opacity: 0.5 },
  center: { alignItems: 'center', gap: 20 },
  centeredText: { textAlign: 'center' },
});
