import { StyleSheet } from 'react-native';

export const serviceFormStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#F3EEEE',
  },
  background: {
    bottom: 0,
    left: 0,
    opacity: 0.56,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  scrollContent: {
    paddingBottom: 40,
    paddingHorizontal: 28,
  },
  header: {
    alignItems: 'center',
    flexDirection: 'row',
    marginBottom: 30,
  },
  backButton: {
    alignItems: 'center',
    height: 36,
    justifyContent: 'center',
    marginRight: 12,
    width: 36,
  },
  headerTitle: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 23,
    includeFontPadding: false,
    lineHeight: 33,
  },
  field: {
    marginBottom: 24,
  },
  dropdownField: {
    marginBottom: 24,
    zIndex: 20,
  },
  compactField: {
    marginBottom: 12,
  },
  label: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 18,
    includeFontPadding: false,
    lineHeight: 26,
    marginBottom: 10,
  },
  required: {
    color: '#D71920',
  },
  input: {
    backgroundColor: '#ffffff',
    borderColor: 'rgba(76, 94, 118, 0.5)',
    borderRadius: 10,
    borderWidth: 1,
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 17,
    height: 51,
    includeFontPadding: false,
    paddingHorizontal: 18,
  },
  textarea: {
    height: 94,
    paddingTop: 13,
    textAlignVertical: 'top',
  },
  selectInput: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: 'rgba(76, 94, 118, 0.5)',
    borderRadius: 10,
    borderWidth: 1,
    flexDirection: 'row',
    height: 51,
    justifyContent: 'space-between',
    paddingHorizontal: 18,
  },
  inputText: {
    color: '#4C5E76',
    flex: 1,
    fontFamily: 'Inter',
    fontSize: 17,
    includeFontPadding: false,
    lineHeight: 23,
  },
  categoryList: {
    left: 0,
    gap: 8,
    position: 'absolute',
    right: 0,
    top: 61,
    zIndex: 30,
  },
  categoryMenu: {
    backgroundColor: '#ffffff',
    borderColor: 'rgba(76, 94, 118, 0.24)',
    borderRadius: 10,
    borderWidth: 1,
    maxHeight: 220,
    overflow: 'hidden',
    padding: 6,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.18,
    shadowRadius: 12,
    elevation: 8,
  },
  categoryOption: {
    backgroundColor: '#ffffff',
    borderColor: 'transparent',
    borderRadius: 10,
    borderWidth: 1,
    minHeight: 42,
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  activeCategoryOption: {
    backgroundColor: '#142C4C',
    borderColor: '#142C4C',
  },
  categoryText: {
    color: '#142C4C',
    fontFamily: 'InterMedium',
    fontSize: 14,
    includeFontPadding: false,
  },
  activeCategoryText: {
    color: '#ffffff',
  },
  photoRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 24,
    marginTop: 12,
  },
  photoBox: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: 'rgba(76, 94, 118, 0.5)',
    borderRadius: 10,
    borderWidth: 1,
    flex: 1,
    height: 125,
    justifyContent: 'center',
    overflow: 'hidden',
    paddingHorizontal: 8,
  },
  photoPreview: {
    height: '100%',
    width: '100%',
  },
  photoText: {
    color: '#4C5E76',
    fontFamily: 'Inter',
    fontSize: 12,
    includeFontPadding: false,
    lineHeight: 16,
    marginTop: 8,
    textAlign: 'center',
  },
  browseText: {
    color: '#0F6FE4',
  },
  hint: {
    color: '#6D7E94',
    fontFamily: 'Inter',
    fontSize: 11,
    includeFontPadding: false,
    lineHeight: 15,
    marginTop: -18,
    marginBottom: 18,
  },
  inclusionsHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  iconButton: {
    alignItems: 'center',
    backgroundColor: '#142C4C',
    borderRadius: 5,
    height: 32,
    justifyContent: 'center',
    width: 32,
  },
  inclusionRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    marginBottom: 12,
  },
  inclusionInput: {
    backgroundColor: '#ffffff',
    borderColor: 'rgba(76, 94, 118, 0.5)',
    borderRadius: 10,
    borderWidth: 1,
    color: '#4C5E76',
    flex: 1,
    fontFamily: 'Inter',
    fontSize: 15,
    height: 38,
    includeFontPadding: false,
    paddingHorizontal: 18,
  },
  removeInclusionButton: {
    alignItems: 'center',
    backgroundColor: '#EAF2FA',
    borderRadius: 8,
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  activeRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    marginBottom: 18,
  },
  activeBox: {
    backgroundColor: '#E45F62',
    borderRadius: 9,
    height: 18,
    width: 18,
  },
  activeBoxOn: {
    backgroundColor: '#4FB69F',
  },
  activeText: {
    color: '#142C4C',
    fontFamily: 'InterMedium',
    fontSize: 14,
    includeFontPadding: false,
  },
  actionRow: {
    flexDirection: 'row',
    gap: 18,
    marginTop: 12,
  },
  cancelButton: {
    alignItems: 'center',
    backgroundColor: '#D3E0F1',
    borderRadius: 10,
    flex: 1,
    height: 58,
    justifyContent: 'center',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 2,
  },
  cancelText: {
    color: '#142C4C',
    fontFamily: 'Jomolhari',
    fontSize: 18,
    includeFontPadding: false,
    lineHeight: 26,
  },
  saveButton: {
    alignItems: 'center',
    backgroundColor: '#142C4C',
    borderColor: 'rgba(76, 94, 118, 0.5)',
    borderRadius: 10,
    borderWidth: 1,
    flex: 1,
    height: 58,
    justifyContent: 'center',
  },
  saveText: {
    color: '#ffffff',
    fontFamily: 'Jomolhari',
    fontSize: 18,
    includeFontPadding: false,
    lineHeight: 26,
  },
});
